# Generated by Django 6.0.1 on 2026-01-19 13:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'factory_plants',
            },
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'factory_processes',
            },
        ),
        migrations.CreateModel(
            name='WorkCenter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_centers', to='factory.plant')),
            ],
            options={
                'db_table': 'factory_work_centers',
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DOWN', 'Down'), ('MAINTENANCE', 'Maintenance')], default='ACTIVE', max_length=20)),
                ('work_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines', to='factory.workcenter')),
            ],
            options={
                'db_table': 'factory_machines',
            },
        ),
        migrations.CreateModel(
            name='WorkCenterProcess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='center_processes', to='factory.process')),
                ('work_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='center_processes', to='factory.workcenter')),
            ],
            options={
                'db_table': 'factory_work_center_processes',
                'unique_together': {('work_center', 'process')},
            },
        ),
    ]
