# Generated by Django 6.0.1 on 2026-01-19 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0001_initial'),
        ('inventory', '0002_alter_inventorylocation_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workcenter',
            name='default_wip_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staging_work_centers', to='inventory.inventorylocation'),
        ),
    ]
