# Generated by Django 6.0.1 on 2026-01-20 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0002_workcenter_default_wip_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='category',
            field=models.CharField(choices=[('EXTRUSION', 'Extrusion'), ('PRINTING', 'Printing'), ('SLITTING', 'Slitting'), ('LAMINATION', 'Lamination'), ('BAG_MAKING', 'Bag Making'), ('OTHERS', 'Others')], default='OTHERS', max_length=50),
        ),
        migrations.AddField(
            model_name='process',
            name='input_mode',
            field=models.CharField(choices=[('ROLL', 'Roll'), ('QTY', 'Quantity')], default='QTY', max_length=10),
        ),
        migrations.AddField(
            model_name='process',
            name='is_terminal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='process',
            name='output_mode',
            field=models.CharField(choices=[('ROLL', 'Roll'), ('QTY', 'Quantity')], default='QTY', max_length=10),
        ),
    ]
