# Generated by Django 6.0.1 on 2026-01-25 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0003_process_category_process_input_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='category',
            field=models.CharField(choices=[('EXTRUSION', 'Extrusion'), ('PRINTING', 'Printing'), ('SLITTING', 'Slitting'), ('LAMINATION', 'Lamination'), ('BAG_MAKING', 'Bag Making'), ('JOB_WORK', 'Job Work'), ('OTHERS', 'Others')], default='OTHERS', max_length=50),
        ),
    ]
