# Generated by Django 5.2.10 on 2026-01-26 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0004_alter_process_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='input_form',
            field=models.CharField(choices=[('ROLL', 'Roll'), ('BULK', 'Bulk'), ('POUCH', 'Pouch')], default='BULK', max_length=10),
        ),
        migrations.AddField(
            model_name='process',
            name='output_form',
            field=models.CharField(choices=[('ROLL', 'Roll'), ('BULK', 'Bulk'), ('POUCH', 'Pouch')], default='ROLL', max_length=10),
        ),
    ]
