# Generated by Django 6.0.1 on 2026-01-29 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0005_process_input_form_process_output_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='is_system',
            field=models.BooleanField(default=False),
        ),
    ]
