# Generated by Django 5.2.10 on 2026-01-31 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0006_process_is_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='allows_multi_roll',
            field=models.BooleanField(default=False, help_text='TRUE if this process requires multiple input rolls (e.g. Lamination)'),
        ),
    ]
