# Generated by Django 6.0.1 on 2026-01-31 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0007_process_allows_multi_roll'),
    ]

    operations = [
        migrations.RenameField(
            model_name='process',
            old_name='allows_multi_roll',
            new_name='allows_multi_roll_input',
        ),
        migrations.RemoveField(
            model_name='process',
            name='category',
        ),
        migrations.RemoveField(
            model_name='process',
            name='input_mode',
        ),
        migrations.RemoveField(
            model_name='process',
            name='is_terminal',
        ),
        migrations.RemoveField(
            model_name='process',
            name='output_mode',
        ),
        migrations.AddField(
            model_name='process',
            name='allows_multi_roll_output',
            field=models.BooleanField(default=False, help_text='TRUE if this process produces multiple output rolls (e.g. Slitting)'),
        ),
        migrations.AddField(
            model_name='process',
            name='consumption_mode',
            field=models.CharField(choices=[('FULL', 'Full Consume'), ('PARTIAL', 'Partial Consume')], default='FULL', help_text='FULL = entire roll consumed, PARTIAL = roll can be partially consumed', max_length=10),
        ),
        migrations.AddField(
            model_name='process',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='process',
            name='input_form',
            field=models.CharField(choices=[('BULK', 'Bulk'), ('ROLL', 'Roll')], default='BULK', max_length=10),
        ),
        migrations.AlterField(
            model_name='process',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='process',
            name='output_form',
            field=models.CharField(choices=[('BULK', 'Bulk'), ('ROLL', 'Roll')], default='ROLL', max_length=10),
        ),
    ]
