# Generated by Django 6.0.1 on 2026-02-02 14:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0008_process_physical_only_refactor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessMaterialRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('material_category', models.CharField(choices=[('INK', 'Ink'), ('ADHESIVE', 'Adhesive'), ('SOLVENT', 'Solvent'), ('GRANULE', 'Granule'), ('POD', 'POD Material'), ('ADDON', 'Add-on'), ('CHEMICAL', 'Chemical')], max_length=20)),
                ('calculation_mode', models.CharField(choices=[('PHYSICS', 'Physics Driven (GSM/Density)'), ('FIXED_QTY', 'Fixed Quantity per Unit'), ('FIXED_GSM', 'Fixed GSM (Override)'), ('RECIPE', 'Recipe Percentage')], max_length=20)),
                ('default_value', models.FloatField(default=0, help_text='e.g. GSM, Fixed Qty, or Percentage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_rules', to='factory.process')),
            ],
            options={
                'db_table': 'factory_process_material_rules',
                'unique_together': {('process', 'material_category')},
            },
        ),
    ]
