# Generated by Django 5.2.10 on 2026-02-02 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0009_processmaterialrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='modifies_existing_roll',
            field=models.BooleanField(default=False, help_text='TRUE = modifies input roll in-place (e.g. Printing), FALSE = creates new roll'),
        ),
        migrations.AddField(
            model_name='process',
            name='rolls_required',
            field=models.IntegerField(default=1, help_text='Number of input rolls required (0 for BULK input like Extrusion)'),
        ),
    ]
