# Generated by Django 5.2.10 on 2026-02-02 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0010_phase68_process_flow_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process',
            name='rolls_required',
        ),
    ]
