# Generated by Django 5.2.10 on 2026-02-02 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0011_remove_process_rolls_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process',
            name='consumption_mode',
        ),
    ]
