# Generated by Django 5.2.10 on 2026-02-03 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0013_process_physics_rewrite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='input_form',
            field=models.CharField(choices=[('NONE', 'None'), ('BULK', 'Bulk'), ('ROLL', 'Roll')], default='BULK', max_length=10),
        ),
    ]
