# Generated by Django 5.2.10 on 2026-02-09 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0015_process_final_physics'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='assigned_operator',
            field=models.ForeignKey(blank=True, help_text='Currently assigned operator for this machine', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operated_machines', to=settings.AUTH_USER_MODEL),
        ),
    ]
