# Generated by Django 5.2.10 on 2026-02-12 07:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0016_machine_operator_assignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantLegalProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('legal_name', models.CharField(max_length=255)),
                ('gstin', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField()),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('authorized_signatory_name', models.CharField(blank=True, max_length=120)),
                ('authorized_signatory_designation', models.CharField(blank=True, max_length=120)),
                ('is_verified', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='legal_profile', to='factory.plant')),
            ],
            options={
                'db_table': 'factory_plant_legal_profiles',
            },
        ),
    ]
