# Generated by Codex on 2026-02-12
from django.db import migrations


def seed_legal_profiles(apps, schema_editor):
    Plant = apps.get_model('factory', 'Plant')
    PlantLegalProfile = apps.get_model('factory', 'PlantLegalProfile')

    for plant in Plant.objects.all():
        PlantLegalProfile.objects.get_or_create(
            plant=plant,
            defaults={
                'legal_name': plant.name,
                'gstin': '',
                'address': f'{plant.name} Plant Address',
                'contact_phone': '',
                'contact_email': '',
                'authorized_signatory_name': 'Authorized Signatory',
                'authorized_signatory_designation': '',
                'is_verified': False,
                'notes': 'Auto-created from migration. Update with legal details.',
            },
        )


def noop_reverse(apps, schema_editor):
    # Keep legal profiles in place.
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('factory', '0017_plantlegalprofile'),
    ]

    operations = [
        migrations.RunPython(seed_legal_profiles, noop_reverse),
    ]
