# Generated by Django 6.0.1 on 2026-02-19 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0018_seed_plant_legal_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='standard_rate_kg_per_hour',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Standard output rate for OEE Performance calculation', max_digits=10),
        ),
        migrations.AddField(
            model_name='workcenter',
            name='standard_operating_minutes_per_day',
            field=models.PositiveIntegerField(default=480, help_text='Standard daily operating time (e.g. 480 for 8h shift, 1440 for 24h)'),
        ),
    ]
