# Generated by Django 5.2.10 on 2026-03-04 00:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0019_machine_standard_rate_kg_per_hour_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineShiftOverride',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(blank=True, default='', max_length=60)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('crosses_midnight', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.PositiveIntegerField(default=100, help_text='Lower number wins when overlaps exist.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_overrides', to='factory.machine')),
            ],
            options={
                'db_table': 'factory_machine_shift_overrides',
                'ordering': ['machine__code', 'priority', 'code'],
                'unique_together': {('machine', 'code')},
            },
        ),
        migrations.CreateModel(
            name='PlantShiftDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='Shift code (A/B/C or custom)', max_length=20)),
                ('name', models.CharField(blank=True, default='', max_length=60)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('crosses_midnight', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.PositiveIntegerField(default=100, help_text='Lower number wins when overlaps exist.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_definitions', to='factory.plant')),
            ],
            options={
                'db_table': 'factory_plant_shift_definitions',
                'ordering': ['plant__code', 'priority', 'code'],
                'unique_together': {('plant', 'code')},
            },
        ),
    ]
