# Generated by Django 5.2.10 on 2026-03-14 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0020_machineshiftoverride_plantshiftdefinition'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='include_in_official_reports',
            field=models.BooleanField(default=True, help_text='When enabled, this plant is included in official daily PDF and spreadsheet report packs.'),
        ),
    ]
