# Generated by Django 5.2.10 on 2026-03-26 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costing', '0003_costabsorptiongroup_jobcost_actual_cost_coverage_pct_and_more'),
        ('factory', '0021_plant_include_in_official_reports'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='cost_absorption_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machines', to='costing.costabsorptiongroup'),
        ),
        migrations.AddField(
            model_name='plant',
            name='default_cost_absorption_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_plants', to='costing.costabsorptiongroup'),
        ),
        migrations.AddField(
            model_name='workcenter',
            name='default_cost_absorption_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_work_centers', to='costing.costabsorptiongroup'),
        ),
    ]
