# Generated by Django 6.0.4 on 2026-05-03 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0023_machine_code_per_work_center'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='process',
            name='has_artwork',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='process',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='process',
            name='print_capable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='process',
            name='requires_lamination_adhesive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='process',
            name='requires_recipe',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='process',
            name='requires_substrate_prep',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='process',
            name='transition',
            field=models.CharField(blank=True, choices=[('BULK_TO_ROLL', 'Bulk → Roll'), ('ROLL_TO_ROLL', 'Roll → Roll'), ('ROLL_TO_BULK', 'Roll → Bulk')], default='', max_length=20),
        ),
    ]
