# Generated by Django 6.0.4 on 2026-05-25 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0024_process_active_process_has_artwork_process_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='default_margin_pct',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Plant-level default margin floor in %. Cascade rank #3 (customer overlay > pouch style > THIS > company default).', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='rate_card',
            field=models.JSONField(blank=True, default=dict, help_text='Conversion rates per stage in INR/kg. Keys: extrusion_per_kg, lamination_per_kg, printing_per_kg, slitting_per_kg, pouching_per_kg, overhead_per_kg, scrap_pct (decimal e.g. 0.04). Missing keys treated as 0 and flagged INDICATIVE.'),
        ),
    ]
