# Generated by Django 6.0.1 on 2026-01-19 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='routingrule',
            name='allowed_workcenters',
            field=models.JSONField(blank=True, default=list, help_text='Optional list of specific WC IDs'),
        ),
        migrations.AddField(
            model_name='routingrule',
            name='interplant_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='routingrule',
            name='ordered_processes',
            field=models.JSONField(default=list, help_text='Ordered list of Process codes'),
        ),
    ]
