# Generated by Django 6.0.1 on 2026-01-19 13:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cylinder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('diameter_mm', models.DecimalField(decimal_places=2, max_digits=10)),
                ('width_mm', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cell_depth_microns', models.IntegerField(default=0)),
                ('usage_count_linear_meters', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('last_serviced_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('MAINTENANCE', 'Maintenance'), ('RE_CHROME', 'Requires Re-chrome'), ('SCRAP', 'Scrapped')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tooling_cylinders',
            },
        ),
    ]
