# Generated by Django 6.0.1 on 2026-01-22 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0002_artwork_colors_count_artwork_customer'),
        ('inventory', '0010_vendor_alter_jobworkorder_vendor_name_and_more'),
        ('tooling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cylinder',
            name='artwork',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cylinders', to='artwork.artwork'),
        ),
        migrations.AddField(
            model_name='cylinder',
            name='color_name',
            field=models.CharField(default='', help_text='Specific color this cylinder prints', max_length=255),
        ),
        migrations.AddField(
            model_name='cylinder',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='cylinder',
            name='engraving_vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cylinders', to='inventory.vendor'),
        ),
        migrations.AddField(
            model_name='cylinder',
            name='life_cycles_count',
            field=models.IntegerField(default=0, help_text='Number of times mounted/used'),
        ),
    ]
