# Generated by Django 6.0.1 on 2026-01-22 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_alter_inventorylocation_type'),
        ('tooling', '0002_cylinder_artwork_cylinder_color_name_cylinder_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cylinder',
            name='storage_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cylinders', to='inventory.inventorylocation'),
        ),
    ]
