# Generated by Django 5.2.10 on 2026-01-27 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tooling', '0003_cylinder_storage_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='cylinder',
            name='circumference',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Circumference in mm (Printing Repeat)', max_digits=10),
        ),
    ]
