# Generated by Django 5.2.10 on 2026-02-18 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tooling', '0004_cylinder_circumference'),
    ]

    operations = [
        migrations.AddField(
            model_name='cylinder',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cylinder',
            name='lifecycle_status',
            field=models.CharField(default='DRAFT', max_length=20),
        ),
        migrations.AddField(
            model_name='cylinder',
            name='side',
            field=models.CharField(default='FRONT', max_length=10),
        ),
        migrations.AddField(
            model_name='cylinder',
            name='side_slot_index',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
