# Generated by Django 5.2.10 on 2026-03-14 21:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0021_plant_include_in_official_reports'),
        ('inventory', '0030_jobworkorder_dispatched_at_and_more'),
        ('tooling', '0005_cylinder_is_draft_cylinder_lifecycle_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset_type', models.CharField(choices=[('ANILOX', 'Anilox'), ('SLEEVE', 'Sleeve'), ('CUTTING_DIE', 'Cutting Die'), ('SEALING_JAW', 'Sealing Jaw'), ('CORE_SHAFT', 'Core Shaft'), ('MOUNTING_ADAPTER', 'Mounting Adapter'), ('TOOLING_OTHER', 'Other Tool')], max_length=32)),
                ('code', models.CharField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('READY', 'Ready'), ('IN_USE', 'In Use'), ('SERVICE_DUE', 'Service Due'), ('MAINTENANCE', 'Maintenance'), ('RETIRED', 'Retired')], default='READY', max_length=20)),
                ('rack_code', models.CharField(blank=True, default='', max_length=50)),
                ('slot_code', models.CharField(blank=True, default='', max_length=50)),
                ('service_due_at', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('meta_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tool_assets', to='factory.plant')),
                ('storage_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tool_assets', to='inventory.inventorylocation')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tool_assets', to='inventory.vendor')),
            ],
            options={
                'db_table': 'tooling_assets',
                'ordering': ['plant__name', 'asset_type', 'code'],
            },
        ),
    ]
