# Generated by Django 6.0.1 on 2026-01-19 13:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('factory', '0001_initial'),
        ('inventory', '0001_initial'),
        ('routing', '0001_initial'),
        ('sales', '0001_initial'),
        ('templates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_number', models.CharField(max_length=50, unique=True)),
                ('origin', models.CharField(choices=[('MTO', 'Make To Order'), ('MTS', 'Make To Stock')], default='MTO', max_length=10)),
                ('routing_step_index', models.IntegerField(default=0)),
                ('input_mode', models.CharField(choices=[('ROLL', 'Roll'), ('QUANTITY', 'Quantity')], default='QUANTITY', max_length=10)),
                ('output_mode', models.CharField(choices=[('ROLL', 'Roll'), ('QUANTITY', 'Quantity')], default='QUANTITY', max_length=10)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('uom', models.CharField(default='KG', max_length=10)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('ASSIGNED', 'Assigned'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='QUEUED', max_length=20)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jobs_from', to='inventory.inventorylocation')),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='factory.machine')),
                ('process', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='factory.process')),
                ('routing_rule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='routing.routingrule')),
                ('sales_order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.salesorderitem')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='templates.templateblueprint')),
                ('to_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jobs_to', to='inventory.inventorylocation')),
                ('work_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='factory.workcenter')),
            ],
            options={
                'db_table': 'production_jobs',
            },
        ),
    ]
