# Generated by Django 6.0.1 on 2026-01-20 16:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0003_process_category_process_input_mode_and_more'),
        ('production', '0002_productionjob_operator'),
        ('templates', '0002_rename_addon_config_templateblueprint_addons_schema_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='productionjob',
            name='hold_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productionjob',
            name='is_on_hold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productionjob',
            name='job_state',
            field=models.CharField(choices=[('PLANNED', 'Planned'), ('RELEASED', 'Released'), ('EXECUTING', 'Executing'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PLANNED', max_length=20),
        ),
        migrations.AddField(
            model_name='productionjob',
            name='planned_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productionjob',
            name='planner_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productionjob',
            name='priority',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='productionjob',
            name='source_type',
            field=models.CharField(choices=[('SALES', 'Sales Order'), ('MTS', 'Make To Stock'), ('REWORK', 'Rework'), ('JOBWORK_RETURN', 'Job Work Return')], default='SALES', max_length=20),
        ),
        migrations.CreateModel(
            name='PlannedOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference_code', models.CharField(blank=True, max_length=50, unique=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('RELEASED', 'Released'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planned_orders', to=settings.AUTH_USER_MODEL)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='factory.plant')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='templates.templateblueprint')),
            ],
            options={
                'db_table': 'production_planned_orders',
            },
        ),
    ]
