# Generated by Django 6.0.1 on 2026-01-21 14:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0003_process_category_process_input_mode_and_more'),
        ('inventory', '0006_alter_inventorylocation_code_and_more'),
        ('production', '0003_productionjob_hold_reason_productionjob_is_on_hold_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkCenterAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('WC_READY', 'Ready for Preparation'), ('ASSIGNED', 'Resource Assigned'), ('EXECUTION_READY', 'Ready for Operator')], default='WC_READY', max_length=20)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('assigned_rolls', models.ManyToManyField(blank=True, related_name='assignments', to='inventory.inventoryroll')),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='factory.machine')),
                ('production_job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='production.productionjob')),
                ('work_center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='factory.workcenter')),
            ],
            options={
                'db_table': 'production_work_center_assignments',
            },
        ),
    ]
