# Generated by Django 6.0.1 on 2026-01-21 21:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_inventorylocation_code_and_more'),
        ('materials', '0002_inventorymaterial_is_purchasable'),
        ('production', '0004_workcenterassignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionjob',
            name='job_state',
            field=models.CharField(choices=[('WAITING', 'Waiting'), ('PLANNED', 'Planned'), ('RELEASED', 'Released'), ('EXECUTING', 'Executing'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PLANNED', max_length=20),
        ),
        migrations.CreateModel(
            name='DowntimeLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('reason', models.CharField(choices=[('BREAKDOWN', 'Machine Breakdown'), ('MAINTENANCE', 'Scheduled Maintenance'), ('MATERIAL', 'Material Shortage'), ('MANPOWER', 'Manpower Shortage'), ('POWER', 'Power Failure'), ('OTHER', 'Other')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('logged_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('production_job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='downtime_logs', to='production.productionjob')),
            ],
            options={
                'db_table': 'production_downtime_logs',
            },
        ),
        migrations.CreateModel(
            name='JobExecutionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=12)),
                ('uom', models.CharField(default='KG', max_length=10)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('logged_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('production_job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='execution_logs', to='production.productionjob')),
            ],
            options={
                'db_table': 'production_execution_logs',
            },
        ),
        migrations.CreateModel(
            name='MaterialConsumptionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=12)),
                ('uom', models.CharField(default='KG', max_length=10)),
                ('is_estimated', models.BooleanField(default=False, help_text='If true, calculated by BOM, not measured.')),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materials.inventorymaterial')),
                ('production_job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumption_logs', to='production.productionjob')),
                ('roll', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.inventoryroll')),
            ],
            options={
                'db_table': 'production_consumption_logs',
            },
        ),
        migrations.CreateModel(
            name='ScrapLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=12)),
                ('uom', models.CharField(default='KG', max_length=10)),
                ('reason', models.CharField(choices=[('SETUP', 'Setup Waste'), ('TRIM', 'Trim Loss'), ('DEFECT', 'Print/Quality Defect'), ('MACHINE', 'Machine Fault'), ('MATERIAL', 'Material Issue'), ('OTHER', 'Other')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('logged_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('production_job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scrap_logs', to='production.productionjob')),
            ],
            options={
                'db_table': 'production_scrap_logs',
            },
        ),
    ]
