# Generated by Django 6.0.1 on 2026-01-22 05:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_inventoryroll_is_fg_inventoryroll_production_job'),
        ('production', '0005_alter_productionjob_job_state_downtimelog_and_more'),
        ('sales', '0006_remove_salesorder_plant'),
        ('templates', '0003_templateblueprint_requires_engineering'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinishedGoodsBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_number', models.CharField(max_length=100, unique=True)),
                ('qty_pcs', models.IntegerField(help_text='Primary UOM: Pieces')),
                ('qty_kg', models.DecimalField(blank=True, decimal_places=4, help_text='Secondary UOM: Weight in KG', max_digits=12, null=True)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('PACKED', 'Packed'), ('DISPATCHED', 'Dispatched')], default='AVAILABLE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fg_batches', to='inventory.inventorylocation')),
                ('production_job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fg_batches', to='production.productionjob')),
                ('sales_order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fg_batches', to='sales.salesorderitem')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fg_batches', to='templates.templateblueprint')),
            ],
            options={
                'verbose_name': 'Finished Goods Batch',
                'verbose_name_plural': 'Finished Goods Batches',
                'db_table': 'production_fg_batches',
            },
        ),
    ]
