# Generated by Django 6.0.1 on 2026-01-22 06:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0003_process_category_process_input_mode_and_more'),
        ('inventory', '0007_inventoryroll_is_fg_inventoryroll_production_job'),
        ('production', '0006_finishedgoodsbatch'),
        ('sales', '0006_remove_salesorder_plant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryChallan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dc_no', models.CharField(max_length=50, unique=True)),
                ('customer_name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('DISPATCHED', 'Dispatched'), ('IN_TRANSIT', 'In Transit'), ('RECEIVED', 'Received'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('vehicle_no', models.CharField(blank=True, max_length=50)),
                ('driver_name', models.CharField(blank=True, max_length=100)),
                ('driver_phone', models.CharField(blank=True, max_length=20)),
                ('dispatch_date', models.DateTimeField(blank=True, null=True)),
                ('received_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_challans', to=settings.AUTH_USER_MODEL)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='challans', to='factory.plant')),
                ('sales_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='challans', to='sales.salesorder')),
            ],
            options={
                'verbose_name': 'Delivery Challan',
                'verbose_name_plural': 'Delivery Challans',
                'db_table': 'production_delivery_challans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PackingUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label_id', models.CharField(max_length=100, unique=True)),
                ('qty_pcs', models.IntegerField(help_text='Number of pieces packed')),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=4, help_text='Weight after sealing', max_digits=12, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('SEALED', 'Sealed'), ('DISPATCHED', 'Dispatched')], default='OPEN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sealed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_packing_units', to=settings.AUTH_USER_MODEL)),
                ('fg_batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packing_units', to='production.finishedgoodsbatch')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packing_units', to='inventory.inventorylocation')),
            ],
            options={
                'verbose_name': 'Packing Unit (Gonny)',
                'verbose_name_plural': 'Packing Units (Gonnies)',
                'db_table': 'production_packing_units',
            },
        ),
        migrations.CreateModel(
            name='DeliveryChallanItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weight_kg', models.DecimalField(decimal_places=4, max_digits=12)),
                ('qty_pcs', models.IntegerField(blank=True, help_text='For gonnies/pouches only', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('challan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='production.deliverychallan')),
                ('roll', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='challan_items', to='inventory.inventoryroll')),
                ('packing_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='challan_items', to='production.packingunit')),
            ],
            options={
                'verbose_name': 'Delivery Challan Item',
                'verbose_name_plural': 'Delivery Challan Items',
                'db_table': 'production_delivery_challan_items',
            },
        ),
    ]
