# Generated by Django 6.0.1 on 2026-01-22 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0007_deliverychallan_packingunit_deliverychallanitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverychallan',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('DISPATCHED', 'Dispatched'), ('IN_TRANSIT', 'In Transit'), ('DELIVERED', 'Delivered'), ('RETURNED', 'Returned'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20),
        ),
    ]
