# Generated by Django 6.0.1 on 2026-01-22 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0008_alter_deliverychallan_status'),
        ('sales', '0006_remove_salesorder_plant'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverychallanitem',
            name='sales_order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='challan_items', to='sales.salesorderitem'),
        ),
        migrations.AddField(
            model_name='packingunit',
            name='sales_order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packing_units', to='sales.salesorderitem'),
        ),
        migrations.AlterField(
            model_name='finishedgoodsbatch',
            name='qty_kg',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Weight in KG', max_digits=12, null=True),
        ),
    ]
