# Generated by Django 6.0.1 on 2026-01-22 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0009_deliverychallanitem_sales_order_item_and_more'),
        ('sales', '0006_remove_salesorder_plant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverychallanitem',
            name='sales_order_item',
            field=models.ForeignKey(default='3359e2b8-a1f1-4561-8c1a-0207c4f1043c', on_delete=django.db.models.deletion.PROTECT, related_name='challan_items', to='sales.salesorderitem'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='finishedgoodsbatch',
            name='sales_order_item',
            field=models.ForeignKey(default='3359e2b8-a1f1-4561-8c1a-0207c4f1043c', on_delete=django.db.models.deletion.PROTECT, related_name='fg_batches', to='sales.salesorderitem'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='packingunit',
            name='sales_order_item',
            field=models.ForeignKey(default='3359e2b8-a1f1-4561-8c1a-0207c4f1043c', on_delete=django.db.models.deletion.PROTECT, related_name='packing_units', to='sales.salesorderitem'),
            preserve_default=False,
        ),
    ]
