# Generated by Django 6.0.1 on 2026-01-22 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0010_alter_deliverychallanitem_sales_order_item_and_more'),
        ('sales', '0006_remove_salesorder_plant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverychallan',
            name='sales_order',
            field=models.ForeignKey(default='72fbab44-db9c-40bb-bfdf-e9bedac30110', on_delete=django.db.models.deletion.PROTECT, related_name='challans', to='sales.salesorder'),
            preserve_default=False,
        ),
    ]
