# Generated by Django 6.0.1 on 2026-01-22 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0011_alter_deliverychallan_sales_order'),
        ('sales', '0006_remove_salesorder_plant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverychallan',
            name='sales_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='challans', to='sales.salesorder'),
        ),
    ]
