# Generated by Django 6.0.1 on 2026-01-24 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0013_stockproductionorder'),
        ('sales', '0007_customer_salesorder_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverychallanitem',
            name='sales_order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='challan_items', to='sales.salesorderitem'),
        ),
        migrations.AlterField(
            model_name='finishedgoodsbatch',
            name='sales_order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fg_batches', to='sales.salesorderitem'),
        ),
        migrations.AlterField(
            model_name='packingunit',
            name='sales_order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='packing_units', to='sales.salesorderitem'),
        ),
    ]
