# Generated by Django 5.2.10 on 2026-01-26 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0005_process_input_form_process_output_form'),
        ('production', '0014_alter_deliverychallanitem_sales_order_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionjob',
            name='input_mode',
        ),
        migrations.RemoveField(
            model_name='productionjob',
            name='output_mode',
        ),
        migrations.AddField(
            model_name='productionjob',
            name='current_process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='active_jobs', to='factory.process'),
        ),
        migrations.AddField(
            model_name='productionjob',
            name='current_step_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productionjob',
            name='input_form',
            field=models.CharField(choices=[('ROLL', 'Roll'), ('BULK', 'Bulk'), ('POUCH', 'Pouch')], default='BULK', max_length=10),
        ),
        migrations.AddField(
            model_name='productionjob',
            name='output_form',
            field=models.CharField(choices=[('ROLL', 'Roll'), ('BULK', 'Bulk'), ('POUCH', 'Pouch')], default='ROLL', max_length=10),
        ),
        migrations.AddField(
            model_name='productionjob',
            name='produced_qty',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='productionjob',
            name='remaining_qty',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
    ]
