# Generated by Django 5.2.10 on 2026-01-26 15:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0005_process_input_form_process_output_form'),
        ('production', '0015_remove_productionjob_input_mode_and_more'),
        ('templates', '0004_templateblueprint_production_mode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverychallanitem',
            name='fg_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='challan_items', to='production.finishedgoodsbatch'),
        ),
        migrations.CreateModel(
            name='PlannedStockOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('target_qty', models.DecimalField(decimal_places=2, max_digits=12)),
                ('produced_qty', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('RELEASED', 'Released'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_planner_orders', to=settings.AUTH_USER_MODEL)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='factory.plant')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='templates.templateblueprint')),
            ],
            options={
                'db_table': 'production_mts_orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='StockProductionOrder',
        ),
    ]
