# Generated by Django 5.2.10 on 2026-01-26 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0016_deliverychallanitem_fg_batch_plannedstockorder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='finishedgoodsbatch',
            name='dispatched_qty_pcs',
            field=models.IntegerField(default=0, help_text='Quantity already dispatched'),
        ),
    ]
