# Generated by Django 5.2.10 on 2026-01-26 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0017_finishedgoodsbatch_dispatched_qty_pcs'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionjob',
            name='mts_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='production.plannedstockorder'),
        ),
    ]
