# Generated by Django 5.2.10 on 2026-01-26 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0018_productionjob_mts_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='plannedstockorder',
            name='target_step_index',
            field=models.IntegerField(blank=True, help_text='Optional: Stop production at this routing step', null=True),
        ),
    ]
