# Generated by Django 5.2.10 on 2026-01-26 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0019_plannedstockorder_target_step_index'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workcenterassignment',
            old_name='assigned_rolls',
            new_name='allocated_rolls',
        ),
        migrations.RenameField(
            model_name='workcenterassignment',
            old_name='machine',
            new_name='assigned_machine',
        ),
    ]
