# Generated by Django 5.2.10 on 2026-01-27 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0020_rename_assigned_rolls_workcenterassignment_allocated_rolls_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plannedstockorder',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PLANNED', 'Planned'), ('RELEASED', 'Released'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20),
        ),
    ]
