# Generated by Django 6.0.1 on 2026-01-27 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0005_process_input_form_process_output_form'),
        ('production', '0021_alter_plannedstockorder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plannedstockorder',
            name='plant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='factory.plant'),
        ),
    ]
