# Generated by Django 6.0.1 on 2026-02-02 10:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0004_alter_inventorymaterial_category'),
        ('production', '0022_alter_plannedstockorder_plant'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobMaterialRequirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('required_qty', models.DecimalField(decimal_places=4, default=0, help_text='Total calculated requirement', max_digits=12)),
                ('assigned_qty', models.DecimalField(decimal_places=4, default=0, help_text='Total currently assigned/reserved', max_digits=12)),
                ('consumed_qty', models.DecimalField(decimal_places=4, default=0, help_text='Total actually consumed', max_digits=12)),
                ('uom', models.CharField(default='KG', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_requirements', to='materials.inventorymaterial')),
                ('production_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_requirements', to='production.productionjob')),
            ],
            options={
                'verbose_name': 'Job Material Requirement',
                'db_table': 'production_job_material_requirements',
                'unique_together': {('production_job', 'material')},
            },
        ),
    ]
