# Generated by Django 5.2.10 on 2026-02-02 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0023_jobmaterialrequirement'),
        ('templates', '0007_phase_70_step_aware_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobmaterialrequirement',
            name='process_step',
            field=models.ForeignKey(blank=True, help_text='Which process step this requirement belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_requirements', to='templates.templateprocessstep'),
        ),
    ]
