# Generated by Django 5.2.10 on 2026-02-02 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0005_consumablematerial'),
        ('production', '0024_phase_70_step_aware_templates'),
        ('templates', '0009_templateprocessstep_roll_inputs_required_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='jobmaterialrequirement',
            unique_together={('production_job', 'material', 'process_step')},
        ),
    ]
