# Generated by Django 5.2.10 on 2026-02-03 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0026_normalize_production_forms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionjob',
            name='input_form',
            field=models.CharField(choices=[('NONE', 'None'), ('BULK', 'Bulk'), ('ROLL', 'Roll')], default='BULK', max_length=10),
        ),
        migrations.AlterField(
            model_name='productionjob',
            name='output_form',
            field=models.CharField(choices=[('BULK', 'Bulk'), ('ROLL', 'Roll')], default='ROLL', max_length=10),
        ),
    ]
