# Generated by Django 5.2.10 on 2026-02-11 04:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0027_alter_productionjob_input_form_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='productionjob',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productionjob',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_production_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productionjob',
            name='closed_with_variance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productionjob',
            name='completion_force_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productionjob',
            name='completion_variance_kg',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
    ]
