# Generated by Django 5.2.10 on 2026-02-15 05:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def _extract_geometry_override(geometry):
    if not isinstance(geometry, dict):
        return {}
    base = geometry.get('base') if isinstance(geometry.get('base'), dict) else {}
    return {
        'width_mm': base.get('width_mm', geometry.get('width_mm')),
        'height_mm': base.get('height_mm', geometry.get('height_mm')),
        'gusset_mm': geometry.get('gusset_mm'),
        'repeat_length_mm': geometry.get('repeat_length_mm'),
        'adjustments': geometry.get('adjustments') if isinstance(geometry.get('adjustments'), list) else [],
    }


def backfill_mts_and_fg_metadata(apps, schema_editor):
    PlannedStockOrder = apps.get_model('production', 'PlannedStockOrder')
    FinishedGoodsBatch = apps.get_model('production', 'FinishedGoodsBatch')

    mts_qs = PlannedStockOrder.objects.select_related('template')
    for order in mts_qs.iterator():
        changed = []
        if not isinstance(order.geometry_override, dict) or not order.geometry_override:
            geom = order.template.geometry_schema if getattr(order, 'template_id', None) else {}
            order.geometry_override = _extract_geometry_override(geom or {})
            changed.append('geometry_override')
        if order.stop_step_index is None and order.target_step_index is not None:
            order.stop_step_index = order.target_step_index
            changed.append('stop_step_index')
        if changed:
            order.save(update_fields=changed)

    fg_qs = FinishedGoodsBatch.objects.select_related(
        'template',
        'sales_order_item__sales_order',
        'production_job__mts_order',
        'production_job',
    )
    for batch in fg_qs.iterator():
        changed = []

        current_job_step = getattr(batch.production_job, 'current_step_index', 0) if getattr(batch, 'production_job', None) else 0
        normalized_step = int(current_job_step or 0)
        if batch.completed_step_index != normalized_step:
            batch.completed_step_index = normalized_step
            changed.append('completed_step_index')

        geometry_override = {}
        if getattr(batch, 'sales_order_item', None) and getattr(batch.sales_order_item, 'sales_order_id', None):
            geometry_override = batch.sales_order_item.sales_order.geometry_override or {}
            if not geometry_override:
                geometry_override = _extract_geometry_override(batch.sales_order_item.geometry_snapshot or {})
        elif getattr(batch, 'production_job', None) and getattr(batch.production_job, 'mts_order_id', None):
            geometry_override = batch.production_job.mts_order.geometry_override or {}
        elif getattr(batch, 'template', None):
            geometry_override = _extract_geometry_override(batch.template.geometry_schema or {})
        geometry_override = geometry_override or {}

        if batch.geometry_override != geometry_override:
            batch.geometry_override = geometry_override
            changed.append('geometry_override')

        if changed:
            batch.save(update_fields=changed)


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0027_inventoryroll_completed_step_index_and_more'),
        ('production', '0028_productionjob_closed_at_productionjob_closed_by_and_more'),
        ('sales', '0008_salesorder_commercial_confirmed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='finishedgoodsbatch',
            name='completed_step_index',
            field=models.IntegerField(default=0, help_text='Canonical completed route step index'),
        ),
        migrations.AddField(
            model_name='finishedgoodsbatch',
            name='geometry_override',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='plannedstockorder',
            name='geometry_override',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='plannedstockorder',
            name='start_step_index',
            field=models.IntegerField(default=0, help_text='Routing step index to start execution from'),
        ),
        migrations.AddField(
            model_name='plannedstockorder',
            name='stop_step_index',
            field=models.IntegerField(blank=True, help_text='Optional: Stop production at this routing step', null=True),
        ),
        migrations.AlterField(
            model_name='plannedstockorder',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PLANNING_REQUIRED', 'Planning Required'), ('PLANNED', 'Planned'), ('RELEASED', 'Released'), ('STOCK_READY', 'Stock Ready'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20),
        ),
        migrations.CreateModel(
            name='InventoryAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('allocated_qty_kg', models.DecimalField(decimal_places=4, max_digits=12)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('CONSUMED', 'Consumed'), ('RELEASED', 'Released')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('fg_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planner_allocations', to='production.finishedgoodsbatch')),
                ('inventory_roll', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planner_allocations', to='inventory.inventoryroll')),
                ('mts_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_allocations', to='production.plannedstockorder')),
                ('sales_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_allocations', to='sales.salesorder')),
            ],
            options={
                'db_table': 'production_inventory_allocations',
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('sales_order__isnull', False), ('mts_order__isnull', True)), models.Q(('sales_order__isnull', True), ('mts_order__isnull', False)), _connector='OR'), name='allocation_exactly_one_order_fk'), models.CheckConstraint(condition=models.Q(models.Q(('inventory_roll__isnull', False), ('fg_batch__isnull', True)), models.Q(('inventory_roll__isnull', True), ('fg_batch__isnull', False)), _connector='OR'), name='allocation_exactly_one_inventory_fk'), models.CheckConstraint(condition=models.Q(('allocated_qty_kg__gt', 0)), name='allocation_qty_positive')],
            },
        ),
        migrations.RunPython(backfill_mts_and_fg_metadata, migrations.RunPython.noop),
    ]
