# Generated by Django 5.2.10 on 2026-02-17 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0029_finishedgoodsbatch_completed_step_index_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionjob',
            name='execution_model_version',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
