# Generated by Django 5.2.10 on 2026-02-18 09:40

import django.core.validators
from django.conf import settings
from django.db import migrations, models


def set_all_jobs_v2(apps, schema_editor):
    ProductionJob = apps.get_model('production', 'ProductionJob')
    ProductionJob.objects.exclude(execution_model_version=2).update(execution_model_version=2)


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0018_seed_plant_legal_profiles'),
        ('inventory', '0027_inventoryroll_completed_step_index_and_more'),
        ('production', '0030_productionjob_execution_model_version'),
        ('routing', '0002_routingrule_allowed_workcenters_and_more'),
        ('sales', '0010_alter_salesorder_execution_model_version_and_more'),
        ('templates', '0013_templateprocessstepmaterial_category_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='plannedstockorder',
            name='addons_snapshot',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='plannedstockorder',
            name='bom_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='plannedstockorder',
            name='geometry_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='plannedstockorder',
            name='layer_snapshot',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='plannedstockorder',
            name='printing_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='plannedstockorder',
            name='total_weight_kg',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='plannedstockorder',
            name='unit_weight_g',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='productionjob',
            name='execution_model_version',
            field=models.PositiveSmallIntegerField(default=2, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(2)]),
        ),
        migrations.RunPython(set_all_jobs_v2, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='productionjob',
            constraint=models.CheckConstraint(condition=models.Q(('execution_model_version', 2)), name='production_job_execution_model_version_v2_only'),
        ),
    ]
