# Generated by Django 5.2.10 on 2026-02-18 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0031_plannedstockorder_addons_snapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plannedstockorder',
            name='internal_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='plannedstockorder',
            name='spec_signature',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
