# Generated by Django 6.0.1 on 2026-02-19 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0032_plannedstockorder_internal_name_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='inventoryallocation',
            name='allocation_exactly_one_order_fk',
        ),
        migrations.RemoveConstraint(
            model_name='inventoryallocation',
            name='allocation_exactly_one_inventory_fk',
        ),
        migrations.RemoveConstraint(
            model_name='inventoryallocation',
            name='allocation_qty_positive',
        ),
        migrations.RemoveConstraint(
            model_name='productionjob',
            name='production_job_execution_model_version_v2_only',
        ),
    ]
