# Generated by Django 5.2.10 on 2026-02-19 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0033_remove_inventoryallocation_allocation_exactly_one_order_fk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plannedstockorder',
            name='output_type',
            field=models.CharField(default='WIP_ROLL', max_length=20),
        ),
        migrations.AddField(
            model_name='plannedstockorder',
            name='pod_option',
            field=models.CharField(default='NONE', max_length=20),
        ),
        migrations.AlterField(
            model_name='productionjob',
            name='source_type',
            field=models.CharField(choices=[('SALES', 'Sales Order'), ('STOCK', 'Stock Order'), ('MTS', 'Make To Stock'), ('REWORK', 'Rework'), ('JOBWORK_RETURN', 'Job Work Return')], default='SALES', max_length=20),
        ),
    ]
