# Generated by Django 5.2.10 on 2026-02-20 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0034_plannedstockorder_output_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionjob',
            name='origin',
            field=models.CharField(choices=[('MTO', 'Make To Order'), ('STOCK', 'Stock Order'), ('MTS', 'Make To Stock')], default='MTO', max_length=10),
        ),
    ]
