# Generated by Django 5.2.10 on 2026-02-20 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0006_artwork_back_colors_artwork_back_colors_count_and_more'),
        ('production', '0035_alter_productionjob_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='plannedstockorder',
            name='artwork_assignment_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plannedstockorder',
            name='assigned_artwork',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planned_stock_orders_assigned', to='artwork.artwork'),
        ),
    ]
