# Generated by Django 5.2.10 on 2026-02-23 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0036_plannedstockorder_artwork_assignment_required_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plannedstockorder',
            name='invariant_signature',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
