# Generated by Django 5.2.10 on 2026-02-27 21:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0028_packagingtransaction_packagingstock'),
        ('materials', '0008_inventorymaterial_packaging_kind_and_more'),
        ('production', '0037_plannedstockorder_invariant_signature'),
        ('sales', '0015_salesorderitem_packaging_snapshot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='finishedgoodsbatch',
            name='meta_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='plannedstockorder',
            name='packaging_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='packaging_stock_orders', to='materials.inventorymaterial'),
        ),
        migrations.AddField(
            model_name='plannedstockorder',
            name='packaging_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='plannedstockorder',
            name='quantity_uom',
            field=models.CharField(choices=[('KG', 'Kilograms'), ('PCS', 'Pieces'), ('METER', 'Meter')], default='KG', max_length=10),
        ),
        migrations.AddField(
            model_name='plannedstockorder',
            name='stock_purpose',
            field=models.CharField(choices=[('PRODUCT', 'Product'), ('PACKAGING', 'Packaging Material')], default='PRODUCT', max_length=20),
        ),
        migrations.CreateModel(
            name='RollDispatchPackRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('packed_at', models.DateTimeField(auto_now_add=True)),
                ('lines', models.JSONField(blank=True, default=list)),
                ('tx_ids', models.JSONField(blank=True, default=list)),
                ('meta_json', models.JSONField(blank=True, default=dict)),
                ('packed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roll_pack_actions', to=settings.AUTH_USER_MODEL)),
                ('roll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_pack_records', to='inventory.inventoryroll')),
                ('sales_order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='roll_dispatch_pack_records', to='sales.salesorderitem')),
            ],
            options={
                'db_table': 'production_roll_dispatch_pack_records',
                'ordering': ['-packed_at'],
                'constraints': [models.UniqueConstraint(fields=('roll', 'sales_order_item'), name='uniq_roll_dispatch_pack_record')],
            },
        ),
    ]
