# Generated by Django 5.2.10 on 2026-03-04 00:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0009_inventorymaterial_pod_profile_fields'),
        ('production', '0042_remove_plannedstockorder_pod_option'),
        ('templates', '0024_alter_templateprocessstepmaterial_formula_driver'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='downtimelog',
            name='shift_code',
            field=models.CharField(blank=True, db_index=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='downtimelog',
            name='shift_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='jobexecutionlog',
            name='shift_code',
            field=models.CharField(blank=True, db_index=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='jobexecutionlog',
            name='shift_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='scraplog',
            name='shift_code',
            field=models.CharField(blank=True, db_index=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='scraplog',
            name='shift_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.CreateModel(
            name='InkBlendTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('return_mode', models.CharField(choices=[('EXACT_COLOR_RETURN', 'Exact Color Return'), ('REMIXED_RETURN', 'Remixed Return')], default='EXACT_COLOR_RETURN', max_length=30)),
                ('returned_qty_kg', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('process_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ink_blend_transactions', to='templates.templateprocessstep')),
                ('production_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ink_blend_transactions', to='production.productionjob')),
                ('source_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ink_blend_source_transactions', to='materials.inventorymaterial')),
                ('source_requirement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ink_blend_source_transactions', to='production.jobmaterialrequirement')),
                ('target_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ink_blend_target_transactions', to='materials.inventorymaterial')),
            ],
            options={
                'db_table': 'production_ink_blend_transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
