# Generated by Django 5.2.10 on 2026-03-06 20:41

from django.db import migrations, models


def backfill_stock_strategy(apps, schema_editor):
    PlannedStockOrder = apps.get_model("production", "PlannedStockOrder")
    for order in PlannedStockOrder.objects.all().only("id", "stock_purpose", "output_type"):
        stock_purpose = str(getattr(order, "stock_purpose", "") or "").upper()
        output_type = str(getattr(order, "output_type", "") or "").upper()
        if stock_purpose == "PACKAGING" or output_type == "PACKAGING_STOCK":
            strategy = "PACKAGING_STOCK"
        elif output_type.startswith("WIP") or output_type.startswith("INTERMEDIATE"):
            strategy = "INTERMEDIATE_POOL"
        else:
            strategy = "FINAL_STOCK"
        PlannedStockOrder.objects.filter(id=order.id).update(stock_strategy=strategy)


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0043_downtimelog_shift_code_downtimelog_shift_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plannedstockorder',
            name='stock_strategy',
            field=models.CharField(choices=[('FINAL_STOCK', 'Final Stock'), ('INTERMEDIATE_POOL', 'Intermediate Pool'), ('PACKAGING_STOCK', 'Packaging Stock')], default='FINAL_STOCK', max_length=30),
        ),
        migrations.AddField(
            model_name='productionjob',
            name='current_step_issue_policy_overrides',
            field=models.JSONField(blank=True, default=list, help_text='Current-step WCM overrides for material planning lines.'),
        ),
        migrations.RunPython(backfill_stock_strategy, migrations.RunPython.noop),
    ]
