# Generated by Django 5.2.10 on 2026-03-14 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0044_plannedstockorder_stock_strategy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packingunit',
            name='extras_tare_kg',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Seal extras / tape / tags tare weight.', max_digits=12),
        ),
        migrations.AddField(
            model_name='packingunit',
            name='gross_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Gross shipment weight after sealing.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='packingunit',
            name='inner_pack_tare_kg',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Primary inner-pack tare weight.', max_digits=12),
        ),
        migrations.AddField(
            model_name='packingunit',
            name='net_product_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Net product content weight excluding packaging tare.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='packingunit',
            name='secondary_pack_tare_kg',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Gonny / secondary pack tare weight.', max_digits=12),
        ),
        migrations.AddField(
            model_name='packingunit',
            name='tare_breakdown_json',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
