# Generated by Django 5.2.12 on 2026-03-30 20:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0022_machine_cost_absorption_group_and_more'),
        ('materials', '0012_podsku_and_variants'),
        ('production', '0046_plannedbulkstockorder_and_planner_stock_class'),
        ('templates', '0029_templateprocessstep_cost_absorption_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='plannedstockorder',
            name='planner_origin_meta',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='PlannerSku',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planner_skus', to=settings.AUTH_USER_MODEL)),
                ('default_plant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='planner_skus', to='factory.plant')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planner_skus', to='templates.templateblueprint')),
            ],
            options={
                'db_table': 'production_planner_skus',
                'ordering': ['name', 'code'],
            },
        ),
        migrations.CreateModel(
            name='PlannerSkuVariant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('launch_kind', models.CharField(choices=[('FINAL_ROLL', 'Final Roll'), ('SHARED_INVARIANT_ROLL', 'Shared Invariant Roll'), ('BASE_UPSTREAM_ROLL', 'Base / Upstream Roll'), ('PACKAGING_STOCK', 'Packaging Stock'), ('POD_STOCK', 'POD Stock')], max_length=32)),
                ('default_qty', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('quantity_uom', models.CharField(choices=[('KG', 'Kilograms'), ('PCS', 'Pieces'), ('METER', 'Meter')], default='KG', max_length=10)),
                ('stock_purpose', models.CharField(choices=[('PRODUCT', 'Product'), ('PACKAGING', 'Packaging Material')], default='PRODUCT', max_length=20)),
                ('stock_strategy', models.CharField(choices=[('FINAL_STOCK', 'Final Stock'), ('INTERMEDIATE_POOL', 'Intermediate Pool'), ('PACKAGING_STOCK', 'Packaging Stock')], default='FINAL_STOCK', max_length=30)),
                ('planner_stock_class', models.CharField(blank=True, choices=[('FINAL_PRODUCT', 'Final Product'), ('FINAL_PLAIN_ROLL', 'Final Plain Roll'), ('EXTRUDED_BASE_ROLL', 'Extruded/Base Roll'), ('SHARED_INVARIANT_ROLL', 'Shared Invariant Roll'), ('PACKAGING_STOCK', 'Packaging Stock')], default='', max_length=30)),
                ('start_step_index', models.IntegerField(default=0)),
                ('stop_step_index', models.IntegerField(blank=True, null=True)),
                ('geometry_snapshot', models.JSONField(blank=True, default=dict)),
                ('layer_snapshot', models.JSONField(blank=True, default=list)),
                ('printing_snapshot', models.JSONField(blank=True, default=dict)),
                ('addons_snapshot', models.JSONField(blank=True, default=list)),
                ('packaging_snapshot', models.JSONField(blank=True, default=dict)),
                ('planner_origin_meta', models.JSONField(blank=True, default=dict)),
                ('spec_signature', models.CharField(blank=True, default='', max_length=128)),
                ('invariant_signature', models.CharField(blank=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planner_sku_variants', to=settings.AUTH_USER_MODEL)),
                ('default_plant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='planner_sku_variants', to='factory.plant')),
                ('packaging_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='planner_sku_variants', to='materials.inventorymaterial')),
                ('pod_sku_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='planner_variants', to='materials.podskuvariant')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='production.plannersku')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='planner_sku_variants', to='templates.templateblueprint')),
            ],
            options={
                'db_table': 'production_planner_sku_variants',
                'ordering': ['sku__name', 'name', 'code'],
            },
        ),
    ]
