# Generated by Codex on 2026-04-10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0014_granulequalitycode"),
        ("production", "0047_plannedstockorder_planner_origin_meta_plannersku_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="materialconsumptionlog",
            name="granule_code",
            field=models.ForeignKey(blank=True, help_text="Optional granule vendor quality code used for consumption reporting.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name="consumption_logs", to="materials.granulequalitycode"),
        ),
    ]
