# Generated by Django 5.2.13 on 2026-05-01 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0053_plannerskuvariant_invariant_signature_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionwcmauditevent',
            name='action',
            field=models.CharField(choices=[('ASSIGN_MACHINE', 'Assign Machine'), ('ALLOCATE_ROLLS', 'Allocate Rolls'), ('UNASSIGN_ROLL', 'Unassign Roll'), ('RELEASE_TO_MACHINE', 'Release To Machine'), ('MATERIAL_ISSUE', 'Material Issue'), ('MATERIAL_POLICY_OVERRIDE', 'Material Policy Override'), ('SHORT_CLOSE', 'Short Close'), ('CANCEL', 'Cancel')], max_length=32),
        ),
    ]
