# Generated by Django 6.0.4 on 2026-05-05 18:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0023_alter_commercialfamily_default_reporting_group_and_more'),
        ('production', '0056_stock_order_axis_values'),
        ('sales', '0026_salessku_axis_values_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesOrderItemInHouseDemand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('demand_kind', models.CharField(choices=[('PACKAGING', 'In-House Packaging'), ('POD', 'In-House POD')], max_length=12)),
                ('target_qty', models.DecimalField(decimal_places=4, max_digits=14)),
                ('qty_uom', models.CharField(default='KG', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('packaging_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='in_house_demand_links', to='materials.inventorymaterial')),
                ('planned_bulk_stock_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_in_house_demands', to='production.plannedbulkstockorder')),
                ('planned_stock_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_in_house_demands', to='production.plannedstockorder')),
                ('sales_order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_house_demands', to='sales.salesorderitem')),
            ],
            options={
                'db_table': 'production_sales_in_house_demand',
                'ordering': ['-created_at'],
                'unique_together': {('sales_order_item', 'demand_kind', 'packaging_material')},
            },
        ),
    ]
