# Generated by Django 6.0.4 on 2026-05-29 10:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0059_rollallocationbatchrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='DowntimeReason',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=40, unique=True)),
                ('label', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='production.downtimereason')),
            ],
            options={
                'verbose_name': 'Downtime Reason',
                'verbose_name_plural': 'Downtime Reasons',
                'db_table': 'production_downtime_reasons',
                'ordering': ['sort_order', 'code'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScrapReason',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=40, unique=True)),
                ('label', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='production.scrapreason')),
            ],
            options={
                'verbose_name': 'Scrap Reason',
                'verbose_name_plural': 'Scrap Reasons',
                'db_table': 'production_scrap_reasons',
                'ordering': ['sort_order', 'code'],
                'abstract': False,
            },
        ),
    ]
