# Generated by Django 5.2.15 on 2026-07-01 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0065_production_batch_route_graph'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionwcmauditevent',
            name='action',
            field=models.CharField(choices=[('ASSIGN_MACHINE', 'Assign Machine'), ('ALLOCATE_ROLLS', 'Allocate Rolls'), ('UNASSIGN_ROLL', 'Unassign Roll'), ('RELEASE_TO_MACHINE', 'Release To Machine'), ('MATERIAL_ISSUE', 'Material Issue'), ('MATERIAL_POLICY_OVERRIDE', 'Material Policy Override'), ('ROUTE_STEP_SKIP', 'Route Step Skip'), ('SHORT_CLOSE', 'Short Close'), ('CANCEL', 'Cancel')], max_length=32),
        ),
    ]
