# Generated by Django 6.0.7 on 2026-07-28 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0050_interplantchallanitem_granule_code'),
        ('production', '0069_delivery_challan_print_snapshot_pod'),
        ('sales', '0036_bom_weight_precision'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverychallanitem',
            name='reservation_active',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='deliverychallanitem',
            name='reservation_release_reason',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='deliverychallanitem',
            name='reservation_released_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliverychallanitem',
            name='reserved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='deliverychallanitem',
            constraint=models.UniqueConstraint(condition=models.Q(('reservation_active', True), ('roll__isnull', False)), fields=('roll',), name='uniq_active_dc_roll_reservation'),
        ),
        migrations.AddConstraint(
            model_name='deliverychallanitem',
            constraint=models.UniqueConstraint(condition=models.Q(('packing_unit__isnull', False), ('reservation_active', True)), fields=('packing_unit',), name='uniq_active_dc_gonny_reservation'),
        ),
        migrations.AddConstraint(
            model_name='deliverychallanitem',
            constraint=models.CheckConstraint(condition=models.Q(('reservation_active', False), models.Q(('fg_batch__isnull', True), ('packing_unit__isnull', True), ('roll__isnull', False)), models.Q(('fg_batch__isnull', True), ('packing_unit__isnull', False), ('roll__isnull', True)), _connector='OR'), name='active_dc_reservation_has_one_unit'),
        ),
    ]
