# Generated by Django 6.0.8 on 2026-10-09 21:14

from django.db import migrations, models


def add_jobwork_waste_reason(apps, schema_editor):
    ScrapReason = apps.get_model("production", "ScrapReason")
    ScrapReason.objects.get_or_create(
        code="JOBWORK_WASTE",
        defaults={"label": "Job work wastage", "is_active": True, "sort_order": 900},
    )


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0073_planner_operation_receipts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scraplog',
            name='reason',
            field=models.CharField(choices=[('SETUP', 'Setup Waste'), ('TRIM', 'Trim Loss'), ('DEFECT', 'Print/Quality Defect'), ('MACHINE', 'Machine Fault'), ('MATERIAL', 'Material Issue'), ('JOBWORK_WASTE', 'Job Work Wastage'), ('OTHER', 'Other')], max_length=20),
        ),
        # Reason code for wastage reported by outside job workers. Kept on
        # rollback: an existing taxonomy row is harmless to older images.
        migrations.RunPython(add_jobwork_waste_reason, migrations.RunPython.noop),
    ]
