# Generated by Django 6.0.8 on 2026-10-10 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0074_jobwork_waste_scrap_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobmaterialrequirement',
            name='supply_note',
            field=models.CharField(blank=True, db_default='', default='', max_length=255),
        ),
        migrations.AddField(
            model_name='jobmaterialrequirement',
            name='supply_source',
            field=models.CharField(choices=[('FACTORY', 'Factory stock'), ('JOBWORK_SENT', 'Sent to the job worker on a challan'), ('JOBWORK_VENDOR', "Job worker's own material")], db_default='FACTORY', default='FACTORY', max_length=16),
        ),
    ]
