# Generated by Django 6.0.1 on 2026-01-19 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_salesorder_plant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft - Sales Editing'), ('ON_HOLD', 'On Hold - Waiting for Engineering'), ('READY', 'Ready - Engineering Approved'), ('CONFIRMED', 'Confirmed - Released to Production')], default='DRAFT', max_length=20),
        ),
    ]
