# Generated by Django 6.0.1 on 2026-01-20 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_salesorder_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesorderitem',
            old_name='ordered_qty',
            new_name='qty_value',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='delivery_date',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='order_type',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='plant',
        ),
        migrations.RemoveField(
            model_name='salesorderitem',
            name='physics_snapshot',
        ),
        migrations.RemoveField(
            model_name='salesorderitem',
            name='uom',
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='addons_snapshot',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='bom_snapshot',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='geometry_snapshot',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='layer_snapshot',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='mode',
            field=models.CharField(choices=[('TEMPLATE', 'Template'), ('CUSTOM', 'Custom'), ('REPEAT', 'Repeat')], default='TEMPLATE', max_length=20),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='printing_snapshot',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='qty_uom',
            field=models.CharField(choices=[('PCS', 'Pieces'), ('KG', 'Kilograms')], default='KG', max_length=10),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='total_weight_kg',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='unit_weight_g',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='order_number',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('ON_HOLD', 'On Hold'), ('READY', 'Ready'), ('CONFIRMED', 'Confirmed')], default='DRAFT', max_length=20),
        ),
    ]
