# Generated by Django 6.0.1 on 2026-01-20 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0003_process_category_process_input_mode_and_more'),
        ('sales', '0004_rename_ordered_qty_salesorderitem_qty_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='order_type',
            field=models.CharField(choices=[('MTO', 'Make To Order'), ('REPEAT', 'Repeat Order')], default='MTO', max_length=20),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='plant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='factory.plant'),
        ),
    ]
