# Generated by Django 6.0.1 on 2026-01-20 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_salesorder_delivery_date_salesorder_order_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesorder',
            name='plant',
        ),
    ]
