# Generated by Django 5.2.10 on 2026-02-15 05:16

from django.db import migrations, models


def _extract_geometry_override(geometry):
    if not isinstance(geometry, dict):
        return {}
    base = geometry.get('base') if isinstance(geometry.get('base'), dict) else {}
    width = base.get('width_mm', geometry.get('width_mm'))
    height = base.get('height_mm', geometry.get('height_mm'))
    gusset = geometry.get('gusset_mm')
    repeat_length = geometry.get('repeat_length_mm')
    adjustments = geometry.get('adjustments') if isinstance(geometry.get('adjustments'), list) else []
    return {
        'width_mm': width,
        'height_mm': height,
        'gusset_mm': gusset,
        'repeat_length_mm': repeat_length,
        'adjustments': adjustments,
    }


def backfill_sales_geometry_override(apps, schema_editor):
    SalesOrder = apps.get_model('sales', 'SalesOrder')
    SalesOrderItem = apps.get_model('sales', 'SalesOrderItem')

    for order in SalesOrder.objects.all().iterator():
        existing = order.geometry_override if isinstance(order.geometry_override, dict) else {}
        if existing:
            continue
        first_item = (
            SalesOrderItem.objects.filter(sales_order_id=order.id)
            .select_related('template')
            .order_by('created_at')
            .first()
        )
        if not first_item:
            continue
        geometry_source = first_item.geometry_snapshot or (first_item.template.geometry_schema if first_item.template_id else {}) or {}
        order.geometry_override = _extract_geometry_override(geometry_source)
        order.save(update_fields=['geometry_override'])


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_customer_salesorder_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='commercial_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='geometry_override',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('CONFIRMED', 'Confirmed'), ('PLANNING_REQUIRED', 'Planning Required'), ('PLANNED', 'Planned'), ('RELEASED', 'Released'), ('DISPATCH_READY', 'Dispatch Ready'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('ON_HOLD', 'On Hold'), ('READY', 'Ready')], default='DRAFT', max_length=20),
        ),
        migrations.RunPython(backfill_sales_geometry_override, migrations.RunPython.noop),
    ]
