# Generated by Django 5.2.10 on 2026-02-17 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_salesorder_commercial_confirmed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='execution_model_version',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
