# Generated by Django 5.2.10 on 2026-02-18 09:40

import django.core.validators
from django.db import migrations, models


def set_all_sales_orders_v2(apps, schema_editor):
    SalesOrder = apps.get_model('sales', 'SalesOrder')
    SalesOrder.objects.exclude(execution_model_version=2).update(execution_model_version=2)


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_salesorder_execution_model_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='execution_model_version',
            field=models.PositiveSmallIntegerField(default=2, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(2)]),
        ),
        migrations.RunPython(set_all_sales_orders_v2, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='salesorder',
            constraint=models.CheckConstraint(condition=models.Q(('execution_model_version', 2)), name='sales_order_execution_model_version_v2_only'),
        ),
    ]
