# Generated by Django 5.2.10 on 2026-02-18 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_alter_salesorder_execution_model_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorderitem',
            name='spec_signature',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
