# Generated by Django 6.0.1 on 2026-02-19 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_salesorderitem_spec_signature'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='salesorder',
            name='sales_order_execution_model_version_v2_only',
        ),
    ]
