# Generated by Django 5.2.10 on 2026-02-20 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0006_artwork_back_colors_artwork_back_colors_count_and_more'),
        ('sales', '0012_remove_salesorder_sales_order_execution_model_version_v2_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='order_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='artwork_assignment_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='assigned_artwork',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_order_items_assigned', to='artwork.artwork'),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='line_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='price_basis',
            field=models.CharField(choices=[('KG', 'Per KG'), ('PCS', 'Per PCS')], default='KG', max_length=10),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
    ]
