# Generated by Django 5.2.10 on 2026-02-27 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_salesorderitem_invariant_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorderitem',
            name='packaging_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
