# Generated by Django 5.2.10 on 2026-03-15 07:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0021_plant_include_in_official_reports'),
        ('sales', '0015_salesorderitem_packaging_snapshot'),
        ('templates', '0028_alter_templateblueprint_pouch_style'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quote_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('customer_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired'), ('CONVERTED', 'Converted')], default='DRAFT', max_length=20)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('terms', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('totals_snapshot', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('converted_sales_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_quotations', to='sales.salesorder')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to='sales.customer')),
                ('plant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to='factory.plant')),
            ],
            options={
                'db_table': 'sales_quotations',
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuotationItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('line_name', models.CharField(blank=True, default='', max_length=255)),
                ('finished_good_type', models.CharField(choices=[('POUCH', 'Pouch'), ('ROLL', 'Roll')], default='POUCH', max_length=20)),
                ('roll_form', models.CharField(blank=True, choices=[('', 'Not Applicable'), ('FLAT', 'Flat'), ('FOLDED', 'Folded'), ('TUBING', 'Tubing')], default='', max_length=20)),
                ('qty_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('qty_uom', models.CharField(choices=[('PCS', 'Pieces'), ('KG', 'Kilograms')], default='PCS', max_length=10)),
                ('price_basis', models.CharField(choices=[('KG', 'Per KG'), ('PCS', 'Per PCS')], default='KG', max_length=10)),
                ('geometry_snapshot', models.JSONField(blank=True, default=dict)),
                ('layer_snapshot', models.JSONField(blank=True, default=list)),
                ('printing_snapshot', models.JSONField(blank=True, default=dict)),
                ('chemicals_snapshot', models.JSONField(blank=True, default=dict)),
                ('addons_snapshot', models.JSONField(blank=True, default=list)),
                ('packaging_snapshot', models.JSONField(blank=True, default=dict)),
                ('physics_snapshot', models.JSONField(blank=True, default=dict)),
                ('bom_snapshot', models.JSONField(blank=True, default=dict)),
                ('process_cost_rows', models.JSONField(blank=True, default=list)),
                ('commercial_snapshot', models.JSONField(blank=True, default=dict)),
                ('costing_snapshot', models.JSONField(blank=True, default=dict)),
                ('unit_weight_g', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('total_weight_kg', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('quoted_unit_price', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('quoted_line_total', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.quotation')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='templates.templateblueprint')),
            ],
            options={
                'db_table': 'sales_quotation_items',
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
