# Generated by Django 5.2.12 on 2026-04-06 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0018_quotationitem_sku_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('CONFIRMED', 'Confirmed'), ('PLANNING_REQUIRED', 'Planning Required'), ('PLANNED', 'Planned'), ('RELEASED', 'Released'), ('PACKING_READY', 'Packing Ready'), ('DISPATCH_READY', 'Dispatch Ready'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('ON_HOLD', 'On Hold'), ('READY', 'Ready')], default='DRAFT', max_length=20),
        ),
    ]
