# Generated by Django 6.0.4 on 2026-04-14 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0019_alter_salesorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='additional_addresses',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='customer',
            name='bank_details',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='customer',
            name='contact_details',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='customer',
            name='interest_calculation',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='customer',
            name='mailing_country',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='mailing_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='customer',
            name='mailing_pincode',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='mailing_state',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='pan_no',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='tcs_deductable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='tds_deductable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='under_group',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
