# Generated by Django 6.0.4 on 2026-04-21 12:53

import django.db.models.deletion
from django.db import migrations, models


def default_ship_to_from_bill_to(apps, schema_editor):
    SalesOrder = apps.get_model('sales', 'SalesOrder')
    for order in SalesOrder.objects.filter(ship_to_customer__isnull=True).iterator():
        update_fields = []
        if order.customer_id:
            order.ship_to_customer_id = order.customer_id
            update_fields.append('ship_to_customer')
        if not order.ship_to_customer_name:
            order.ship_to_customer_name = order.customer_name or ''
            update_fields.append('ship_to_customer_name')
        if update_fields:
            order.save(update_fields=update_fields)


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0020_customer_additional_addresses_customer_bank_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='remarks',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='ship_to_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ship_to_sales_orders', to='sales.customer'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='ship_to_customer_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.RunPython(default_ship_to_from_bill_to, migrations.RunPython.noop),
    ]
