# Generated by Django 6.0.4 on 2026-05-02 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0023_product_master_overlay_trace'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerproductoverlay',
            name='default_packing_recipe',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='customerproductoverlay',
            name='moq_kg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='customerproductoverlay',
            name='size_variant_code',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
