# Generated by Django 6.0.4 on 2026-05-03 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0021_productmaster_extrusion_recipe_and_more'),
        ('sales', '0024_customerproductoverlay_default_packing_recipe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerproductoverlay',
            name='axis_values',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='axis_values',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='bom_margin_pct',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='bom_material_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='material_overrides',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='product_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_order_items', to='materials.productvariant'),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='source_chip',
            field=models.CharField(choices=[('REORDER', 'Quick reorder'), ('PRESET', 'Saved preset'), ('CSV', 'Bulk paste'), ('WIZARD', 'Configure new line')], default='WIZARD', max_length=20),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='source_ref',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
