# Generated by Django 6.0.4 on 2026-05-20 16:03

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0024_process_active_process_has_artwork_process_notes_and_more'),
        ('materials', '0037_add_is_sellable_and_trading_good'),
        ('sales', '0027_sales_order_lane_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=40, unique=True)),
                ('order_date', models.DateField(default=django.utils.timezone.localdate)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('CONFIRMED', 'Confirmed'), ('DISPATCHED', 'Dispatched'), ('INVOICED', 'Invoiced'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('gst_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('grand_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('invoice_no', models.CharField(blank=True, default='', max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_trade_orders', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trade_orders', to='sales.customer')),
                ('plant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trade_orders', to='factory.plant')),
            ],
            options={
                'db_table': 'sales_trade_order',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TradeOrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('line_no', models.PositiveIntegerField(default=1)),
                ('item_type', models.CharField(choices=[('INVENTORY_MATERIAL', 'Inventory Material'), ('TRADING_GOOD', 'Trading Good')], max_length=20)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('qty', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14)),
                ('uom', models.CharField(default='PCS', max_length=10)),
                ('rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('gst_pct', models.DecimalField(decimal_places=2, default=Decimal('18.00'), max_digits=5)),
                ('line_subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('line_gst', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('inventory_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trade_order_items', to='materials.inventorymaterial')),
                ('trade_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.tradeorder')),
                ('trading_good', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trade_order_items', to='materials.tradinggood')),
            ],
            options={
                'db_table': 'sales_trade_order_item',
                'ordering': ['line_no', 'id'],
            },
        ),
    ]
