# Generated by Django 6.0.4 on 2026-05-25 20:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0028_add_trade_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_quotations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quotation',
            name='parent_quotation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisions', to='sales.quotation'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='revision_no',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='quotation',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='line_kind',
            field=models.CharField(choices=[('CATALOG', 'Catalog'), ('AD_HOC', 'Ad-hoc')], default='CATALOG', max_length=12),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='manual_rate_override',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Operator-typed rate that overrides system suggestion. Stays even if cost changes underneath.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='margin_lock',
            field=models.BooleanField(default=True, help_text='True = margin% pinned, rate computed. False = rate pinned, margin computed.'),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='spec_snapshot',
            field=models.JSONField(blank=True, default=dict, help_text='Full pouch spec for ad-hoc lines. Shape: { pouch_style_id, width_mm, height_mm, gusset_mm, flap_mm, layers: [{material_id, micron, gsm}], adhesive, print, addons, child_web_width_mm, save_as_master? }'),
        ),
    ]
