# Generated by Django 6.0.4 on 2026-05-25 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0029_quotation_approved_at_quotation_approved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerproductoverlay',
            name='margin_floor_pct',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Customer-specific minimum margin % for this product. Wins over pouch-style and plant defaults in the quotation costing cascade.', max_digits=5, null=True),
        ),
    ]
