# Generated by Django 6.0.4 on 2026-05-28 09:15

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def migrate_legacy_status(apps, schema_editor):
    """Sprint 2: convert legacy ON_HOLD/READY values to DRAFT so the
    new STATUS_CHOICES list doesn't break existing rows.
    """
    SalesOrder = apps.get_model("sales", "SalesOrder")
    legacy = SalesOrder.objects.filter(status__in=["ON_HOLD", "READY"])
    count = legacy.count()
    if count:
        legacy.update(status="DRAFT")
        import logging
        logging.getLogger("sales.migrations").info(
            "Sprint 2: converted %d SalesOrder rows from ON_HOLD/READY to DRAFT", count
        )


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0025_plant_default_margin_pct_plant_rate_card'),
        ('sales', '0031_quotation_custom_terms_quotation_discount_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(migrate_legacy_status, migrations.RunPython.noop),
        migrations.AddField(
            model_name='salesorder',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('CONFIRMED', 'Confirmed'), ('PLANNING_REQUIRED', 'Planning Required'), ('PLANNED', 'Planned'), ('RELEASED', 'Released'), ('PACKING_READY', 'Packing Ready'), ('DISPATCH_READY', 'Dispatch Ready'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20),
        ),
        migrations.CreateModel(
            name='CustomerDispatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, db_index=True, max_length=24, unique=True)),
                ('dispatch_date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('CONFIRMED', 'Confirmed'), ('DISPATCHED', 'Dispatched'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=16)),
                ('vehicle_no', models.CharField(blank=True, default='', max_length=40)),
                ('driver_name', models.CharField(blank=True, default='', max_length=80)),
                ('lr_no', models.CharField(blank=True, default='', max_length=40)),
                ('invoice_no', models.CharField(blank=True, default='', max_length=40)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_dispatches_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_dispatches', to='sales.customer')),
                ('plant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_dispatches', to='factory.plant')),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_dispatches', to='sales.salesorder')),
            ],
            options={
                'verbose_name': 'Customer dispatch',
                'verbose_name_plural': 'Customer dispatches',
                'db_table': 'sales_customer_dispatch',
                'ordering': ['-dispatch_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerDispatchLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qty_dispatched', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14)),
                ('uom', models.CharField(default='KG', max_length=12)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('dispatch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.customerdispatch')),
                ('sales_order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispatch_lines', to='sales.salesorderitem')),
            ],
            options={
                'db_table': 'sales_customer_dispatch_line',
                'ordering': ['id'],
            },
        ),
    ]
