# Generated by Django 6.0.7 on 2026-08-10 12:52

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def backfill_quotation_revision_roots(apps, schema_editor):
    Quotation = apps.get_model('sales', 'Quotation')
    rows = {row.id: row for row in Quotation.objects.all().only('id', 'parent_quotation_id')}
    roots = {}

    def resolve(row):
        seen = set()
        current = row
        while current.parent_quotation_id and current.parent_quotation_id in rows:
            if current.id in seen:
                break
            seen.add(current.id)
            current = rows[current.parent_quotation_id]
        return current.id

    for row in rows.values():
        roots[row.id] = resolve(row)
    for quotation_id, root_id in roots.items():
        Quotation.objects.filter(id=quotation_id).update(revision_root_id=root_id)


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0015_remove_artwork_ink_mapping_split'),
        ('costing', '0004_seed_cost_absorption_groups'),
        ('factory', '0027_process_route_skip_capabilities'),
        ('materials', '0050_canonical_granule_quality_codes'),
        ('sales', '0036_bom_weight_precision'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotationAcceptance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('outcome', models.CharField(choices=[('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], max_length=20)),
                ('reference', models.CharField(blank=True, default='', max_length=160)),
                ('channel', models.CharField(blank=True, default='', max_length=40)),
                ('reason', models.TextField(blank=True, default='')),
                ('received_at', models.DateTimeField()),
                ('snapshot_checksum', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'sales_quotation_acceptances',
            },
        ),
        migrations.CreateModel(
            name='QuotationActualVariance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quoted_material_cost', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('quoted_conversion_cost', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('quoted_total_cost', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('actual_material_cost', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('actual_conversion_cost', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('actual_total_cost', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('variance_amount', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('variance_percent', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=10)),
                ('actual_coverage_pct', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8)),
                ('source_snapshot', models.JSONField(blank=True, default=dict)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sales_quotation_actual_variances',
            },
        ),
        migrations.CreateModel(
            name='QuotationApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gate', models.CharField(choices=[('COMMERCIAL', 'Commercial'), ('FINANCE', 'Finance / Credit'), ('ENGINEERING', 'Engineering'), ('DELIVERY', 'Delivery Commitment')], max_length=24)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('NOT_REQUIRED', 'Not Required')], default='PENDING', max_length=20)),
                ('reason', models.TextField(blank=True, default='')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('snapshot_checksum', models.CharField(blank=True, default='', max_length=64)),
            ],
            options={
                'db_table': 'sales_quotation_approvals',
            },
        ),
        migrations.CreateModel(
            name='QuotationArtifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('artifact_type', models.CharField(choices=[('CLIENT_PDF', 'Client PDF'), ('INTERNAL_PDF', 'Internal PDF')], max_length=20)),
                ('filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(default='application/pdf', max_length=80)),
                ('byte_length', models.PositiveBigIntegerField(default=0)),
                ('checksum', models.CharField(db_index=True, max_length=64)),
                ('provenance', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sales_quotation_artifacts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuotationAuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(db_index=True, max_length=60)),
                ('note', models.TextField(blank=True, default='')),
                ('before_snapshot', models.JSONField(blank=True, default=dict)),
                ('after_snapshot', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'sales_quotation_audit_events',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuotationCostComponent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('category', models.CharField(choices=[('MATERIAL', 'Raw Material'), ('PROCESS', 'Machine / Process'), ('LABOUR', 'Labour'), ('OVERHEAD', 'Overhead'), ('WASTAGE', 'Wastage / Yield'), ('PACKING', 'Packing'), ('FREIGHT', 'Freight'), ('OTHER', 'Other')], max_length=20)),
                ('role', models.CharField(blank=True, default='', max_length=40)),
                ('label', models.CharField(max_length=180)),
                ('source_type', models.CharField(choices=[('MATERIAL_COST_SNAPSHOT', 'Material Cost Snapshot'), ('INVENTORY_FIFO', 'Inventory FIFO Source'), ('INVENTORY_AVERAGE', 'Inventory Average'), ('PROCESS_RATE', 'Process Rate'), ('COST_POOL', 'Plant Cost Pool'), ('PACKING_RECIPE', 'Packing Recipe'), ('MASTER_POLICY', 'Master Policy'), ('QUOTE_OVERRIDE', 'Approved Quote Override'), ('MISSING', 'Missing Source')], default='MISSING', max_length=32)),
                ('source_ref', models.CharField(blank=True, default='', max_length=180)),
                ('source_version', models.CharField(blank=True, default='', max_length=80)),
                ('source_lot_ref', models.CharField(blank=True, default='', max_length=120)),
                ('source_effective_at', models.DateTimeField(blank=True, null=True)),
                ('source_expires_at', models.DateTimeField(blank=True, null=True)),
                ('baseline_quantity', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=18)),
                ('baseline_uom', models.CharField(blank=True, default='', max_length=16)),
                ('baseline_rate', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=18)),
                ('baseline_available_qty', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=18)),
                ('quote_quantity', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=18)),
                ('quote_uom', models.CharField(blank=True, default='', max_length=16)),
                ('effective_rate', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=18)),
                ('component_cost', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=18)),
                ('override_rate', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('override_reason', models.TextField(blank=True, default='')),
                ('override_status', models.CharField(choices=[('NOT_REQUIRED', 'Not Required'), ('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='NOT_REQUIRED', max_length=20)),
                ('override_at', models.DateTimeField(blank=True, null=True)),
                ('override_expires_at', models.DateTimeField(blank=True, null=True)),
                ('override_approved_at', models.DateTimeField(blank=True, null=True)),
                ('readiness_status', models.CharField(choices=[('READY', 'Ready'), ('PENDING_APPROVAL', 'Pending Approval'), ('MISSING_SOURCE', 'Missing Source'), ('EXPIRED', 'Expired')], default='MISSING_SOURCE', max_length=24)),
                ('provenance', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sales_quotation_cost_components',
                'ordering': ['sequence', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuotationCostSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('FROZEN', 'Frozen')], default='DRAFT', max_length=12)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('pricing_definition', models.CharField(choices=[('MARKUP_ON_COST', 'Markup On Cost'), ('GROSS_MARGIN_ON_SALES', 'Gross Margin On Net Sales')], default='GROSS_MARGIN_ON_SALES', max_length=32)),
                ('target_percent', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=8)),
                ('material_cost', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('conversion_cost', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('total_cost', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('list_price', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('discount_amount', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('net_sale', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('tax_amount', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('rounding_amount', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('grand_total', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('contribution', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('markup_pct', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=8)),
                ('gross_margin_pct', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=8)),
                ('formula_version', models.CharField(default='QUOTE_COST_V2', max_length=40)),
                ('sensitivity_snapshot', models.JSONField(blank=True, default=dict)),
                ('readiness_snapshot', models.JSONField(blank=True, default=dict)),
                ('source_snapshot', models.JSONField(blank=True, default=dict)),
                ('effective_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('checksum', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('frozen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sales_quotation_cost_snapshots',
            },
        ),
        migrations.CreateModel(
            name='QuotationDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('EMAIL', 'Email'), ('SECURE_LINK', 'Secure Link'), ('PDF_RELEASE', 'PDF Release')], max_length=20)),
                ('recipient', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('provider', models.CharField(blank=True, default='', max_length=40)),
                ('provider_message_id', models.CharField(blank=True, default='', max_length=160)),
                ('idempotency_key', models.CharField(max_length=180, unique=True)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('error_text', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'sales_quotation_deliveries',
                'ordering': ['-attempted_at'],
            },
        ),
        migrations.AddField(
            model_name='quotation',
            name='acceptance_channel',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='quotation',
            name='acceptance_reference',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='quotation',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='accepted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations_acceptance_recorded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quotation',
            name='billing_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='quotation',
            name='cancellation_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='quotation',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations_cancelled', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quotation',
            name='contact_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='quotation',
            name='contact_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='quotation',
            name='contact_phone',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='quotation',
            name='delivery_terms',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='quotation',
            name='enquiry_reference',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='quotation',
            name='frozen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='frozen_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='quotation',
            name='payment_terms',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='quotation',
            name='place_of_supply',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='quotation',
            name='requested_delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='revision_root_id',
            field=models.UUIDField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='shipping_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='quotation',
            name='tax_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='quotation',
            name='void_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='quotation',
            name='voided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='voided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations_voided', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='artwork',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotation_items', to='artwork.artwork'),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='canonical_source_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='converted_sales_order_item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_quotation_item', to='sales.salesorderitem'),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='cost_snapshot_checksum',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='gst_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='hsn_code',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='pouch_style_master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotation_items', to='materials.pouchstylemaster'),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='product_master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotation_items', to='materials.productmaster'),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='product_master_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotation_items', to='materials.productmastersize'),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='product_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotation_items', to='materials.productvariant'),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='revised_from_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revision_items', to='sales.quotationitem'),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='spec_signature',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='bill_to_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='currency',
            field=models.CharField(default='INR', max_length=10),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='customer_po_reference',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='delivery_terms',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='payment_terms',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='quote_acceptance_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='quote_commercial_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='quote_cost_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='ship_to_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='source_quotation_revision',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='converted_order', to='sales.quotation'),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='quote_cost_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='quote_variant_snapshot',
            field=models.JSONField(blank=True, default=dict, help_text='Immutable quote-scoped configuration and Base Product Master lineage carried from the accepted quotation revision.'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved For Release'), ('SENT', 'Sent'), ('ACCEPTED', 'Accepted By Customer'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled'), ('VOID', 'Void'), ('CONVERTED', 'Converted')], default='DRAFT', max_length=20),
        ),
        migrations.RunPython(backfill_quotation_revision_roots, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='quotation',
            name='revision_root_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
        migrations.AddConstraint(
            model_name='quotation',
            constraint=models.UniqueConstraint(fields=('revision_root_id', 'revision_no'), name='sales_quote_root_revision_unique'),
        ),
        migrations.AddField(
            model_name='quotationacceptance',
            name='quotation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='client_outcome', to='sales.quotation'),
        ),
        migrations.AddField(
            model_name='quotationacceptance',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotation_outcomes_recorded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quotationactualvariance',
            name='quotation_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='actual_variance', to='sales.quotationitem'),
        ),
        migrations.AddField(
            model_name='quotationactualvariance',
            name='sales_order_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='quotation_variance', to='sales.salesorderitem'),
        ),
        migrations.AddField(
            model_name='quotationapproval',
            name='decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotation_approvals_decided', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quotationapproval',
            name='quotation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_gates', to='sales.quotation'),
        ),
        migrations.AddField(
            model_name='quotationapproval',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotation_approvals_requested', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quotationartifact',
            name='generated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotation_artifacts_generated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quotationartifact',
            name='quotation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='artifacts', to='sales.quotation'),
        ),
        migrations.AddField(
            model_name='quotationauditevent',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotation_audit_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quotationauditevent',
            name='quotation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to='sales.quotation'),
        ),
        migrations.AddField(
            model_name='quotationcostcomponent',
            name='machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotation_cost_components', to='factory.machine'),
        ),
        migrations.AddField(
            model_name='quotationcostcomponent',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotation_cost_components', to='materials.inventorymaterial'),
        ),
        migrations.AddField(
            model_name='quotationcostcomponent',
            name='material_cost_snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotation_cost_components', to='costing.materialcostsnapshot'),
        ),
        migrations.AddField(
            model_name='quotationcostcomponent',
            name='override_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotation_cost_overrides_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quotationcostcomponent',
            name='override_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotation_cost_overrides_entered', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quotationcostcomponent',
            name='process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotation_cost_components', to='factory.process'),
        ),
        migrations.AddField(
            model_name='quotationcostcomponent',
            name='process_cost_rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotation_cost_components', to='costing.processcostrate'),
        ),
        migrations.AddField(
            model_name='quotationcostcomponent',
            name='quotation_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cost_components', to='sales.quotationitem'),
        ),
        migrations.AddField(
            model_name='quotationcostsnapshot',
            name='frozen_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotation_cost_snapshots_frozen', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quotationcostsnapshot',
            name='quotation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cost_build', to='sales.quotation'),
        ),
        migrations.AddField(
            model_name='quotationcostcomponent',
            name='cost_snapshot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='sales.quotationcostsnapshot'),
        ),
        migrations.AddField(
            model_name='quotationdelivery',
            name='artifact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='sales.quotationartifact'),
        ),
        migrations.AddField(
            model_name='quotationdelivery',
            name='quotation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='sales.quotation'),
        ),
        migrations.AddField(
            model_name='quotationdelivery',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotation_deliveries_requested', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='quotationapproval',
            constraint=models.UniqueConstraint(fields=('quotation', 'gate'), name='sales_quote_gate_unique'),
        ),
        migrations.AddIndex(
            model_name='quotationcostcomponent',
            index=models.Index(fields=['cost_snapshot', 'category', 'sequence'], name='sales_qcost_snap_cat_seq'),
        ),
        migrations.AddIndex(
            model_name='quotationcostcomponent',
            index=models.Index(fields=['material', 'source_effective_at'], name='sales_qcost_mat_effective'),
        ),
    ]
