# Generated by Django 6.0.7 on 2026-08-10 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0037_quotationacceptance_quotationactualvariance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationitem',
            name='line_kind',
            field=models.CharField(choices=[('CATALOG', 'Existing ready product / variant'), ('AD_HOC', 'Quote-scoped variant under Base Product Master')], default='CATALOG', max_length=12),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='spec_snapshot',
            field=models.JSONField(blank=True, default=dict, help_text='Immutable quote-scoped configuration derived from an existing Base Product Master. Shape: { pouch_style_id, width_mm, height_mm, gusset_mm, flap_mm, layers: [{material_id, micron, gsm}], inks, adhesives, solvents, additives, addons, child_web_width_mm }. It never creates or mutates master data.'),
        ),
    ]
