# Generated by Django 6.0.8 on 2026-09-27 08:29

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0040_quotation_cost_margin_led_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationcostsnapshot',
            name='gross_margin_pct',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=28),
        ),
        migrations.AlterField(
            model_name='quotationcostsnapshot',
            name='markup_pct',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=28),
        ),
    ]
