# Generated by Django 6.0.1 on 2026-01-22 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0001_initial'),
        ('sales', '0007_customer_salesorder_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='colors_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='artwork',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='artworks', to='sales.customer'),
        ),
    ]
