# Generated by Django 5.2.10 on 2026-01-27 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0002_artwork_colors_count_artwork_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='customer',
        ),
        migrations.AddField(
            model_name='artwork',
            name='color_list',
            field=models.JSONField(default=list, help_text='List of hex codes or pantone names'),
        ),
    ]
