# Generated by Django 6.0.1 on 2026-01-30 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0003_remove_artwork_customer_artwork_color_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='color_mapping',
            field=models.JSONField(default=dict, help_text='Mapping of Template Color Name to Ink Material ID'),
        ),
    ]
