# Generated by Django 6.0.1 on 2026-01-30 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0004_artwork_color_mapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='artworks/'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='file_path',
            field=models.CharField(blank=True, help_text='S3 or Local Path to PDF/AI', max_length=500, null=True),
        ),
    ]
