# Generated by Django 5.2.10 on 2026-02-18 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0005_artwork_image_alter_artwork_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='back_colors',
            field=models.JSONField(default=list, help_text='Back side color names'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='back_colors_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='artwork',
            name='front_colors',
            field=models.JSONField(default=list, help_text='Front side color names'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='front_colors_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='artwork',
            name='print_type',
            field=models.CharField(default='FLEXO', max_length=20),
        ),
    ]
