# Generated by Django 6.0.1 on 2026-01-19 13:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryMaterial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('FILM_FAMILY', 'Film Family'), ('FILM_VARIANT', 'Film Variant'), ('GRANULE', 'Granule'), ('INK', 'Ink'), ('SOLVENT', 'Solvent'), ('ADHESIVE', 'Adhesive'), ('PACKAGING', 'Packaging'), ('ADDON', 'Add-On')], db_index=True, max_length=20)),
                ('base_uom', models.CharField(choices=[('KG', 'Kilograms (KG)'), ('PCS', 'Pieces (PCS)'), ('METER', 'Meters (M)')], default='KG', max_length=10)),
                ('density_gcm3', models.DecimalField(blank=True, decimal_places=4, help_text='Density in g/cm3 - Mandatory for FILM_FAMILY', max_digits=6, null=True)),
                ('is_extrudable', models.BooleanField(default=False, help_text='TRUE enables recipe engineering for this variant')),
                ('weight_mode', models.CharField(blank=True, choices=[('PER_MM', 'Per MM'), ('PER_PIECE', 'Per Piece'), ('FIXED', 'Fixed Weight')], max_length=20, null=True)),
                ('weight_value', models.FloatField(blank=True, help_text='Formula input value (g) based on weight_mode', null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_family', models.ForeignKey(blank=True, help_text='Mandatory for FILM_VARIANT', limit_choices_to={'category': 'FILM_FAMILY'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='materials.inventorymaterial')),
            ],
            options={
                'verbose_name': 'Material Master',
                'verbose_name_plural': 'Material Master',
                'db_table': 'inventory_materials',
            },
        ),
    ]
