# Generated by Django 6.0.1 on 2026-01-20 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorymaterial',
            name='is_purchasable',
            field=models.BooleanField(default=True, help_text='TRUE if this material can be purchased directly'),
        ),
    ]
