# Generated by Django 5.2.10 on 2026-01-28 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_inventorymaterial_is_purchasable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorymaterial',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
