# Generated by Django 5.2.10 on 2026-01-28 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_alter_inventorymaterial_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorymaterial',
            name='category',
            field=models.CharField(choices=[('FILM_FAMILY', 'Film Family'), ('FILM_VARIANT', 'Film Variant'), ('GRANULE', 'Granule'), ('INK', 'Ink'), ('SOLVENT', 'Solvent'), ('ADHESIVE', 'Adhesive'), ('PACKAGING', 'Packaging'), ('ADDON', 'Add-On'), ('POD', 'POD Film')], db_index=True, max_length=20),
        ),
    ]
