# Generated by Django 6.0.1 on 2026-02-02 14:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0004_alter_inventorymaterial_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumableMaterial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('INK', 'Ink'), ('ADHESIVE', 'Adhesive'), ('SOLVENT', 'Solvent'), ('GRANULE', 'Granule'), ('POD', 'POD Material'), ('ADDON', 'Add-on'), ('CHEMICAL', 'Chemical')], db_index=True, max_length=20)),
                ('unit', models.CharField(default='KG', max_length=10)),
                ('density_gcm3', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('gsm', models.DecimalField(blank=True, decimal_places=2, help_text='Common for Inks/Adhesives', max_digits=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('master_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumable_configurations', to='materials.inventorymaterial')),
            ],
            options={
                'verbose_name': 'Consumable Material',
                'verbose_name_plural': 'Consumable Materials',
                'db_table': 'materials_consumables',
            },
        ),
    ]
