# Generated by Django 5.2.10 on 2026-02-09 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0006_create_base_inks'),
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorymaterial',
            name='grade',
            field=models.ForeignKey(blank=True, help_text='Mandatory for FILM_VARIANT', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='materials', to='recipes.recipegrade'),
        ),
    ]
