# Generated by Django 5.2.10 on 2026-02-27 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0007_inventorymaterial_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorymaterial',
            name='packaging_kind',
            field=models.CharField(blank=True, choices=[('INNER_POUCH', 'Inner Pouch'), ('GONNY', 'Gonny'), ('TAPE', 'Tape'), ('SHEET', 'Sheet'), ('FILM', 'Film'), ('BOX', 'Box'), ('LABEL', 'Label'), ('TAG', 'Tag'), ('OTHER', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='inventorymaterial',
            name='packaging_supply_mode',
            field=models.CharField(blank=True, choices=[('PURCHASED', 'Purchased'), ('IN_HOUSE', 'In House'), ('BOTH', 'Both')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='inventorymaterial',
            name='per_sheet_base_qty',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Base-UOM qty represented by one sheet (used when a sheet line is entered in PCS).', max_digits=12, null=True),
        ),
    ]
