# Generated by Django 5.2.10 on 2026-03-14 14:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0009_inventorymaterial_pod_profile_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommercialFamily',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('default_form', models.CharField(choices=[('ROLL', 'Roll'), ('POUCH', 'Pouch')], default='ROLL', max_length=10)),
                ('default_reporting_group', models.CharField(choices=[('FILM', 'Film'), ('PRINTED', 'Printed'), ('LAMINATED', 'Laminated'), ('SEMI_FG', 'Semi-Finished'), ('FG', 'Finished Goods'), ('PACKAGING', 'Packaging'), ('OTHER', 'Other')], default='FILM', max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'commercial_families',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='inventorymaterial',
            name='commercial_family',
            field=models.ForeignKey(blank=True, help_text='Controlled business-facing family alias used for naming, stock grouping, and reporting.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='materials.commercialfamily'),
        ),
    ]
