# Generated by Django 5.2.10 on 2026-03-14 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0010_commercialfamily_inventorymaterial_commercial_family'),
        ('templates', '0028_alter_templateblueprint_pouch_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorymaterial',
            name='packaging_defaults_json',
            field=models.JSONField(blank=True, default=dict, help_text='Optional branded packaging defaults and tare settings used by packing-yard flows.'),
        ),
        migrations.AddField(
            model_name='inventorymaterial',
            name='production_template',
            field=models.ForeignKey(blank=True, help_text='Linked in-house template/blueprint used when this packaging SKU is manufactured as PACKAGING_STOCK.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packaging_materials', to='templates.templateblueprint'),
        ),
        migrations.AddField(
            model_name='inventorymaterial',
            name='tare_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Default tare weight per packaging unit used for packing and dispatch gross-weight math.', max_digits=10, null=True),
        ),
    ]
