# Generated by Django 5.2.13 on 2026-04-11 15:05

from django.db import migrations, models


def merge_packaging_film_into_sheet(apps, schema_editor):
    InventoryMaterial = apps.get_model("materials", "InventoryMaterial")
    InventoryMaterial.objects.filter(category="PACKAGING", packaging_kind="FILM").update(packaging_kind="SHEET")


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0015_granulequalitycode_drop_vendor'),
    ]

    operations = [
        migrations.RunPython(merge_packaging_film_into_sheet, noop_reverse),
        migrations.RemoveField(
            model_name='inventorymaterial',
            name='tare_weight_kg',
        ),
        migrations.AlterField(
            model_name='inventorymaterial',
            name='packaging_defaults_json',
            field=models.JSONField(blank=True, default=dict, help_text='Optional branded packaging defaults used by packing-yard flows.'),
        ),
        migrations.AlterField(
            model_name='inventorymaterial',
            name='packaging_kind',
            field=models.CharField(blank=True, choices=[('INNER_POUCH', 'Inner Pouch'), ('GONNY', 'Gonny'), ('TAPE', 'Tape'), ('SHEET', 'Sheet'), ('BOX', 'Box'), ('LABEL', 'Label'), ('TAG', 'Tag'), ('OTHER', 'Other')], max_length=20, null=True),
        ),
    ]
