# Generated by Django 6.0.4 on 2026-04-13 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0016_remove_inventorymaterial_tare_weight_kg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorymaterial',
            name='per_sheet_base_qty',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Base-UOM qty represented by one consumed unit when operators enter packaging usage in PCS.', max_digits=12, null=True),
        ),
    ]
