# Generated by Django 6.0.4 on 2026-05-02 21:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0018_productmaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductMasterSize',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=80)),
                ('label', models.CharField(max_length=120)),
                ('width_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('height_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('gusset_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('roll_width_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('thickness_micron', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('standard_qty', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('qty_uom', models.CharField(choices=[('KG', 'Kilograms'), ('PCS', 'Pieces'), ('METER', 'Meters')], default='KG', max_length=10)),
                ('default_packing', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True, default='')),
                ('active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='materials.productmaster')),
            ],
            options={
                'db_table': 'product_master_sizes',
                'ordering': ['product_master__name', 'sort_order', 'label', 'code'],
                'constraints': [models.UniqueConstraint(fields=('product_master', 'code'), name='product_master_size_unique_code')],
            },
        ),
    ]
