# Generated by Django 6.0.4 on 2026-05-03 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0019_productmastersize'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmaster',
            name='canonical_layer_stack',
            field=models.JSONField(blank=True, default=list, help_text='Reusable product-level layer identity, excluding size/artwork/customer. Execution still freezes order snapshots.'),
        ),
        migrations.AddField(
            model_name='productmaster',
            name='invariant_signature',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Product-level invariant signature used for grouping/reporting and planner reuse hints.', max_length=128),
        ),
    ]
