# Generated by Django 6.0.4 on 2026-05-03 11:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0020_productmaster_canonical_layer_stack_and_more'),
        ('recipes', '0001_initial'),
        ('templates', '0031_roll_to_bulk_output_capture_modes'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmaster',
            name='extrusion_recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='masters', to='recipes.extrusionrecipe'),
        ),
        migrations.AddField(
            model_name='productmaster',
            name='fixed_attributes',
            field=models.JSONField(blank=True, default=dict, help_text='{layer_count, fg_type, print_capable, ...}'),
        ),
        migrations.AddField(
            model_name='productmaster',
            name='layer_template',
            field=models.JSONField(blank=True, default=list, help_text='[{role, material_code, percent_of_total, grade_options, default_grade}]'),
        ),
        migrations.AddField(
            model_name='productmaster',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='masters', to='templates.templateblueprint'),
        ),
        migrations.AddField(
            model_name='productmaster',
            name='variant_axes',
            field=models.JSONField(blank=True, default=list, help_text='[{axis, type, required, options?, scope?}]'),
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=80)),
                ('axis_values', models.JSONField(blank=True, default=dict)),
                ('geometry_snapshot', models.JSONField(blank=True, default=dict)),
                ('layer_snapshot', models.JSONField(blank=True, default=list)),
                ('bom_signature', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='materials.productmaster')),
            ],
            options={
                'db_table': 'product_variants',
                'ordering': ['master__name', 'code'],
                'constraints': [models.UniqueConstraint(fields=('master', 'bom_signature'), name='product_variant_unique_per_master_axis_combo')],
            },
        ),
    ]
