# Generated by Django 6.0.4 on 2026-05-05 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0021_productmaster_extrusion_recipe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmaster',
            name='layer_template',
            field=models.JSONField(blank=True, default=list, help_text='[{role, material_code/film_variant_code, thickness_micron, grade_options, default_grade}]'),
        ),
    ]
