# Generated by Django 6.0.4 on 2026-05-05 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0022_alter_productmaster_layer_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commercialfamily',
            name='default_reporting_group',
            field=models.CharField(choices=[('FILM', 'Film'), ('PRINTED', 'Printed'), ('LAMINATED', 'Laminated'), ('SEMI_FG', 'Semi-Finished'), ('FG', 'Finished Goods'), ('PACKAGING', 'Packaging'), ('POD', 'POD'), ('OTHER', 'Other')], default='FILM', max_length=20),
        ),
        migrations.AlterField(
            model_name='productmaster',
            name='default_reporting_group',
            field=models.CharField(choices=[('FILM', 'Film'), ('PRINTED', 'Printed'), ('LAMINATED', 'Laminated'), ('SEMI_FG', 'Semi-Finished'), ('FG', 'Finished Goods'), ('PACKAGING', 'Packaging'), ('POD', 'POD'), ('OTHER', 'Other')], default='FG', max_length=20),
        ),
        migrations.AlterField(
            model_name='productmaster',
            name='product_kind',
            field=models.CharField(choices=[('POUCH', 'Pouch'), ('ROLL', 'Roll'), ('PACKAGING', 'Packaging'), ('POD', 'POD'), ('OTHER', 'Other')], default='POUCH', max_length=20),
        ),
    ]
