# Generated by Django 6.0.4 on 2026-05-08 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0025_remove_productmaster_bulk_addon_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorymaterial',
            name='packaging_kind',
            field=models.CharField(blank=True, choices=[('INNER_POUCH', 'Inner Pouch'), ('OUTER_BAG', 'Outer Bag / Packing Pouch'), ('GONNY', 'Gonny'), ('TAPE', 'Tape'), ('SHEET', 'Sheet'), ('BOX', 'Box'), ('LABEL', 'Label'), ('TAG', 'Tag'), ('OTHER', 'Other')], max_length=20, null=True),
        ),
    ]
