# Generated by Django 6.0.4 on 2026-05-20 16:03

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0024_process_active_process_has_artwork_process_notes_and_more'),
        ('materials', '0036_pouch_style_versioning'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradingGood',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('base_uom', models.CharField(choices=[('KG', 'Kilograms'), ('PCS', 'Pieces'), ('METER', 'Meters'), ('ROLL', 'Rolls'), ('BOX', 'Boxes')], default='PCS', max_length=10)),
                ('hsn_code', models.CharField(blank=True, default='', max_length=20)),
                ('default_gst_pct', models.DecimalField(decimal_places=2, default=Decimal('18.00'), max_digits=5)),
                ('default_sale_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('default_buy_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'materials_trading_good',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='inventorymaterial',
            name='default_gst_pct',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Default GST % when sold via trade order. Operator can override per-line.', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='inventorymaterial',
            name='is_sellable',
            field=models.BooleanField(default=False, help_text='TRUE if this material can be sold as a trading good (granules, film variants resold as-is)'),
        ),
        migrations.CreateModel(
            name='TradingGoodStock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qty', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14)),
                ('avg_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trading_good_stocks', to='factory.plant')),
                ('trading_good', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='materials.tradinggood')),
            ],
            options={
                'db_table': 'materials_trading_good_stock',
                'unique_together': {('trading_good', 'plant')},
            },
        ),
    ]
