# Generated by Django 6.0.4 on 2026-05-25 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0040_backfill_tradable_films_granules'),
    ]

    operations = [
        migrations.AddField(
            model_name='pouchstylemaster',
            name='conversion_stages',
            field=models.JSONField(blank=True, default=list, help_text='Which plant rate-card stages apply for this pouch style, e.g. ["extrusion","printing","slitting","pouching"]. Empty list = all stages.'),
        ),
        migrations.AddField(
            model_name='pouchstylemaster',
            name='default_margin_pct',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Style default margin floor. Cascade rank #2.', max_digits=5, null=True),
        ),
    ]
