# Generated by Django 6.0.4 on 2026-05-28 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0041_pouchstylemaster_conversion_stages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorymaterial',
            name='lead_time_override_days',
            field=models.PositiveIntegerField(blank=True, help_text='Override vendor lead time for this material.', null=True),
        ),
        migrations.AddField(
            model_name='inventorymaterial',
            name='reorder_qty',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='When stock falls below this, raise a low-stock alert.', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='inventorymaterial',
            name='safety_stock',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Buffer below which production is at risk.', max_digits=14, null=True),
        ),
    ]
