# Generated by Django 6.0.4 on 2026-05-31 09:48

from django.db import migrations, models


def backfill_open_web_contract(apps, schema_editor):
    PouchStyleMaster = apps.get_model('materials', 'PouchStyleMaster')
    ProductMasterSize = apps.get_model('materials', 'ProductMasterSize')
    default_options = {
        "OPEN_WEB": {
            "enabled": True,
            "film_area_factor": 1,
            "width_basis": "OPEN_WEB_WIDTH",
            "slit_policy": "SLIT_ALLOWED",
        },
        "LAYFLAT_TUBE": {
            "enabled": False,
            "film_area_factor": 2,
            "width_basis": "LAYFLAT_WIDTH",
            "slit_policy": "EXACT_ONLY",
        },
    }
    PouchStyleMaster.objects.filter(stock_form_options={}).update(
        default_stock_form="OPEN_WEB",
        default_width_basis="OPEN_WEB_WIDTH",
        default_slit_policy="SLIT_ALLOWED",
        stock_form_options=default_options,
    )
    for size in ProductMasterSize.objects.all().only("id", "child_target_width_mm", "film_area_width_mm"):
        updates = {
            "stock_form": "OPEN_WEB",
            "width_basis": "OPEN_WEB_WIDTH",
            "slit_policy": "SLIT_ALLOWED",
        }
        if size.film_area_width_mm is None and size.child_target_width_mm is not None:
            updates["film_area_width_mm"] = size.child_target_width_mm
        ProductMasterSize.objects.filter(id=size.id).update(**updates)


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0043_add_meter_addon_uom_and_backfill_zippers'),
    ]

    operations = [
        migrations.AddField(
            model_name='pouchstylemaster',
            name='default_slit_policy',
            field=models.CharField(choices=[('SLIT_ALLOWED', 'Slit allowed'), ('EXACT_ONLY', 'Exact stock width only')], default='SLIT_ALLOWED', help_text='Whether WCM can slit wider parent stock for this pouch style.', max_length=24),
        ),
        migrations.AddField(
            model_name='pouchstylemaster',
            name='default_stock_form',
            field=models.CharField(choices=[('OPEN_WEB', 'Open web / sheet'), ('LAYFLAT_TUBE', 'Lay-flat tube'), ('FOLDED_WEB', 'Folded web')], default='OPEN_WEB', help_text='Physical stock form this pouch style normally consumes: open web/sheet or lay-flat tubing.', max_length=24),
        ),
        migrations.AddField(
            model_name='pouchstylemaster',
            name='default_width_basis',
            field=models.CharField(choices=[('OPEN_WEB_WIDTH', 'Open-web width'), ('LAYFLAT_WIDTH', 'Lay-flat width'), ('FOLDED_WIDTH', 'Folded width')], default='OPEN_WEB_WIDTH', help_text='Meaning of the stored width for this stock form.', max_length=32),
        ),
        migrations.AddField(
            model_name='pouchstylemaster',
            name='stock_form_options',
            field=models.JSONField(blank=True, default=dict, help_text='Per-stock-form overrides. Example: {OPEN_WEB:{film_area_factor:1, slit_policy:SLIT_ALLOWED}, LAYFLAT_TUBE:{film_area_factor:2, slit_policy:EXACT_ONLY}}.'),
        ),
        migrations.AddField(
            model_name='productmastersize',
            name='film_area_width_mm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Width used for film-area weight math. Usually stock width for open web, 2 × lay-flat width for tubing.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productmastersize',
            name='slit_policy',
            field=models.CharField(choices=[('SLIT_ALLOWED', 'Slit allowed'), ('EXACT_ONLY', 'Exact stock width only')], default='SLIT_ALLOWED', help_text='Whether WCM can slit wider parent rolls for this size.', max_length=24),
        ),
        migrations.AddField(
            model_name='productmastersize',
            name='stock_form',
            field=models.CharField(choices=[('OPEN_WEB', 'Open web / sheet'), ('LAYFLAT_TUBE', 'Lay-flat tube'), ('FOLDED_WEB', 'Folded web')], db_index=True, default='OPEN_WEB', help_text='Physical stock form to consume for this size.', max_length=24),
        ),
        migrations.AddField(
            model_name='productmastersize',
            name='width_basis',
            field=models.CharField(choices=[('OPEN_WEB_WIDTH', 'Open-web width'), ('LAYFLAT_WIDTH', 'Lay-flat width'), ('FOLDED_WIDTH', 'Folded width')], default='OPEN_WEB_WIDTH', help_text='Meaning of child_target_width_mm / roll_width_mm for this size.', max_length=32),
        ),
        migrations.AlterField(
            model_name='productmastersize',
            name='child_target_width_mm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Physical stock width requirement. Auto-computed by the pouch style formula, with optional manual override.', max_digits=10, null=True),
        ),
        migrations.RunPython(backfill_open_web_contract, migrations.RunPython.noop),
    ]
