# Generated by Django 5.2.10 on 2026-01-28 16:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('factory', '0005_process_input_form_process_output_form'),
        ('materials', '0004_alter_inventorymaterial_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MRPPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='DRAFT', max_length=20)),
                ('total_demand_kg', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('total_shortage_kg', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('purchase_value_est', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mrp_plans', to=settings.AUTH_USER_MODEL)),
                ('plant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mrp_plans', to='factory.plant')),
            ],
            options={
                'db_table': 'mrp_plans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MRPRequirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('required_qty_kg', models.DecimalField(decimal_places=4, max_digits=15)),
                ('available_qty_kg', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('shortage_qty_kg', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('source_type', models.CharField(choices=[('SO', 'Sales Order'), ('MTS', 'Make To Stock')], max_length=20)),
                ('source_ref', models.CharField(max_length=100)),
                ('source_id', models.UUIDField(blank=True, null=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.inventorymaterial')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='mrp.mrpplan')),
            ],
            options={
                'db_table': 'mrp_requirements',
            },
        ),
        migrations.CreateModel(
            name='MRPSuggestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('PURCHASE', 'Purchase Suggestion'), ('MTS_PRODUCE', 'Suggest MTS Production'), ('TRANSFER', 'Inter-Plant Transfer')], max_length=20)),
                ('qty', models.DecimalField(decimal_places=4, max_digits=15)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.inventorymaterial')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='mrp.mrpplan')),
                ('source_plant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mrp_transfer_sources', to='factory.plant')),
                ('target_plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mrp_suggestions', to='factory.plant')),
            ],
            options={
                'db_table': 'mrp_suggestions',
            },
        ),
    ]
