# Generated by Django 5.2.10 on 2026-01-28 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0005_process_input_form_process_output_form'),
        ('mrp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mrpsuggestion',
            name='target_plant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mrp_suggestions', to='factory.plant'),
        ),
    ]
