# Generated by Django 6.0.1 on 2026-02-09 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0002_alter_mrpsuggestion_target_plant'),
    ]

    operations = [
        migrations.AddField(
            model_name='mrprequirement',
            name='wip_qty_kg',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=15),
        ),
    ]
