# Generated by Django 5.2.10 on 2026-02-27 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0004_mrpsuggestion_action_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='mrpplan',
            name='total_available_kg',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='mrpplan',
            name='total_wip_kg',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=15),
        ),
    ]
