# Generated by Django 6.0.4 on 2026-05-27 15:19

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('factory', '0025_plant_default_margin_pct_plant_rate_card'),
        ('inventory', '0042_add_stock_adjustment'),
        ('materials', '0041_pouchstylemaster_conversion_stages_and_more'),
        ('mrp', '0005_mrpplan_total_available_kg_mrpplan_total_wip_kg'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=24, unique=True)),
                ('order_date', models.DateField(default=django.utils.timezone.now)),
                ('expected_delivery_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent'), ('ACK', 'Acknowledged'), ('PARTIAL', 'Partially Received'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=12)),
                ('currency', models.CharField(default='INR', max_length=8)),
                ('payment_terms', models.CharField(blank=True, default='', max_length=120)),
                ('freight_terms', models.CharField(blank=True, default='', max_length=120)),
                ('delivery_address', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('gst_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('freight_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('grand_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('ack_ref', models.CharField(blank=True, default='', max_length=80)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.TextField(blank=True, default='')),
                ('status_history', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders_cancelled', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders_created', to=settings.AUTH_USER_MODEL)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='factory.plant')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders_sent', to=settings.AUTH_USER_MODEL)),
                ('source_mrp_suggestion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='mrp.mrpsuggestion')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='inventory.vendor')),
            ],
            options={
                'db_table': 'procurement_purchase_order',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('line_no', models.PositiveIntegerField(default=1)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('qty_ordered', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14)),
                ('uom', models.CharField(default='KG', max_length=12)),
                ('rate_per_uom', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('gst_pct', models.DecimalField(decimal_places=2, default=Decimal('18'), max_digits=5)),
                ('line_subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('line_gst', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('expected_delivery_date', models.DateField(blank=True, null=True)),
                ('qty_received', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14)),
                ('is_closed', models.BooleanField(default=False)),
                ('close_reason', models.TextField(blank=True, default='')),
                ('expected_width_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('expected_thickness_micron', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='po_items', to='materials.inventorymaterial')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='procurement.purchaseorder')),
            ],
            options={
                'db_table': 'procurement_purchase_order_item',
                'ordering': ['line_no', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=24, unique=True)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('vendor_invoice_no', models.CharField(blank=True, default='', max_length=60)),
                ('vendor_invoice_date', models.DateField(blank=True, null=True)),
                ('vehicle_no', models.CharField(blank=True, default='', max_length=40)),
                ('driver_name', models.CharField(blank=True, default='', max_length=80)),
                ('lr_no', models.CharField(blank=True, default='', max_length=40)),
                ('quality_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=12)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='po_receipts', to='factory.plant')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='procurement.purchaseorder')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='po_receipts_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'procurement_po_receipt',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderReceiptLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qty_received', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14)),
                ('rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('rejection_reason', models.CharField(blank=True, default='', max_length=255)),
                ('bulk_tx_id', models.UUIDField(blank=True, null=True)),
                ('roll_id', models.UUIDField(blank=True, null=True)),
                ('packaging_tx_id', models.UUIDField(blank=True, null=True)),
                ('po_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_lines', to='procurement.purchaseorderitem')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='procurement.purchaseorderreceipt')),
            ],
            options={
                'db_table': 'procurement_po_receipt_line',
            },
        ),
    ]
