# Generated by Django 6.0.4 on 2026-05-28 09:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0025_plant_default_margin_pct_plant_rate_card'),
        ('procurement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderreceipt',
            name='client_token',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderreceipt',
            constraint=models.UniqueConstraint(condition=models.Q(('vendor_invoice_no__gt', '')), fields=('purchase_order', 'vendor_invoice_no'), name='uniq_po_vendor_invoice'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderreceipt',
            constraint=models.UniqueConstraint(condition=models.Q(('client_token__gt', '')), fields=('purchase_order', 'client_token'), name='uniq_po_client_token'),
        ),
    ]
