# Generated by Django 6.0.4 on 2026-05-28 12:16

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0025_plant_default_margin_pct_plant_rate_card'),
        ('inventory', '0043_bulktransaction_vendor_and_more'),
        ('materials', '0042_inventorymaterial_lead_time_override_days_and_more'),
        ('procurement', '0002_purchaseorderreceipt_client_token_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TradingGoodReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=24, unique=True)),
                ('qty_received', models.DecimalField(decimal_places=3, max_digits=14)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=14)),
                ('vendor_invoice_no', models.CharField(blank=True, db_index=True, default='', max_length=80)),
                ('vendor_invoice_date', models.DateField(blank=True, null=True)),
                ('vehicle_no', models.CharField(blank=True, default='', max_length=40)),
                ('driver_name', models.CharField(blank=True, default='', max_length=80)),
                ('lr_no', models.CharField(blank=True, default='', max_length=40)),
                ('notes', models.TextField(blank=True, default='')),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trading_good_receipts', to='factory.plant')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trading_good_receipts', to=settings.AUTH_USER_MODEL)),
                ('trading_good', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='materials.tradinggood')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trading_good_receipts', to='inventory.vendor')),
            ],
            options={
                'db_table': 'procurement_trading_good_receipt',
                'ordering': ['-received_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('vendor_invoice_no__gt', '')), fields=('vendor', 'vendor_invoice_no'), name='uniq_tgr_vendor_invoice')],
            },
        ),
    ]
