# Generated by Django 6.0.4 on 2026-05-28 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0003_tradinggoodreceipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradinggoodreceipt',
            name='manual_po_ref',
            field=models.CharField(blank=True, db_index=True, default='', help_text="Vendor's PO ref when receiving against a PO not in our system.", max_length=80),
        ),
    ]
