# Generated by Codex on 2026-06-12

import decimal

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procurement", "0004_tradinggoodreceipt_manual_po_ref"),
    ]

    operations = [
        migrations.AddField(
            model_name="tradinggoodreceipt",
            name="gst_pct",
            field=models.DecimalField(
                decimal_places=2,
                default=decimal.Decimal("0.00"),
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="tradinggoodreceipt",
            name="line_subtotal",
            field=models.DecimalField(
                decimal_places=2,
                default=decimal.Decimal("0.00"),
                max_digits=14,
            ),
        ),
        migrations.AddField(
            model_name="tradinggoodreceipt",
            name="line_gst",
            field=models.DecimalField(
                decimal_places=2,
                default=decimal.Decimal("0.00"),
                max_digits=14,
            ),
        ),
        migrations.AddField(
            model_name="tradinggoodreceipt",
            name="line_total",
            field=models.DecimalField(
                decimal_places=2,
                default=decimal.Decimal("0.00"),
                max_digits=14,
            ),
        ),
    ]
