# Generated by Django 6.0.8 on 2026-10-09 20:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0028_enable_print_process_capabilities'),
        ('gate', '0004_documents_outward_gate_passes'),
        ('inventory', '0053_explicit_maintenance_audit'),
        ('procurement', '0005_tradinggoodreceipt_gst_totals'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=32, unique=True)),
                ('party_name', models.CharField(max_length=255)),
                ('invoice_number', models.CharField(blank=True, default='', max_length=80)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('receipt_type', models.CharField(choices=[('GOODS', 'Goods received'), ('SERVICE', 'Service / work done')], max_length=8)),
                ('received_at', models.DateTimeField()),
                ('reference', models.CharField(blank=True, default='', max_length=80)),
                ('notes', models.CharField(blank=True, default='', max_length=1000)),
                ('status', models.CharField(choices=[('POSTED', 'Posted'), ('REVERSED', 'Reversed')], default='POSTED', max_length=10)),
                ('reversed_at', models.DateTimeField(blank=True, null=True)),
                ('reversal_reason', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request_key', models.CharField(blank=True, editable=False, max_length=128, null=True, unique=True)),
                ('request_fingerprint', models.CharField(blank=True, default='', editable=False, max_length=64)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='general_receipts_created', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='general_receipts', to='gate.inwardbillintake')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='general_receipts', to='factory.plant')),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='general_receipts_received', to=settings.AUTH_USER_MODEL)),
                ('reversed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='general_receipts_reversed', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='general_receipts', to='inventory.vendor')),
            ],
            options={
                'ordering': ['-received_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='GeneralReceiptLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('line_no', models.PositiveSmallIntegerField()),
                ('line_category', models.CharField(choices=[('SPARES', 'Spares and parts'), ('MACHINERY', 'Machinery / equipment'), ('TOOLS', 'Tools'), ('CONSUMABLE', 'General consumable'), ('SAFETY', 'Safety items'), ('ELECTRICAL', 'Electrical'), ('CIVIL', 'Civil / building'), ('OFFICE', 'Office / admin'), ('SERVICE', 'Service / labour'), ('CHARGE', 'Freight / other charge')], max_length=12)),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('uom', models.CharField(max_length=8)),
                ('rate', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('gst_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('disposition', models.CharField(choices=[('KEPT_IN_STORE', 'Kept in store'), ('INSTALLED', 'Installed / fitted'), ('CONSUMED', 'Used immediately'), ('NOT_APPLICABLE', 'Not applicable')], default='NOT_APPLICABLE', max_length=16)),
                ('equipment_text', models.CharField(blank=True, default='', max_length=160)),
                ('serial_no', models.CharField(blank=True, default='', max_length=80)),
                ('remarks', models.CharField(blank=True, default='', max_length=255)),
                ('gate_pass_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='general_receipt_lines', to='gate.gatepassline')),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='general_receipt_lines', to='factory.machine')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='procurement.generalreceipt')),
            ],
            options={
                'ordering': ['line_no'],
            },
        ),
        migrations.AddIndex(
            model_name='generalreceipt',
            index=models.Index(fields=['plant', 'received_at'], name='general_receipt_plant_idx'),
        ),
        migrations.AddIndex(
            model_name='generalreceipt',
            index=models.Index(fields=['vendor', 'received_at'], name='general_receipt_vendor_idx'),
        ),
        migrations.AddConstraint(
            model_name='generalreceipt',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'POSTED'), ('reversed_at__isnull', False), _connector='OR'), name='general_receipt_reversal_timestamp'),
        ),
        migrations.AddIndex(
            model_name='generalreceiptline',
            index=models.Index(fields=['machine'], name='general_line_machine_idx'),
        ),
        migrations.AddConstraint(
            model_name='generalreceiptline',
            constraint=models.UniqueConstraint(fields=('receipt', 'line_no'), name='general_receipt_line_unique'),
        ),
        migrations.AddConstraint(
            model_name='generalreceiptline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='general_line_qty_positive'),
        ),
        migrations.AddConstraint(
            model_name='generalreceiptline',
            constraint=models.CheckConstraint(condition=models.Q(('amount__isnull', True), ('amount__gte', 0), _connector='OR'), name='general_line_amount_nonnegative'),
        ),
    ]
