# Generated by Django 6.0.1 on 2026-01-19 13:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('routing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateBlueprint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('fg_type', models.CharField(choices=[('POUCH', 'Pouch'), ('ROLL', 'Roll')], max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('LIVE', 'Live'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20)),
                ('created_from', models.CharField(choices=[('ADMIN', 'Administrative Standard'), ('CUSTOM_ORDER', 'Custom Order')], default='ADMIN', max_length=20)),
                ('geometry_schema', models.JSONField(default=dict, help_text='Dimensions, Faces, Repeats')),
                ('adjustment_schema', models.JSONField(default=list, help_text='Gusset, Flap, Zipper dimensions')),
                ('layer_stack', models.JSONField(default=list, help_text='Ordered list of Films/Resins')),
                ('printing_config', models.JSONField(default=dict, help_text='Type (ROTO/FLEXO), Colors, etc.')),
                ('addon_config', models.JSONField(default=list, help_text='Zippers, Valves, etc.')),
                ('chemistry_gsm', models.JSONField(default=dict, help_text="{'ink': 0, 'adhesive': 0, 'solvent': 0}")),
                ('editable_fields', models.JSONField(default=list, help_text='Fields Sales can override')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('routing_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='routing.routingrule')),
            ],
            options={
                'db_table': 'production_templates',
            },
        ),
    ]
