# Generated by Django 6.0.1 on 2026-01-19 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='templateblueprint',
            old_name='addon_config',
            new_name='addons_schema',
        ),
        migrations.RenameField(
            model_name='templateblueprint',
            old_name='layer_stack',
            new_name='layer_schema',
        ),
        migrations.RenameField(
            model_name='templateblueprint',
            old_name='printing_config',
            new_name='printing_schema',
        ),
        migrations.AddField(
            model_name='templateblueprint',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='templateblueprint',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='templateblueprint',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='templateblueprint',
            name='version',
            field=models.IntegerField(default=1),
        ),
    ]
