# Generated by Django 6.0.1 on 2026-01-20 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0002_rename_addon_config_templateblueprint_addons_schema_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='templateblueprint',
            name='requires_engineering',
            field=models.BooleanField(default=False),
        ),
    ]
