# Generated by Django 6.0.1 on 2026-01-24 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0003_templateblueprint_requires_engineering'),
    ]

    operations = [
        migrations.AddField(
            model_name='templateblueprint',
            name='production_mode',
            field=models.CharField(choices=[('MTO', 'Make To Order'), ('MTS', 'Make To Stock')], default='MTO', max_length=5),
        ),
    ]
