# Generated by Django 5.2.10 on 2026-01-27 07:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0003_remove_artwork_customer_artwork_color_list'),
        ('templates', '0004_templateblueprint_production_mode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='templateblueprint',
            name='artwork',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates', to='artwork.artwork'),
        ),
        migrations.AddField(
            model_name='templateblueprint',
            name='printing_type',
            field=models.CharField(choices=[('NONE', 'None'), ('FLEXO', 'Flexo'), ('ROTO', 'Rotogravure'), ('DIGITAL', 'Digital')], default='NONE', max_length=20),
        ),
        migrations.AddField(
            model_name='templateblueprint',
            name='required_color_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='templateblueprint',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('ENGINEERING', 'Engineering Review'), ('APPROVED', 'Approved'), ('LIVE', 'Live'), ('OBSOLETE', 'Obsolete')], default='DRAFT', max_length=20),
        ),
        migrations.CreateModel(
            name='TemplateRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('dimensions', models.CharField(help_text='e.g. 100x200mm', max_length=255)),
                ('printing_type', models.CharField(choices=[('NONE', 'None'), ('FLEXO', 'Flexo'), ('ROTO', 'Rotogravure'), ('DIGITAL', 'Digital')], default='NONE', max_length=20)),
                ('required_color_count', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('NEW', 'New Request'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected')], default='NEW', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='templates.templateblueprint')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='template_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'template_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
