# Generated by Django 5.2.10 on 2026-01-28 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0005_templateblueprint_artwork_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='templateblueprint',
            name='pod_type',
            field=models.CharField(choices=[('NONE', 'None'), ('SINGLE', 'Single POD'), ('DOUBLE', 'Double POD')], default='NONE', max_length=10),
        ),
    ]
