# Generated by Django 5.2.10 on 2026-02-02 17:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0010_phase68_process_flow_fields'),
        ('materials', '0005_consumablematerial'),
        ('templates', '0006_templateblueprint_pod_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateProcessStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence_number', models.IntegerField(help_text='Execution order (1, 2, 3...)')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='template_steps', to='factory.process')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_steps', to='templates.templateblueprint')),
            ],
            options={
                'db_table': 'template_process_steps',
                'ordering': ['sequence_number'],
                'unique_together': {('template', 'sequence_number')},
            },
        ),
        migrations.CreateModel(
            name='TemplateMaterial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=4, help_text='Amount per unit of calculation mode', max_digits=12)),
                ('uom', models.CharField(default='KG', max_length=10)),
                ('calculation_mode', models.CharField(choices=[('FIXED', 'Fixed Quantity'), ('PER_KG', 'Per KG Output'), ('PER_PIECE', 'Per Piece'), ('PER_SQM', 'Per Square Meter'), ('GSM', 'GSM Based (Area × GSM)'), ('RECIPE', 'Recipe Percentage')], default='PER_KG', max_length=20)),
                ('is_optional', models.BooleanField(default=False, help_text='If true, not required for production')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='template_usages', to='materials.inventorymaterial')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_materials', to='templates.templateblueprint')),
                ('process_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='templates.templateprocessstep')),
            ],
            options={
                'db_table': 'template_materials',
                'ordering': ['process_step__sequence_number', 'id'],
                'unique_together': {('process_step', 'material')},
            },
        ),
    ]
