# Generated by Django 5.2.10 on 2026-02-02 20:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0005_consumablematerial'),
        ('templates', '0007_phase_70_step_aware_templates'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateProcessStepMaterial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('ROLL', 'Roll (Main Input)'), ('BULK', 'Bulk (Consumable)')], default='BULK', max_length=10)),
                ('quantity_mode', models.CharField(choices=[('GSM', 'GSM Based (Area × GSM)'), ('KG', 'KG per Unit'), ('PCS', 'Pieces per Unit'), ('COUNT', 'Fixed Count'), ('%', 'Percentage of Total')], default='KG', max_length=10)),
                ('value', models.DecimalField(decimal_places=4, help_text='Quantity value based on mode', max_digits=12)),
                ('is_optional', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='template_usages', to='materials.inventorymaterial')),
                ('template_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='templates.templateprocessstep')),
            ],
            options={
                'db_table': 'template_process_step_materials',
                'ordering': ['template_step__sequence_number', 'id'],
                'unique_together': {('template_step', 'material')},
            },
        ),
        migrations.DeleteModel(
            name='TemplateMaterial',
        ),
    ]
