# Generated by Django 5.2.10 on 2026-02-02 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0008_templateprocessstepmaterial_delete_templatematerial'),
    ]

    operations = [
        migrations.AddField(
            model_name='templateprocessstep',
            name='roll_inputs_required',
            field=models.IntegerField(default=0, help_text='Number of rolls required from previous steps'),
        ),
        migrations.AlterField(
            model_name='templateprocessstepmaterial',
            name='quantity_mode',
            field=models.CharField(choices=[('KG', 'KG per Unit'), ('GSM', 'GSM Based (Area × GSM)'), ('PCS', 'Pieces per Unit'), ('PERCENT', 'Percentage of Total'), ('RECIPE', 'Recipe Based')], default='KG', max_length=10),
        ),
    ]
