# Generated by Django 5.2.10 on 2026-02-03 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0010_remove_roll_inputs_required_and_material_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templateprocessstepmaterial',
            name='value',
            field=models.DecimalField(decimal_places=8, help_text='Quantity value based on mode', max_digits=12),
        ),
    ]
