# Generated by Django 5.2.10 on 2026-02-17 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0007_inventorymaterial_grade'),
        ('templates', '0012_templateprocesssteprollspec'),
    ]

    operations = [
        migrations.AddField(
            model_name='templateprocessstepmaterial',
            name='category_code',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='templateprocessstepmaterial',
            name='source_kind',
            field=models.CharField(choices=[('MATERIAL', 'Exact Material'), ('CATEGORY', 'Broad Category')], default='MATERIAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='templateprocessstepmaterial',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='template_usages', to='materials.inventorymaterial'),
        ),
    ]
