# Generated by Django 5.2.10 on 2026-02-18 09:40

import django.db.models.deletion
from django.db import migrations, models


def normalize_step_materials_to_category(apps, schema_editor):
    StepMaterial = apps.get_model('templates', 'TemplateProcessStepMaterial')

    rows = (
        StepMaterial.objects.select_related('material')
        .order_by('template_step_id', 'id')
    )

    # Normalize every row into CATEGORY mode.
    for row in rows:
        code = str(getattr(row, 'category_code', '') or '').strip().upper()
        material = getattr(row, 'material', None)
        if not code:
            code = str(getattr(material, 'category', '') or '').strip().upper()
        if not code and getattr(row, 'material_id', None):
            code = f"MATERIAL_{str(row.material_id).replace('-', '')[:8].upper()}"
        if not code:
            code = "UNMAPPED"
        row.source_kind = 'CATEGORY'
        row.category_code = code
        row.material_id = None
        row.save(update_fields=['source_kind', 'category_code', 'material'])

    # Collapse duplicate category rows per step.
    grouped = {}
    for row in StepMaterial.objects.order_by('id'):
        key = (row.template_step_id, str(row.category_code or '').strip().upper())
        grouped.setdefault(key, []).append(row)

    for _key, dupes in grouped.items():
        if len(dupes) <= 1:
            continue
        keep = dupes[0]
        for extra in dupes[1:]:
            keep.value = (keep.value or 0) + (extra.value or 0)
            extra.delete()
        keep.save(update_fields=['value'])


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0007_inventorymaterial_grade'),
        ('recipes', '0001_initial'),
        ('templates', '0013_templateprocessstepmaterial_category_code_and_more'),
    ]

    operations = [
        migrations.RunPython(normalize_step_materials_to_category, migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name='templateprocessstepmaterial',
            unique_together={('template_step', 'category_code')},
        ),
        migrations.AlterField(
            model_name='templateblueprint',
            name='addons_schema',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='templateblueprint',
            name='adjustment_schema',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='templateblueprint',
            name='chemistry_gsm',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='templateblueprint',
            name='editable_fields',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='templateblueprint',
            name='geometry_schema',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='templateblueprint',
            name='layer_schema',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='templateblueprint',
            name='printing_schema',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='templateprocessstepmaterial',
            name='source_kind',
            field=models.CharField(choices=[('CATEGORY', 'Broad Category')], default='CATEGORY', max_length=20),
        ),
        migrations.AlterField(
            model_name='templateprocesssteprollspec',
            name='output_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='template_step_roll_specs', to='recipes.recipegrade'),
        ),
        migrations.AlterField(
            model_name='templateprocesssteprollspec',
            name='output_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='template_step_roll_specs', to='materials.inventorymaterial'),
        ),
        migrations.DeleteModel(
            name='TemplateRequest',
        ),
    ]
