# Generated by Django 5.2.10 on 2026-02-19 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0014_alter_templateprocessstepmaterial_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templateblueprint',
            name='addons_schema',
        ),
        migrations.RemoveField(
            model_name='templateblueprint',
            name='adjustment_schema',
        ),
        migrations.RemoveField(
            model_name='templateblueprint',
            name='chemistry_gsm',
        ),
        migrations.RemoveField(
            model_name='templateblueprint',
            name='created_from',
        ),
        migrations.RemoveField(
            model_name='templateblueprint',
            name='editable_fields',
        ),
        migrations.RemoveField(
            model_name='templateblueprint',
            name='geometry_schema',
        ),
        migrations.RemoveField(
            model_name='templateblueprint',
            name='layer_schema',
        ),
        migrations.RemoveField(
            model_name='templateblueprint',
            name='pod_type',
        ),
        migrations.RemoveField(
            model_name='templateblueprint',
            name='printing_schema',
        ),
        migrations.RemoveField(
            model_name='templateblueprint',
            name='printing_type',
        ),
        migrations.RemoveField(
            model_name='templateblueprint',
            name='production_mode',
        ),
        migrations.RemoveField(
            model_name='templateblueprint',
            name='required_color_count',
        ),
        migrations.RemoveField(
            model_name='templateblueprint',
            name='requires_engineering',
        ),
        migrations.RemoveField(
            model_name='templateprocesssteprollspec',
            name='fixed_thickness_micron',
        ),
        migrations.RemoveField(
            model_name='templateprocesssteprollspec',
            name='fixed_width_mm',
        ),
        migrations.RemoveField(
            model_name='templateprocesssteprollspec',
            name='output_grade',
        ),
        migrations.RemoveField(
            model_name='templateprocesssteprollspec',
            name='output_variant',
        ),
        migrations.AddField(
            model_name='templateblueprint',
            name='allowed_film_families',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='templateblueprint',
            name='allowed_film_variants',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
