# Generated by Codex on 2026-02-20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("templates", "0015_remove_templateblueprint_addons_schema_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="templateblueprint",
            name="artwork",
        ),
        migrations.RemoveField(
            model_name="templateblueprint",
            name="allowed_film_families",
        ),
        migrations.RemoveField(
            model_name="templateblueprint",
            name="allowed_film_variants",
        ),
    ]

