# Generated by Django 5.2.10 on 2026-03-02 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0021_templateprocessstepmaterial_formula_basis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templateprocessstepmaterial',
            name='consumption_basis',
            field=models.CharField(choices=[('SNAPSHOT_GSM', 'Snapshot GSM'), ('FIXED_KG', 'Fixed KG'), ('FIXED_PCS', 'Fixed PCS'), ('CATEGORY_FORMULA', 'Category Formula'), ('INVALID_LEGACY', 'Invalid Legacy Mapping')], default='FIXED_KG', max_length=20),
        ),
    ]
