# Generated by Django 5.2.10 on 2026-03-04 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0023_templateprocessstepmaterial_pod_formula_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templateprocessstepmaterial',
            name='formula_driver',
            field=models.CharField(choices=[('NONE', 'None'), ('ADDON_MASTER_WEIGHT_MODE', 'Addon Master Weight Mode'), ('POD_MASTER_PROFILE', 'POD Master Profile')], default='NONE', help_text='Formula driver for CATEGORY_FORMULA basis.', max_length=40),
        ),
    ]
