# Generated by Django 5.2.10 on 2026-03-06 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0024_alter_templateprocessstepmaterial_formula_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='templateblueprint',
            name='default_stock_strategy',
            field=models.CharField(choices=[('FINAL_STOCK', 'Final Stock'), ('INTERMEDIATE_POOL', 'Intermediate Pool'), ('PACKAGING_STOCK', 'Packaging Stock')], default='FINAL_STOCK', help_text='Default planner consumption strategy for stock orders cloned or created from this template.', max_length=30),
        ),
    ]
