# Generated by Django 5.2.10 on 2026-03-14 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0025_templateblueprint_default_stock_strategy'),
    ]

    operations = [
        migrations.AddField(
            model_name='templateblueprint',
            name='pouch_style',
            field=models.CharField(blank=True, choices=[('THREE_SIDE_SEAL', 'Three Side Seal'), ('PILLOW', 'Pillow'), ('STAND_UP', 'Stand Up'), ('SIDE_GUSSET', 'Side Gusset'), ('QUAD_SEAL', 'Quad Seal'), ('FLAT_BOTTOM', 'Flat Bottom'), ('SPOUT', 'Spout'), ('SHAPED', 'Shaped')], default='', help_text='Controlled pouch taxonomy used for validation, repeat-order safety, and reporting.', max_length=32),
        ),
    ]
