# Generated by Django 5.2.10 on 2026-03-14 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0010_commercialfamily_inventorymaterial_commercial_family'),
        ('templates', '0026_templateblueprint_pouch_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='templateblueprint',
            name='commercial_family',
            field=models.ForeignKey(blank=True, help_text='Controlled business-facing family alias used for naming, stock grouping, and reporting.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates', to='materials.commercialfamily'),
        ),
    ]
