# Generated by Django 5.2.12 on 2026-03-27 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costing', '0003_costabsorptiongroup_jobcost_actual_cost_coverage_pct_and_more'),
        ('templates', '0028_alter_templateblueprint_pouch_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='templateprocessstep',
            name='cost_absorption_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='template_steps', to='costing.costabsorptiongroup'),
        ),
    ]
