# Generated by Codex on 2026-04-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0029_templateprocessstep_cost_absorption_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='templateprocesssteprollspec',
            name='active_min_layer_count',
            field=models.PositiveIntegerField(default=0, help_text='Minimum SKU/order layer count needed before this step is active; zero means infer.'),
        ),
        migrations.AddField(
            model_name='templateprocesssteprollspec',
            name='adhesive_split_pct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='templateprocesssteprollspec',
            name='combine_mode',
            field=models.CharField(choices=[('STRICT_ROLL_COUNT', 'Strict Roll Count'), ('LANE_GROUPS', 'Lane Groups')], default='STRICT_ROLL_COUNT', help_text='For lamination-style combine steps, LANE_GROUPS means each lane can contain many physical rolls.', max_length=24),
        ),
        migrations.AddField(
            model_name='templateprocesssteprollspec',
            name='input_lane_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='templateprocesssteprollspec',
            name='lamination_pass_index',
            field=models.PositiveIntegerField(default=0, help_text='1-based pass number for lane lamination; zero means infer from route order.'),
        ),
        migrations.AddField(
            model_name='templateprocesssteprollspec',
            name='lane_schema',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='templateprocesssteprollspec',
            name='solvent_split_pct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
