# Generated by Django 5.2.13 on 2026-05-01 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0030_lane_based_roll_spec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templateprocesssteprollspec',
            name='operator_entry_mode',
            field=models.CharField(choices=[('PROCESS_DEFAULT', 'Process Default'), ('ROLL_SINGLE', 'Single Roll Output'), ('ROLL_MULTI', 'Multiple Roll Outputs'), ('GRID_SPLIT', 'Grid Split'), ('DISCRETE_ONLY', 'Discrete Only'), ('KG_ONLY', 'KG Only Bulk Output'), ('KG_AND_PCS', 'KG + PCS Bulk Output')], default='PROCESS_DEFAULT', help_text='Operator UI entry shape. Refines the process contract; does not override process input/output behavior.', max_length=20),
        ),
    ]
