# Generated by Codex on 2026-06-16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("factory", "0026_process_stock_form_capabilities"),
        ("templates", "0031_roll_to_bulk_output_capture_modes"),
    ]

    operations = [
        migrations.AddField(
            model_name="templateprocessstep",
            name="allowed_work_center_ids",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Operational dispatch allow-list for this route step. Empty means all capable work centers are allowed.",
            ),
        ),
        migrations.AddField(
            model_name="templateprocessstep",
            name="default_work_center",
            field=models.ForeignKey(
                blank=True,
                help_text="Preferred work center for this template step when more than one capable center exists.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="default_template_route_steps",
                to="factory.workcenter",
            ),
        ),
        migrations.AddField(
            model_name="templateprocessstep",
            name="dispatch_notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="templateprocessstep",
            name="dispatch_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="templateprocessstep",
            name="work_center_selection_policy",
            field=models.CharField(
                choices=[
                    ("AUTO_IF_SINGLE", "Auto assign when only one work center is valid"),
                    ("AUTO_DEFAULT", "Use the configured default work center"),
                    ("PLANNER_REQUIRED", "Planner must choose before release"),
                ],
                default="AUTO_IF_SINGLE",
                help_text="How production release resolves this step when multiple work centers are capable.",
                max_length=24,
            ),
        ),
    ]
