# Generated by Django 5.2.10 on 2026-03-05 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platformops', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='backuprecord',
            new_name='platformops_status_65fcf4_idx',
            old_name='platformops__status_d6b1c4_idx',
        ),
        migrations.RenameIndex(
            model_name='backuprecord',
            new_name='platformops_kind_5f68e7_idx',
            old_name='platformops__kind_c5ca1f_idx',
        ),
        migrations.RenameIndex(
            model_name='operationalalert',
            new_name='platformops_resolve_a082a3_idx',
            old_name='platformops__resolve_eb5f34_idx',
        ),
        migrations.RenameIndex(
            model_name='restoredrillrecord',
            new_name='platformops_status_882e6c_idx',
            old_name='platformops__status_53cb54_idx',
        ),
    ]
