# Generated by Django 6.0.1 on 2026-01-28 19:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('factory', '0005_process_input_form_process_output_form'),
        ('materials', '0004_alter_inventorymaterial_category'),
        ('production', '0022_alter_plannedstockorder_plant'),
        ('sales', '0007_customer_salesorder_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('material_cost', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('process_cost', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('total_cost', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('cost_per_kg', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('cost_per_piece', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('calculation_log', models.JSONField(default=dict, help_text='Breakdown of how cost was calculated')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='costing', to='production.productionjob')),
            ],
            options={
                'db_table': 'costing_job_costs',
            },
        ),
        migrations.CreateModel(
            name='MaterialCostSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('avg_rate_per_kg', models.DecimalField(decimal_places=4, max_digits=15)),
                ('uom', models.CharField(default='KG', max_length=10)),
                ('effective_date', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_snapshots', to='materials.inventorymaterial')),
            ],
            options={
                'db_table': 'costing_material_snapshots',
                'ordering': ['-effective_date'],
            },
        ),
        migrations.CreateModel(
            name='OrderCost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('material_cost', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('conversion_cost', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('total_cost', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('selling_price', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('margin_value', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('margin_percent', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('is_frozen', models.BooleanField(default=False, help_text='True if cost is locked for historical reference')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sales_order_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='costing', to='sales.salesorderitem')),
            ],
            options={
                'db_table': 'costing_order_costs',
            },
        ),
        migrations.CreateModel(
            name='ProcessCostRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cost_per_hour', models.DecimalField(decimal_places=2, help_text='Total cost per hour', max_digits=15)),
                ('power_cost_per_hour', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('labor_cost_per_hour', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('overhead_cost_per_hour', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_rates', to='factory.machine')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_rates', to='factory.process')),
            ],
            options={
                'db_table': 'costing_process_rates',
                'unique_together': {('process', 'machine')},
            },
        ),
    ]
