# Generated by Django 5.2.10 on 2026-02-27 09:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyOverhead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('electricity_cost', models.DecimalField(decimal_places=2, default=0, help_text='Total electricity bill for the month', max_digits=15)),
                ('labor_cost', models.DecimalField(decimal_places=2, default=0, help_text='Total labor cost (salary, wages) for the month', max_digits=15)),
                ('other_overheads', models.DecimalField(decimal_places=2, default=0, help_text='Rent, admin, depreciation, etc.', max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'costing_monthly_overheads',
                'unique_together': {('year', 'month')},
            },
        ),
    ]
