# Generated by Django 5.2.12 on 2026-03-27 21:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costing', '0002_monthlyoverhead'),
        ('factory', '0021_plant_include_in_official_reports'),
        ('production', '0046_plannedbulkstockorder_and_planner_stock_class'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CostAbsorptionGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=60, unique=True)),
                ('label', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('default_intensity_factor', models.DecimalField(decimal_places=4, default=1, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'costing_absorption_groups',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='jobcost',
            name='actual_cost_coverage_pct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='jobcost',
            name='conversion_cost_actual',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='jobcost',
            name='costing_mode',
            field=models.CharField(default='ESTIMATED', max_length=20),
        ),
        migrations.AddField(
            model_name='jobcost',
            name='coverage_flags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='jobcost',
            name='material_cost_actual',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='jobcost',
            name='overhead_cost_absorbed',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='jobcost',
            name='plant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='job_costs', to='factory.plant'),
        ),
        migrations.AddField(
            model_name='jobcost',
            name='runtime_minutes_productive',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='ordercost',
            name='absorbed_margin',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='ordercost',
            name='absorbed_margin_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='ordercost',
            name='actual_cost_coverage_pct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='ordercost',
            name='contribution_margin',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='ordercost',
            name='contribution_margin_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='ordercost',
            name='conversion_cost_actual',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='ordercost',
            name='costing_mode',
            field=models.CharField(default='ESTIMATED', max_length=20),
        ),
        migrations.AddField(
            model_name='ordercost',
            name='coverage_flags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='ordercost',
            name='material_cost_actual',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='ordercost',
            name='overhead_cost_absorbed',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='jobcost',
            name='cost_absorption_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='job_costs', to='costing.costabsorptiongroup'),
        ),
        migrations.CreateModel(
            name='JobRuntimeSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('close_reason', models.CharField(blank=True, choices=[('PAUSE', 'Paused'), ('COMPLETE', 'Completed'), ('CANCEL', 'Cancelled'), ('MANUAL', 'Manual')], default='', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cost_absorption_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='runtime_sessions', to='costing.costabsorptiongroup')),
                ('ended_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ended_runtime_sessions', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runtime_sessions', to='production.productionjob')),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='runtime_sessions', to='factory.machine')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runtime_sessions', to='factory.plant')),
                ('process', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='runtime_sessions', to='factory.process')),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='started_runtime_sessions', to=settings.AUTH_USER_MODEL)),
                ('work_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='runtime_sessions', to='factory.workcenter')),
            ],
            options={
                'db_table': 'costing_job_runtime_sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='PlantCostPoolMonth',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('entry_mode', models.CharField(choices=[('DIRECT', 'Direct Entry'), ('ALLOCATED', 'Top-down Allocation')], default='DIRECT', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('REVIEWED', 'Reviewed'), ('LOCKED', 'Locked')], default='DRAFT', max_length=20)),
                ('plant_total_electricity', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('plant_total_labor', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('plant_total_overhead', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('plant_total_maintenance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('plant_total_service_burden', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_pool_months', to='factory.plant')),
            ],
            options={
                'db_table': 'costing_plant_cost_pool_months',
                'ordering': ['-year', '-month', 'plant__code'],
                'unique_together': {('plant', 'year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='PlantCostPoolLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_mode', models.CharField(choices=[('DIRECT', 'Direct Entry'), ('ALLOCATED', 'Allocated')], default='DIRECT', max_length=20)),
                ('allocation_percent', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('electricity_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('labor_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('overhead_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('maintenance_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('service_burden_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cost_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pool_lines', to='costing.costabsorptiongroup')),
                ('month_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='costing.plantcostpoolmonth')),
            ],
            options={
                'db_table': 'costing_plant_cost_pool_lines',
                'ordering': ['month_record__year', 'month_record__month', 'cost_group__code'],
                'unique_together': {('month_record', 'cost_group')},
            },
        ),
    ]
