# Generated by Django 6.0.1 on 2026-01-22 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0003_process_category_process_input_mode_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='machine',
        ),
        migrations.AddField(
            model_name='user',
            name='machines',
            field=models.ManyToManyField(blank=True, related_name='assigned_users', to='factory.machine'),
        ),
    ]
