# Generated by Django 6.0.1 on 2026-01-22 15:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0003_process_category_process_input_mode_and_more'),
        ('users', '0002_remove_user_machine_user_machines'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='role_code',
            new_name='code',
        ),
        migrations.RemoveField(
            model_name='role',
            name='can_create_sales_orders',
        ),
        migrations.RemoveField(
            model_name='role',
            name='can_execute_jobs',
        ),
        migrations.RemoveField(
            model_name='role',
            name='can_manage_factory',
        ),
        migrations.RemoveField(
            model_name='role',
            name='can_manage_inventory',
        ),
        migrations.RemoveField(
            model_name='role',
            name='can_manage_production',
        ),
        migrations.RemoveField(
            model_name='role',
            name='can_manage_tooling',
        ),
        migrations.RemoveField(
            model_name='role',
            name='can_manage_users',
        ),
        migrations.RemoveField(
            model_name='user',
            name='machines',
        ),
        migrations.RemoveField(
            model_name='user',
            name='plant',
        ),
        migrations.RemoveField(
            model_name='user',
            name='work_center',
        ),
        migrations.AddField(
            model_name='role',
            name='default_permissions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='user',
            name='extra_permissions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='user',
            name='is_owner',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='MachineAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignees', to='factory.machine')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_machines', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users_machine_assignments',
                'unique_together': {('user', 'machine')},
            },
        ),
        migrations.CreateModel(
            name='WorkCenterAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_work_centers', to=settings.AUTH_USER_MODEL)),
                ('work_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignees', to='factory.workcenter')),
            ],
            options={
                'db_table': 'users_wc_assignments',
                'unique_together': {('user', 'work_center')},
            },
        ),
    ]
