# Generated by Django 5.2.10 on 2026-02-01 20:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_role_code_role_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_role', models.CharField(blank=True, help_text='Target role code (e.g., DISPATCH, PLANNER)', max_length=50)),
                ('type', models.CharField(choices=[('FG_READY', 'Finished Goods Ready'), ('CHALLAN_CREATED', 'Challan Created'), ('DISPATCH_READY', 'Ready for Dispatch'), ('LOW_STOCK', 'Low Stock Alert'), ('SCRAP_HIGH', 'High Scrap Rate'), ('DELAYED_JOB', 'Delayed Production Job'), ('JOB_COMPLETE', 'Job Completed'), ('ORDER_CREATED', 'Sales Order Created'), ('SYSTEM', 'System Alert')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NORMAL', max_length=10)),
                ('related_object_type', models.CharField(blank=True, help_text='e.g., SalesOrder, ProductionJob', max_length=50)),
                ('related_object_id', models.UUIDField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users_notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='users_notif_user_id_b46b2b_idx'), models.Index(fields=['target_role', 'is_read'], name='users_notif_target__2d7178_idx'), models.Index(fields=['created_at'], name='users_notif_created_09dbf8_idx')],
            },
        ),
    ]
