# Generated by Django 5.2.10 on 2026-03-05 07:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_notification_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationDeliveryAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('IN_APP', 'In-App'), ('EMAIL', 'Email')], max_length=20)),
                ('recipient', models.CharField(blank=True, max_length=255)),
                ('provider_message_id', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('attempt_no', models.PositiveIntegerField(default=1)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, max_length=160)),
                ('error_text', models.TextField(blank=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users_notification_delivery_attempts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_key', models.CharField(max_length=100, unique=True)),
                ('target_roles', models.JSONField(blank=True, default=list)),
                ('channels', models.JSONField(blank=True, default=list, help_text='IN_APP/EMAIL')),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NORMAL', max_length=10)),
                ('active', models.BooleanField(default=True)),
                ('escalation_minutes', models.PositiveIntegerField(default=0)),
                ('email_subject_template', models.CharField(blank=True, max_length=255)),
                ('email_body_template', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'users_notification_rules',
                'ordering': ['event_key'],
            },
        ),
        migrations.CreateModel(
            name='PermissionAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('DENIED', 'Denied'), ('ROLE_OVERRIDE', 'Role Override'), ('ROLE_CHANGED', 'Role Changed'), ('SIGNOFF_UPDATED', 'Signoff Updated')], max_length=40)),
                ('method', models.CharField(blank=True, max_length=16)),
                ('path', models.CharField(blank=True, max_length=255)),
                ('required_permission', models.CharField(blank=True, max_length=100)),
                ('effective_role', models.CharField(blank=True, max_length=50)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users_permission_audit_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoleVisibilitySignoff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role_code', models.CharField(max_length=50)),
                ('module_key', models.CharField(max_length=80)),
                ('action_key', models.CharField(max_length=80)),
                ('approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'users_role_visibility_signoff',
                'ordering': ['role_code', 'module_key', 'action_key'],
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='channels',
            field=models.JSONField(blank=True, default=list, help_text='Channels requested for delivery'),
        ),
        migrations.AddField(
            model_name='notification',
            name='delivery_state',
            field=models.JSONField(blank=True, default=dict, help_text='Delivery status by channel'),
        ),
        migrations.AddField(
            model_name='notification',
            name='event_key',
            field=models.CharField(blank=True, help_text='Canonical event key for routing', max_length=100),
        ),
        migrations.AddField(
            model_name='notification',
            name='first_delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['event_key', 'created_at'], name='users_notif_event_k_9c3f91_idx'),
        ),
        migrations.AddField(
            model_name='notificationdeliveryattempt',
            name='notification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_attempts', to='users.notification'),
        ),
        migrations.AddField(
            model_name='permissionauditlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permission_audits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rolevisibilitysignoff',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_signoffs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='notificationdeliveryattempt',
            index=models.Index(fields=['status', 'created_at'], name='users_notif_status_12cf7f_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationdeliveryattempt',
            index=models.Index(fields=['channel', 'status'], name='users_notif_channel_ef3b9f_idx'),
        ),
        migrations.AddIndex(
            model_name='permissionauditlog',
            index=models.Index(fields=['action', 'created_at'], name='users_permi_action_8b32cf_idx'),
        ),
        migrations.AddIndex(
            model_name='permissionauditlog',
            index=models.Index(fields=['user', 'created_at'], name='users_permi_user_id_dc8623_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rolevisibilitysignoff',
            unique_together={('role_code', 'module_key', 'action_key')},
        ),
    ]
