# Generated by Django 5.2.10 on 2026-03-05 09:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_notificationdeliveryattempt_notificationrule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='permissionauditlog',
            name='action',
            field=models.CharField(choices=[('DENIED', 'Denied'), ('ROLE_OVERRIDE', 'Role Override'), ('ROLE_CHANGED', 'Role Changed'), ('SIGNOFF_UPDATED', 'Signoff Updated'), ('PASSWORD_CHANGED', 'Password Changed'), ('PROFILE_CHANGE_REQUESTED', 'Profile Change Requested'), ('PROFILE_CHANGE_REVIEWED', 'Profile Change Reviewed'), ('USER_LOGOUT', 'User Logout')], max_length=40),
        ),
        migrations.CreateModel(
            name='UserProfileChangeRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requested_changes', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('review_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_change_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_change_reviews', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_change_targets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users_profile_change_requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='users_profi_status_d5b9b8_idx'), models.Index(fields=['target_user', 'created_at'], name='users_profi_target__9f48db_idx')],
            },
        ),
    ]
