# Generated by Django 5.2.13 on 2026-04-09 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_avatar_url_user_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissionauditlog',
            name='action',
            field=models.CharField(choices=[('DENIED', 'Denied'), ('ROLE_OVERRIDE', 'Role Override'), ('ROLE_CHANGED', 'Role Changed'), ('SIGNOFF_UPDATED', 'Signoff Updated'), ('PASSWORD_CHANGED', 'Password Changed'), ('PROFILE_CHANGE_REQUESTED', 'Profile Change Requested'), ('PROFILE_CHANGE_REVIEWED', 'Profile Change Reviewed'), ('USER_LOGIN', 'User Login'), ('USER_LOGOUT', 'User Logout')], max_length=40),
        ),
    ]
