# Generated by Codex on 2026-04-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_permissionauditlog_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="permissionauditlog",
            name="action",
            field=models.CharField(choices=[("DENIED", "Denied"), ("ROLE_OVERRIDE", "Role Override"), ("ROLE_CHANGED", "Role Changed"), ("SIGNOFF_UPDATED", "Signoff Updated"), ("PASSWORD_CHANGED", "Password Changed"), ("PROFILE_CHANGE_REQUESTED", "Profile Change Requested"), ("PROFILE_CHANGE_REVIEWED", "Profile Change Reviewed"), ("USER_LOGIN", "User Login"), ("USER_LOGOUT", "User Logout"), ("MASTER_DATA_CHANGED", "Master Data Changed")], max_length=40),
        ),
    ]
