# Generated by Django 6.0.4 on 2026-04-21 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_permissionauditlog_master_data_changed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissionauditlog',
            name='action',
            field=models.CharField(choices=[('DENIED', 'Denied'), ('ROLE_OVERRIDE', 'Role Override'), ('ROLE_CHANGED', 'Role Changed'), ('SIGNOFF_UPDATED', 'Signoff Updated'), ('PASSWORD_CHANGED', 'Password Changed'), ('PROFILE_CHANGE_REQUESTED', 'Profile Change Requested'), ('PROFILE_CHANGE_REVIEWED', 'Profile Change Reviewed'), ('USER_LOGIN', 'User Login'), ('USER_LOGOUT', 'User Logout'), ('MASTER_DATA_CHANGED', 'Master Data Changed'), ('SALES_ORDER_CHANGED', 'Sales Order Changed')], max_length=40),
        ),
    ]
