# Generated by Django 6.0.4 on 2026-05-27 10:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_permissionauditlog_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('legal_name', models.CharField(default='TOTAL POLY PRINT PVT. LTD.', max_length=200)),
                ('trading_name', models.CharField(blank=True, default='', max_length=200)),
                ('tagline', models.CharField(default='Leading manufacturer of Flexible Packaging', max_length=300)),
                ('address_line1', models.CharField(default='Survey No. 261/3-A, Opp. Dabhel Cricket Ground', max_length=200)),
                ('address_line2', models.CharField(default='Dabhel', max_length=200)),
                ('city', models.CharField(default='Daman', max_length=80)),
                ('state', models.CharField(default='Daman (U.T.)', max_length=80)),
                ('country', models.CharField(default='India', max_length=80)),
                ('pincode', models.CharField(default='396210', max_length=12)),
                ('phone_primary', models.CharField(default='+91 72111 35002', max_length=40)),
                ('phone_secondary', models.CharField(blank=True, default='+91 98985 85118', max_length=40)),
                ('email', models.EmailField(default='info@totalpolyprint.com', max_length=254)),
                ('website', models.URLField(default='https://www.totalpolyprint.com')),
                ('gstin', models.CharField(blank=True, default='', max_length=20)),
                ('pan', models.CharField(blank=True, default='', max_length=12)),
                ('cin', models.CharField(blank=True, default='', max_length=24)),
                ('udyam', models.CharField(blank=True, default='', max_length=24)),
                ('iec_code', models.CharField(blank=True, default='', max_length=20)),
                ('bank_name', models.CharField(blank=True, default='', max_length=100)),
                ('bank_branch', models.CharField(blank=True, default='', max_length=100)),
                ('bank_account_no', models.CharField(blank=True, default='', max_length=40)),
                ('bank_ifsc', models.CharField(blank=True, default='', max_length=20)),
                ('bank_upi', models.CharField(blank=True, default='', max_length=80)),
                ('default_payment_terms', models.CharField(default='Net 45 days from invoice date', max_length=120)),
                ('default_jurisdiction', models.CharField(default='Daman, India', max_length=100)),
                ('quote_validity_days', models.PositiveSmallIntegerField(default=12)),
                ('quote_terms_text', models.TextField(blank=True, default='')),
                ('authorised_signatory_name', models.CharField(default='', max_length=120)),
                ('authorised_signatory_role', models.CharField(default='Authorised Signatory', max_length=120)),
                ('logo_path', models.CharField(default='brand/tpp-logo-pdf.svg', max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Company Profile',
                'verbose_name_plural': 'Company Profile',
                'db_table': 'users_company_profile',
            },
        ),
    ]
