# Generated by Django 6.0.4 on 2026-05-28 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_companyprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='shift_boundaries',
            field=models.JSONField(blank=True, default=dict, help_text='Mapping of shift_code -> [start_HHMM, end_HHMM] in local time. Default: A=06-14, B=14-22, C=22-06.'),
        ),
    ]
