# Generated by Django 6.0.8 on 2026-10-08 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0028_enable_print_process_capabilities'),
        ('users', '0012_watchman_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='deep_link',
            field=models.CharField(blank=True, default='', db_default='', max_length=255),
        ),
        migrations.AddField(
            model_name='notification',
            name='plant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_notifications', to='factory.plant'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(condition=models.Q(('event_key', 'gate.inward_bill_uploaded')), fields=('user', 'event_key', 'related_object_id'), name='users_unique_inward_bill_notice'),
        ),
    ]
