# Generated by Django 6.0.1 on 2026-01-19 13:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('factory', '0001_initial'),
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryChallan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('IN_TRANSIT', 'In Transit'), ('RECEIVED', 'Received')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_plant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_challans', to='factory.plant')),
                ('to_plant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_challans', to='factory.plant')),
            ],
            options={
                'db_table': 'inventory_delivery_challans',
            },
        ),
        migrations.CreateModel(
            name='InventoryLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(default='', max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('RM', 'Raw Material'), ('WIP', 'Work In Progress'), ('FG', 'Finished Good'), ('TOOLING', 'Tooling'), ('SCRAP', 'Scrap'), ('IN_TRANSIT', 'In Transit')], max_length=20)),
                ('is_virtual', models.BooleanField(default=False)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='factory.plant')),
            ],
            options={
                'db_table': 'inventory_locations',
            },
        ),
        migrations.CreateModel(
            name='InventoryRoll',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label_id', models.CharField(help_text='Human Readable Barcode ID', max_length=50, unique=True)),
                ('batch_no', models.CharField(max_length=100)),
                ('width_mm', models.DecimalField(decimal_places=2, max_digits=10)),
                ('length_m', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('weight_kg', models.DecimalField(decimal_places=3, default=0, help_text='Net weight in KG', max_digits=10)),
                ('status', models.CharField(choices=[('WIP', 'Work In Progress'), ('FG', 'Finished Good'), ('CONSUMED', 'Consumed'), ('SCRAP', 'Scrapped'), ('QUARANTINE', 'Quarantine')], default='WIP', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.inventorylocation')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materials.inventorymaterial')),
                ('parent_roll', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='inventory.inventoryroll')),
            ],
            options={
                'db_table': 'inventory_rolls',
            },
        ),
        migrations.CreateModel(
            name='InventoryLedger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('GRN', 'Goods Receipt'), ('ISSUE', 'Issue to Production'), ('PROD_OUT', 'Production Output'), ('TRANSFER', 'Transfer'), ('SCRAP', 'Scrap')], max_length=20)),
                ('qty_change', models.DecimalField(decimal_places=4, max_digits=15)),
                ('reference', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materials.inventorymaterial')),
                ('dest_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='in_tx', to='inventory.inventorylocation')),
                ('source_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='out_tx', to='inventory.inventorylocation')),
                ('roll', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.inventoryroll')),
            ],
            options={
                'db_table': 'inventory_ledger',
            },
        ),
        migrations.CreateModel(
            name='InventoryStock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('uom', models.CharField(default='KG', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.inventorylocation')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materials.inventorymaterial')),
            ],
            options={
                'db_table': 'inventory_stock',
                'unique_together': {('material', 'location')},
            },
        ),
    ]
