# Generated by Django 6.0.1 on 2026-01-19 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inventorylocation',
            unique_together={('plant', 'code', 'name')},
        ),
        migrations.AddField(
            model_name='inventorylocation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='inventorylocation',
            name='is_system',
            field=models.BooleanField(default=False, help_text='System locations cannot be deleted'),
        ),
        migrations.AlterField(
            model_name='inventorylocation',
            name='code',
            field=models.CharField(choices=[('RM', 'Raw Material'), ('WIP', 'Work In Progress'), ('FG', 'Finished Good'), ('TOOLING', 'Tooling'), ('SCRAP', 'Scrap'), ('IN_TRANSIT', 'In Transit'), ('CUSTOM', 'Custom Location')], default='CUSTOM', max_length=50),
        ),
        migrations.AlterField(
            model_name='inventorylocation',
            name='type',
            field=models.CharField(choices=[('STORAGE', 'Storage'), ('WIP', 'Work In Progress Area'), ('TOOLING', 'Tooling Hub'), ('TRANSIT', 'Transit Zone')], default='STORAGE', max_length=20),
        ),
        migrations.RemoveField(
            model_name='inventorylocation',
            name='is_virtual',
        ),
    ]
