# Generated by Django 6.0.1 on 2026-01-20 09:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0003_process_category_process_input_mode_and_more'),
        ('inventory', '0002_alter_inventorylocation_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryledger',
            name='transaction_type',
            field=models.CharField(choices=[('GRN', 'Goods Receipt'), ('PRODUCTION_ISSUE', 'Issue to Production'), ('PRODUCTION_RECEIPT', 'Production Output'), ('JOBWORK_OUT', 'Sent to Job Work'), ('JOBWORK_IN', 'Received from Job Work'), ('TRANSFER', 'Internal Transfer'), ('MANUAL_ADJUST', 'Manual Adjustment'), ('SCRAP', 'Scrap')], max_length=20),
        ),
        migrations.AlterField(
            model_name='inventorylocation',
            name='code',
            field=models.CharField(choices=[('RM', 'Raw Material'), ('WIP', 'Work In Progress'), ('FG', 'Finished Good'), ('TOOLING', 'Tooling'), ('SCRAP', 'Scrap'), ('IN_TRANSIT', 'In Transit'), ('JOBWORK_OUT', 'Job Work Out'), ('CUSTOM', 'Custom Location')], default='CUSTOM', max_length=50),
        ),
        migrations.AlterField(
            model_name='inventoryroll',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('SENT_JOBWORK', 'Sent to Job Work'), ('CONSUMED', 'Consumed'), ('SCRAPPED', 'Scrapped'), ('QUARANTINE', 'Quarantine')], default='AVAILABLE', max_length=20),
        ),
        migrations.CreateModel(
            name='JobWorkOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vendor_name', models.CharField(max_length=255)),
                ('expected_return_type', models.CharField(choices=[('RM', 'Raw Material'), ('WIP', 'Work In Progress'), ('FG', 'Finished Goods')], default='WIP', max_length=10)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent'), ('PARTIAL', 'Partially Received'), ('CLOSED', 'Closed')], default='DRAFT', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_work_orders', to='factory.plant')),
            ],
            options={
                'db_table': 'inventory_job_work_orders',
            },
        ),
    ]
