# Generated by Django 6.0.1 on 2026-01-20 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_inventoryledger_transaction_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobworkorder',
            name='sent_material_type',
            field=models.CharField(choices=[('RM', 'Raw Material'), ('WIP', 'Work In Progress'), ('FG', 'Finished Goods')], default='RM', max_length=10),
        ),
        migrations.AlterField(
            model_name='inventoryledger',
            name='transaction_type',
            field=models.CharField(choices=[('GRN', 'Goods Receipt'), ('PRODUCTION_ISSUE', 'Issue to Production'), ('PRODUCTION_RECEIPT', 'Production Output'), ('JOBWORK_OUT', 'Sent to Job Work'), ('JOBWORK_IN', 'Received from Job Work'), ('INTERPLANT_OUT', 'Inter-Plant Issue'), ('INTERPLANT_IN', 'Inter-Plant Receipt'), ('MANUAL_ADJUST', 'Manual Adjustment'), ('SCRAP', 'Scrap')], max_length=20),
        ),
        migrations.AlterField(
            model_name='inventorylocation',
            name='code',
            field=models.CharField(choices=[('RM', 'Raw Material'), ('WIP', 'Work In Progress'), ('FG', 'Finished Good'), ('SCRAP', 'Scrap'), ('IN_TRANSIT', 'In Transit'), ('JOBWORK_OUT', 'Job Work Out'), ('QC', 'Quality Control'), ('DISPATCH', 'Dispatch Staging'), ('WAREHOUSE', 'Warehouse'), ('CUSTOM', 'Custom Location')], default='CUSTOM', max_length=50),
        ),
        migrations.AlterField(
            model_name='inventorylocation',
            name='type',
            field=models.CharField(choices=[('STORAGE', 'Storage'), ('WIP', 'Work In Progress Area'), ('QC', 'Quality Control'), ('DISPATCH', 'Dispatch Area'), ('TRANSIT', 'Transit Zone')], default='STORAGE', max_length=20),
        ),
        migrations.AlterField(
            model_name='inventoryroll',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('SENT_JOBWORK', 'Sent to Job Work'), ('CONSUMED', 'Consumed'), ('SCRAPPED', 'Scrapped')], default='AVAILABLE', max_length=20),
        ),
    ]
