# Generated by Django 6.0.1 on 2026-01-20 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_jobworkorder_sent_material_type_and_more'),
        ('production', '0002_productionjob_operator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventoryledger',
            old_name='reference',
            new_name='reference_note',
        ),
        migrations.AddField(
            model_name='inventoryledger',
            name='reference_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventoryledger',
            name='reference_type',
            field=models.CharField(blank=True, choices=[('GRN', 'Purchase Receipt'), ('PROD_JOB', 'Production Job'), ('JOB_WORK', 'Job Work Order'), ('INTER_PLANT', 'Delivery Challan'), ('ADJUST', 'Manual Adjustment')], max_length=20),
        ),
        migrations.AddField(
            model_name='jobworkorder',
            name='production_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_work_orders', to='production.productionjob'),
        ),
        migrations.AlterField(
            model_name='inventoryledger',
            name='transaction_type',
            field=models.CharField(choices=[('GRN_BULK', 'Bulk Goods Receipt'), ('GRN_ROLL', 'Roll Goods Receipt'), ('PRODUCTION_ISSUE', 'Issue to Production'), ('PRODUCTION_RECEIPT', 'Production Output'), ('JOBWORK_OUT', 'Sent to Job Work'), ('JOBWORK_IN', 'Received from Job Work'), ('INTER_PLANT_OUT', 'Inter-Plant Issue'), ('INTER_PLANT_IN', 'Inter-Plant Receipt'), ('MANUAL_ADJUST', 'Manual Adjustment'), ('SCRAP', 'Scrap')], max_length=20),
        ),
        migrations.AlterField(
            model_name='inventorylocation',
            name='code',
            field=models.CharField(choices=[('WIP', 'Work In Progress'), ('FG', 'Finished Goods'), ('SCRAP', 'Scrap'), ('JOBWORK_OUT', 'Job Work Out (Internal)'), ('IN_TRANSIT', 'In Transit'), ('WAREHOUSE', 'Warehouse'), ('QC', 'Quality Control'), ('DISPATCH', 'Dispatch Staging'), ('CUSTOM', 'Custom Storage')], default='CUSTOM', max_length=50),
        ),
        migrations.AlterField(
            model_name='inventorylocation',
            name='type',
            field=models.CharField(choices=[('WAREHOUSE', 'Warehouse'), ('QC', 'Quality Control'), ('WIP', 'Work In Progress Area'), ('FG', 'Finished Goods Area'), ('SCRAP', 'Scrap Area'), ('JOBWORK', 'Job Work Zone'), ('TRANSIT', 'Transit Zone'), ('DISPATCH', 'Dispatch Area')], default='STORAGE', max_length=20),
        ),
    ]
