# Generated by Django 6.0.1 on 2026-01-20 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_rename_reference_inventoryledger_reference_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorylocation',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='inventorylocation',
            name='type',
            field=models.CharField(choices=[('WAREHOUSE', 'Warehouse'), ('RM', 'Raw Materials'), ('QC', 'Quality Control'), ('WIP', 'Work In Progress Area'), ('FG', 'Finished Goods Area'), ('SCRAP', 'Scrap Area'), ('JOBWORK', 'Job Work Zone'), ('TRANSIT', 'Transit Zone'), ('DISPATCH', 'Dispatch Area')], default='WAREHOUSE', max_length=20),
        ),
    ]
