# Generated by Django 6.0.1 on 2026-01-22 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_inventorylocation_code_and_more'),
        ('production', '0005_alter_productionjob_job_state_downtimelog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryroll',
            name='is_fg',
            field=models.BooleanField(default=False, help_text='True if this roll is a Finished Good'),
        ),
        migrations.AddField(
            model_name='inventoryroll',
            name='production_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='output_rolls', to='production.productionjob'),
        ),
    ]
