# Generated by Django 6.0.1 on 2026-01-22 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_inventoryroll_is_fg_inventoryroll_production_job'),
        ('sales', '0006_remove_salesorder_plant'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryroll',
            name='sales_order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_rolls', to='sales.salesorderitem'),
        ),
    ]
