# Generated by Django 6.0.1 on 2026-01-22 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_inventoryroll_sales_order_item'),
        ('production', '0009_deliverychallanitem_sales_order_item_and_more'),
        ('sales', '0006_remove_salesorder_plant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryroll',
            name='production_job',
            field=models.ForeignKey(default='ed90e87b-c161-4e0b-a7bc-06d81b47871f', on_delete=django.db.models.deletion.PROTECT, related_name='output_rolls', to='production.productionjob'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventoryroll',
            name='sales_order_item',
            field=models.ForeignKey(default='3359e2b8-a1f1-4561-8c1a-0207c4f1043c', on_delete=django.db.models.deletion.PROTECT, related_name='inventory_rolls', to='sales.salesorderitem'),
            preserve_default=False,
        ),
    ]
