# Generated by Django 6.0.1 on 2026-01-22 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_alter_inventorylocation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorylocation',
            name='type',
            field=models.CharField(choices=[('WAREHOUSE', 'Warehouse'), ('RM', 'Raw Materials'), ('QC', 'Quality Control'), ('WIP', 'Work In Progress Area'), ('FG', 'Finished Goods Area'), ('SCRAP', 'Scrap Area'), ('JOBWORK', 'Job Work Zone'), ('TRANSIT', 'Transit Zone'), ('DISPATCH', 'Dispatch Area'), ('TOOLING', 'Tool Room')], default='WAREHOUSE', max_length=20),
        ),
    ]
