# Generated by Django 6.0.1 on 2026-01-24 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_alter_inventorylocation_type'),
        ('sales', '0007_customer_salesorder_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryroll',
            name='sales_order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_rolls', to='sales.salesorderitem'),
        ),
    ]
