# Generated by Django 5.2.10 on 2026-01-26 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_alter_inventoryroll_sales_order_item'),
        ('templates', '0004_templateblueprint_production_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryroll',
            name='current_step_index',
            field=models.IntegerField(default=0, help_text='Current routing step this roll has completed'),
        ),
        migrations.AddField(
            model_name='inventoryroll',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_rolls', to='templates.templateblueprint'),
        ),
    ]
