# Generated by Django 5.2.10 on 2026-01-28 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_inventoryroll_current_step_index_and_more'),
        ('materials', '0002_inventorymaterial_is_purchasable'),
    ]

    operations = [
        migrations.CreateModel(
            name='InkMaterial',
            fields=[
                ('inventorymaterial_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='materials.inventorymaterial')),
                ('base_type', models.CharField(choices=[('POLY', 'POLY'), ('PET', 'PET')], max_length=10)),
                ('color_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'inventory_ink_materials',
                'constraints': [models.UniqueConstraint(fields=('base_type', 'color_name'), name='unique_ink_per_base')],
            },
            bases=('materials.inventorymaterial',),
        ),
    ]
