# Generated by Django 5.2.10 on 2026-01-31 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_inkmaterial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryroll',
            name='thickness_micron',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Thickness in microns', max_digits=10),
        ),
    ]
