# Generated by Django 5.2.10 on 2026-01-31 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_inventoryroll_thickness_micron'),
        ('production', '0022_alter_plannedstockorder_plant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryroll',
            name='production_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='output_rolls', to='production.productionjob'),
        ),
    ]
