# Generated by Django 5.2.10 on 2026-01-31 11:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0008_process_physical_only_refactor'),
        ('inventory', '0017_alter_inventoryroll_production_job'),
        ('materials', '0004_alter_inventorymaterial_category'),
        ('production', '0022_alter_plannedstockorder_plant'),
        ('sales', '0007_customer_salesorder_customer'),
        ('templates', '0006_templateblueprint_pod_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RollMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(choices=[('GRN', 'Goods Receipt'), ('PRODUCTION', 'Production Issue'), ('WIP_TRANSFER', 'WIP Transfer'), ('FG_TRANSFER', 'FG Storage'), ('DISPATCH', 'Dispatch'), ('JOBWORK_OUT', 'Job Work Send'), ('JOBWORK_IN', 'Job Work Return'), ('SCRAP', 'Scrap Yard'), ('ADJUSTMENT', 'Manual Adjustment'), ('INTER_PLANT', 'Inter-Plant Transfer')], max_length=20)),
                ('reason_note', models.CharField(blank=True, max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'inventory_roll_movements',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='inventoryroll',
            name='created_by_job',
            field=models.ForeignKey(blank=True, help_text='Job that created this roll', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_rolls', to='production.productionjob'),
        ),
        migrations.AddField(
            model_name='inventoryroll',
            name='created_process',
            field=models.ForeignKey(blank=True, help_text='Process that created this roll', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_rolls', to='factory.process'),
        ),
        migrations.AddField(
            model_name='inventoryroll',
            name='grade',
            field=models.CharField(blank=True, help_text='Material grade classification', max_length=50),
        ),
        migrations.AddField(
            model_name='inventoryroll',
            name='meta_json',
            field=models.JSONField(blank=True, default=dict, help_text='Extensible metadata (e.g., quality notes, vendor info)'),
        ),
        migrations.AddField(
            model_name='inventoryroll',
            name='original_weight_kg',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Initial weight at creation (immutable)', max_digits=10),
        ),
        migrations.AddField(
            model_name='inventoryroll',
            name='stage_index',
            field=models.IntegerField(default=0, help_text='Current production stage (0=RM, 1=Extruded, 2=Printed, etc.)'),
        ),
        migrations.AlterField(
            model_name='inventoryroll',
            name='label_id',
            field=models.CharField(help_text='Human Readable Barcode ID (e.g., ROLL-20260131-00123)', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='inventoryroll',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('RESERVED', 'Reserved'), ('IN_PROCESS', 'In Process'), ('SENT_JOBWORK', 'Sent to Job Work'), ('CONSUMED', 'Consumed'), ('SCRAPPED', 'Scrapped')], default='AVAILABLE', max_length=20),
        ),
        migrations.AlterField(
            model_name='inventoryroll',
            name='weight_kg',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Current weight in KG', max_digits=10),
        ),
        migrations.CreateModel(
            name='RollConsumption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('consumed_kg', models.DecimalField(decimal_places=3, help_text='Total weight consumed from input roll', max_digits=10)),
                ('scrap_kg', models.DecimalField(decimal_places=3, default=0, help_text='Weight lost as scrap', max_digits=10)),
                ('balance_kg', models.DecimalField(decimal_places=3, default=0, help_text='Remaining weight returned as balance roll', max_digits=10)),
                ('output_kg', models.DecimalField(decimal_places=3, default=0, help_text='Weight produced as output', max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('balance_roll', models.ForeignKey(blank=True, help_text='Remaining balance roll', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consumptions_as_balance', to='inventory.inventoryroll')),
                ('input_roll', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumptions_as_input', to='inventory.inventoryroll')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='roll_consumptions', to='production.productionjob')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='roll_consumptions', to='factory.machine')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roll_consumptions', to=settings.AUTH_USER_MODEL)),
                ('output_roll', models.ForeignKey(blank=True, help_text='Output roll created from this consumption', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consumptions_as_output', to='inventory.inventoryroll')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='roll_consumptions', to='factory.process')),
                ('scrap_roll', models.ForeignKey(blank=True, help_text='Scrap roll if any', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consumptions_as_scrap', to='inventory.inventoryroll')),
            ],
            options={
                'db_table': 'inventory_roll_consumptions',
            },
        ),
        migrations.CreateModel(
            name='RollLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relation_type', models.CharField(choices=[('SPLIT', 'Split'), ('MERGE', 'Merge'), ('PROCESS_OUTPUT', 'Process Output')], max_length=20)),
                ('qty_used_kg', models.DecimalField(decimal_places=3, default=0, help_text='Amount from parent consumed to create child', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('child_roll', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parent_links', to='inventory.inventoryroll')),
                ('parent_roll', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='child_links', to='inventory.inventoryroll')),
            ],
            options={
                'db_table': 'inventory_roll_links',
            },
        ),
        migrations.AddField(
            model_name='inventoryroll',
            name='parent_rolls',
            field=models.ManyToManyField(related_name='child_rolls', through='inventory.RollLink', to='inventory.inventoryroll'),
        ),
        migrations.AddIndex(
            model_name='inventoryroll',
            index=models.Index(fields=['status'], name='inventory_r_status_e5d416_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryroll',
            index=models.Index(fields=['stage_index'], name='inventory_r_stage_i_5582ea_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryroll',
            index=models.Index(fields=['location'], name='inventory_r_locatio_ea4973_idx'),
        ),
        migrations.AddField(
            model_name='rollmovement',
            name='from_location',
            field=models.ForeignKey(blank=True, help_text='NULL for GRN (initial receipt)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='roll_movements_from', to='inventory.inventorylocation'),
        ),
        migrations.AddField(
            model_name='rollmovement',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roll_movements', to='production.productionjob'),
        ),
        migrations.AddField(
            model_name='rollmovement',
            name='moved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roll_movements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rollmovement',
            name='roll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.inventoryroll'),
        ),
        migrations.AddField(
            model_name='rollmovement',
            name='to_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='roll_movements_to', to='inventory.inventorylocation'),
        ),
        migrations.AddIndex(
            model_name='rollconsumption',
            index=models.Index(fields=['job'], name='inventory_r_job_id_c15761_idx'),
        ),
        migrations.AddIndex(
            model_name='rollconsumption',
            index=models.Index(fields=['input_roll'], name='inventory_r_input_r_5cd147_idx'),
        ),
        migrations.AddIndex(
            model_name='rollconsumption',
            index=models.Index(fields=['timestamp'], name='inventory_r_timesta_2e0b02_idx'),
        ),
        migrations.AddIndex(
            model_name='rolllink',
            index=models.Index(fields=['parent_roll'], name='inventory_r_parent__6437fc_idx'),
        ),
        migrations.AddIndex(
            model_name='rolllink',
            index=models.Index(fields=['child_roll'], name='inventory_r_child_r_5f9f6a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rolllink',
            unique_together={('parent_roll', 'child_roll')},
        ),
        migrations.AddIndex(
            model_name='rollmovement',
            index=models.Index(fields=['roll'], name='inventory_r_roll_id_e5df67_idx'),
        ),
        migrations.AddIndex(
            model_name='rollmovement',
            index=models.Index(fields=['timestamp'], name='inventory_r_timesta_3f6b71_idx'),
        ),
        migrations.AddIndex(
            model_name='rollmovement',
            index=models.Index(fields=['from_location'], name='inventory_r_from_lo_afadd0_idx'),
        ),
        migrations.AddIndex(
            model_name='rollmovement',
            index=models.Index(fields=['to_location'], name='inventory_r_to_loca_bae257_idx'),
        ),
    ]
