# Generated by Django 5.2.10 on 2026-02-01 07:08
# Phase 56: Add grade FK and plant FK to InventoryRoll

import django.db.models.deletion
import uuid
from django.db import migrations, models


def clear_grade_values(apps, schema_editor):
    """
    Clear existing grade CharField values before converting to FK.
    The grade was previously a CharField, now becoming a FK.
    """
    InventoryRoll = apps.get_model('inventory', 'InventoryRoll')
    InventoryRoll.objects.all().update(grade='')


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0008_process_physical_only_refactor'),
        ('inventory', '0018_phase54_roll_tracking'),
        ('materials', '0004_alter_inventorymaterial_category'),
        ('production', '0022_alter_plannedstockorder_plant'),
        ('recipes', '0001_initial'),
    ]

    operations = [
        # First, remove the old grade CharField
        migrations.RemoveField(
            model_name='inventoryroll',
            name='grade',
        ),
        # Add plant FK (nullable)
        migrations.AddField(
            model_name='inventoryroll',
            name='plant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_rolls', to='factory.plant'),
        ),
        # Add new grade FK (nullable)
        migrations.AddField(
            model_name='inventoryroll',
            name='grade',
            field=models.ForeignKey(blank=True, help_text='Recipe Grade (for extrusion tracking)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_rolls', to='recipes.recipegrade'),
        ),
        # Update batch_no field
        migrations.AlterField(
            model_name='inventoryroll',
            name='batch_no',
            field=models.CharField(blank=True, max_length=100),
        ),
        # Update material field with better help_text
        migrations.AlterField(
            model_name='inventoryroll',
            name='material',
            field=models.ForeignKey(blank=True, help_text='Film Variant (logical)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_rolls', to='materials.inventorymaterial'),
        ),
        # Create BulkTransaction model
        migrations.CreateModel(
            name='BulkTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('INWARD', 'Inward (GRN)'), ('CONSUME', 'Production Consumption'), ('TRANSFER', 'Location Transfer'), ('ADJUST', 'Manual Adjustment')], max_length=20)),
                ('qty_kg', models.DecimalField(decimal_places=4, max_digits=15)),
                ('avg_cost', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.productionjob')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bulk_transactions', to='inventory.inventorylocation')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bulk_transactions', to='materials.inventorymaterial')),
            ],
            options={
                'db_table': 'inventory_bulk_transactions',
                'ordering': ['-created_at'],
            },
        ),
        # Create InventoryBulk model
        migrations.CreateModel(
            name='InventoryBulk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qty_kg', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('avg_cost', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bulk_inventory', to='inventory.inventorylocation')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bulk_stock', to='materials.inventorymaterial')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_inventory', to='factory.plant')),
            ],
            options={
                'db_table': 'inventory_bulk',
                'unique_together': {('material', 'plant', 'location')},
            },
        ),
    ]
