# Generated by Django 5.2.10 on 2026-02-01 08:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0008_process_physical_only_refactor'),
        ('inventory', '0019_phase56_roll_grade_plant'),
        ('materials', '0004_alter_inventorymaterial_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('NEGATIVE_STOCK', 'Negative Stock'), ('LOW_STOCK', 'Low Stock'), ('ORPHAN_ROLL', 'Orphan Roll'), ('NO_PARENT', 'Missing Parent'), ('NO_CHILD', 'Missing Child'), ('STUCK_WIP', 'Stuck WIP'), ('COST_MISMATCH', 'Cost Mismatch'), ('WEIGHT_MISMATCH', 'Weight Mismatch'), ('TXN_MISMATCH', 'Transaction Mismatch')], max_length=20)),
                ('message', models.TextField()),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=10)),
                ('expected_value', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('actual_value', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='materials.inventorymaterial')),
                ('plant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_alerts', to='factory.plant')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL)),
                ('roll', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='inventory.inventoryroll')),
            ],
            options={
                'db_table': 'inventory_alerts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['type', 'resolved'], name='inventory_a_type_a76d1b_idx'), models.Index(fields=['severity', 'resolved'], name='inventory_a_severit_1cf2c2_idx'), models.Index(fields=['created_at'], name='inventory_a_created_db8814_idx')],
            },
        ),
        migrations.CreateModel(
            name='InventorySnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_bulk_kg', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('total_roll_kg', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('total_fg_kg', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('total_wip_kg', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('reserved_roll_kg', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('scrap_kg', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('bulk_sku_count', models.IntegerField(default=0)),
                ('roll_count', models.IntegerField(default=0)),
                ('fg_roll_count', models.IntegerField(default=0)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_snapshots', to='factory.plant')),
            ],
            options={
                'db_table': 'inventory_snapshots',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['plant', 'created_at'], name='inventory_s_plant_i_e19c1a_idx')],
            },
        ),
    ]
