# Generated by Django 5.2.10 on 2026-02-01 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_phase58_observability'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inventorystock',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='inventorystock',
            name='location',
        ),
        migrations.RemoveField(
            model_name='inventorystock',
            name='material',
        ),
        migrations.DeleteModel(
            name='InventoryLedger',
        ),
        migrations.DeleteModel(
            name='InventoryStock',
        ),
    ]
