# Generated by Django 5.2.10 on 2026-02-01 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0008_process_physical_only_refactor'),
        ('inventory', '0021_alter_inventorystock_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rollconsumption',
            name='machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='roll_consumptions', to='factory.machine'),
        ),
    ]
