# Generated by Django 6.0.1 on 2026-02-02 10:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_alter_rollconsumption_machine'),
        ('materials', '0004_alter_inventorymaterial_category'),
        ('production', '0022_alter_plannedstockorder_plant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryReservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=4, help_text='Reserved Amount', max_digits=12)),
                ('uom', models.CharField(default='KG', max_length=10)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('FULFILLED', 'Fulfilled'), ('RELEASED', 'Released')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='production.productionjob')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='materials.inventorymaterial')),
                ('roll', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='inventory.inventoryroll')),
            ],
            options={
                'verbose_name': 'Inventory Reservation',
                'db_table': 'inventory_reservations',
                'indexes': [models.Index(fields=['job', 'status'], name='inventory_r_job_id_abb996_idx'), models.Index(fields=['roll', 'status'], name='inventory_r_roll_id_00bf64_idx'), models.Index(fields=['material', 'status'], name='inventory_r_materia_673aa3_idx')],
            },
        ),
    ]
