# Generated by Django 5.2.10 on 2026-02-10 13:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_inventoryreservation_override_fields'),
        ('materials', '0007_inventorymaterial_grade'),
        ('production', '0027_alter_productionjob_input_form_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverychallan',
            name='dc_no',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='deliverychallan',
            name='dispatched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliverychallan',
            name='is_system_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deliverychallan',
            name='received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliverychallan',
            name='source_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_interplant_challans', to='production.productionjob'),
        ),
        migrations.AddField(
            model_name='deliverychallan',
            name='target_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_interplant_challans', to='production.productionjob'),
        ),
        migrations.CreateModel(
            name='InterPlantChallanItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('line_type', models.CharField(choices=[('ROLL', 'Roll'), ('BULK', 'Bulk')], max_length=10)),
                ('planned_qty_kg', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('dispatched_qty_kg', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('received_qty_kg', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('DISPATCHED', 'Dispatched'), ('PARTIAL', 'Partially Received'), ('RECEIVED', 'Received')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('challan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.deliverychallan')),
                ('from_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='interplant_items_from', to='inventory.inventorylocation')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interplant_challan_items', to='materials.inventorymaterial')),
                ('roll', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interplant_challan_items', to='inventory.inventoryroll')),
                ('to_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='interplant_items_to', to='inventory.inventorylocation')),
            ],
            options={
                'db_table': 'inventory_interplant_challan_items',
                'ordering': ['created_at'],
            },
        ),
    ]
