# Generated by Django 5.2.10 on 2026-02-12 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_deliverychallan_dc_no_deliverychallan_dispatched_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverychallan',
            name='driver_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='deliverychallan',
            name='driver_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='deliverychallan',
            name='lr_number',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='deliverychallan',
            name='transporter_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='deliverychallan',
            name='vehicle_no',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
