# Generated by Django 5.2.10 on 2026-02-15 05:16

from django.db import migrations, models


def _extract_geometry_override(geometry):
    if not isinstance(geometry, dict):
        return {}
    base = geometry.get('base') if isinstance(geometry.get('base'), dict) else {}
    return {
        'width_mm': base.get('width_mm', geometry.get('width_mm')),
        'height_mm': base.get('height_mm', geometry.get('height_mm')),
        'gusset_mm': geometry.get('gusset_mm'),
        'repeat_length_mm': geometry.get('repeat_length_mm'),
        'adjustments': geometry.get('adjustments') if isinstance(geometry.get('adjustments'), list) else [],
    }


def backfill_roll_matching_metadata(apps, schema_editor):
    InventoryRoll = apps.get_model('inventory', 'InventoryRoll')

    queryset = InventoryRoll.objects.select_related(
        'template',
        'sales_order_item__sales_order',
        'production_job__mts_order',
    )
    for roll in queryset.iterator():
        changed = []

        current_step = int(getattr(roll, 'current_step_index', 0) or 0)
        normalized_step = current_step - 1 if current_step > 0 else 0
        if roll.completed_step_index != normalized_step:
            roll.completed_step_index = normalized_step
            changed.append('completed_step_index')

        geometry_override = {}
        sales_order_item = getattr(roll, 'sales_order_item', None)
        if sales_order_item and getattr(sales_order_item, 'sales_order_id', None):
            geometry_override = sales_order_item.sales_order.geometry_override or {}
            if not geometry_override:
                geometry_override = _extract_geometry_override(sales_order_item.geometry_snapshot or {})
        elif getattr(roll, 'production_job', None) and getattr(roll.production_job, 'mts_order_id', None):
            geometry_override = roll.production_job.mts_order.geometry_override or {}
        elif getattr(roll, 'template', None):
            geometry_override = _extract_geometry_override(roll.template.geometry_schema or {})

        geometry_override = geometry_override or {}
        if roll.geometry_override != geometry_override:
            roll.geometry_override = geometry_override
            changed.append('geometry_override')

        if changed:
            roll.save(update_fields=changed)


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0018_seed_plant_legal_profiles'),
        ('inventory', '0026_deliverychallan_driver_name_and_more'),
        ('materials', '0007_inventorymaterial_grade'),
        ('production', '0028_productionjob_closed_at_productionjob_closed_by_and_more'),
        ('recipes', '0001_initial'),
        ('sales', '0008_salesorder_commercial_confirmed_at_and_more'),
        ('templates', '0012_templateprocesssteprollspec'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryroll',
            name='completed_step_index',
            field=models.IntegerField(default=0, help_text='Canonical completed route step index'),
        ),
        migrations.AddField(
            model_name='inventoryroll',
            name='geometry_override',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddIndex(
            model_name='inventoryroll',
            index=models.Index(fields=['completed_step_index'], name='inventory_r_complet_1ade47_idx'),
        ),
        migrations.RunPython(backfill_roll_matching_metadata, migrations.RunPython.noop),
    ]
