# Generated by Django 5.2.10 on 2026-02-27 21:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0019_machine_standard_rate_kg_per_hour_and_more'),
        ('inventory', '0027_inventoryroll_completed_step_index_and_more'),
        ('materials', '0008_inventorymaterial_packaging_kind_and_more'),
        ('production', '0037_plannedstockorder_invariant_signature'),
        ('sales', '0015_salesorderitem_packaging_snapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackagingTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('INWARD', 'Inward (GRN)'), ('CONSUME', 'Consumption'), ('TRANSFER', 'Location Transfer'), ('ADJUST', 'Manual Adjustment'), ('PRODUCE', 'In-House Production')], max_length=20)),
                ('qty', models.DecimalField(decimal_places=4, help_text='Signed quantity in material.base_uom', max_digits=15)),
                ('avg_cost', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packaging_transactions', to='production.productionjob')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packaging_transactions', to='inventory.inventorylocation')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packaging_transactions', to='materials.inventorymaterial')),
                ('mts_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packaging_transactions', to='production.plannedstockorder')),
                ('sales_order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packaging_transactions', to='sales.salesorderitem')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packaging_transactions', to='inventory.vendor')),
            ],
            options={
                'db_table': 'inventory_packaging_transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PackagingStock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qty', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('avg_cost', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packaging_inventory', to='inventory.inventorylocation')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packaging_stock', to='materials.inventorymaterial')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packaging_inventory', to='factory.plant')),
            ],
            options={
                'db_table': 'inventory_packaging_stock',
                'unique_together': {('material', 'plant', 'location')},
            },
        ),
    ]
