# Generated by Django 5.2.10 on 2026-03-03 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0029_inventoryroll_density_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobworkorder',
            name='dispatched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobworkorder',
            name='emergency_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobworkorder',
            name='meta_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='jobworkorder',
            name='mode',
            field=models.CharField(choices=[('PLANNED_STEP', 'Planned Route Step'), ('EMERGENCY', 'Emergency Handoff')], default='EMERGENCY', max_length=20),
        ),
        migrations.AddField(
            model_name='jobworkorder',
            name='received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobworkorder',
            name='route_step_index',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='jobwork_capabilities',
            field=models.JSONField(blank=True, default=list, help_text="Compatible process codes for jobwork (e.g. ['PRINTING','LAMINATION']). Empty means generic jobwork-capable."),
        ),
        migrations.AddField(
            model_name='vendor',
            name='jobwork_plants',
            field=models.JSONField(blank=True, default=list, help_text='Plant IDs or codes this vendor serves for jobwork. Empty means all plants.'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='qc_required',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='turnaround_hours',
            field=models.PositiveIntegerField(default=48),
        ),
    ]
