# Generated by Django 5.2.10 on 2026-03-19 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0030_jobworkorder_dispatched_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulktransaction',
            name='type',
            field=models.CharField(choices=[('INWARD', 'Inward (GRN)'), ('PRODUCE', 'In-House Production'), ('CONSUME', 'Production Consumption'), ('TRANSFER', 'Location Transfer'), ('ADJUST', 'Manual Adjustment')], max_length=20),
        ),
    ]
