from django.db import migrations


CUSTOMER_NAMES = ['Accuretta Composites',
 'Amanprint N Pack LLP',
 'Amul Packaging',
 'Arham Polyflex',
 'Excel Industries',
 'Golden Packaging',
 'Grace Pack',
 'Greymark Packaging',
 'J.D.Packaging Pvt Ltd (Dr)',
 'Leon Labels Pvt Ltd',
 'Mivansh Packaging',
 'Namrata Enterprises',
 'Navkar Plasto Pack',
 'Nikhil Packaging',
 'Ocean League',
 'Polyprint Packaging',
 'Rainbow Plastic Industries',
 'Rohan Enterprises',
 'Ronak Enterprises',
 'Ruhi Enterprises',
 'Sanjay Print & Pack',
 'Shree Ganesh Roto Print',
 'Shreeji Enterprises-Guj',
 'Shree Sai Flexi Foils',
 'Shree Sai Industries',
 'Sunshil Packaging',
 'Sunshine Laminators (Silvassa) Pvt. Limited',
 'Tricil Packaging Pvt Ltd.',
 'Vivaan Flexi Pack Pvt Ltd',
 'V P Pack & Print Private Limited',
 'Yash Prints',
 'Rudra Immpex',
 'Samarth Plastic',
 'Sundhamaa Enterprises',
 'Alemac Electrical Pvt Ltd',
 'Coatexo Industries Pvt. Ltd.',
 'Fybros Moddular Private Limited',
 'GBL Garden Private Limited',
 'PM CONA Industries Pvt Ltd',
 'Sanjay Food',
 'TISO Industries',
 'Virat Plast',
 'Badhra Appliances LLP',
 'Duvera Industries Private Limited',
 'Gopal Silk Mills',
 'Meril Life Sciences Private Limited',
 'Natbury Lifecare Private Limited',
 'Om Packaging - Surat',
 'Preston Products LLP',
 'Standard Drawing Stores',
 'Supertopman Dressings Pvt. Ltd.',
 'The Ceylon Fancy House',
 'The Ceylon Global Packaging',
 'Jyoti India Kitchensink Pvt Ltd.',
 'Jyoti Kitchen Industries Pvt. Ltd.',
 'Aarav Industries',
 'Abhinandan Creation',
 'Eximtrac',
 'GM Modular Pvt. Ltd.',
 'Jahnavi Enterprises',
 'Janata Stores',
 'Just Fab',
 'Kensui Life Care LLP',
 'Nutrapoorna',
 'Olympia Industries Limited',
 'PNS Electric Solution Private Limited',
 'Ranuja Plastic Industry(D)',
 'Sambhav Fabrics',
 'Schoeller India Industries Pvt. Ltd',
 'Shalibhadra Creations Pvt. Ltd.',
 'Shree Vithlesh Dry Fruit',
 'Shri Ram Spices Pvt Ltd.',
 'SSB Metal Works(Dmn)',
 'Vihan Electric Pvt.Ltd',
 'Rajco Metal Ind. Pvt Ltd.',
 'Agnee Bakers',
 'A.K.Poly',
 'Akshar Packaging',
 'Anil Packaging',
 'Ankita Plastics',
 'Bhavya Enterprises',
 'Bright Enterprises',
 'B.R. Packagings',
 'Chamunda Plastics',
 'Clear Plastic',
 'District Panchayat',
 'Everest Woven Industries',
 'Fortunext Retail Pvt Ltd.',
 'Garg Corporation',
 'Gautam Enterprise',
 'Gudhka Packaging Services',
 'Haria Impex',
 'Hem Creation',
 'Hetvi Packaging',
 'I Shree Khodiar Packaging',
 'Jai Ganesh Packing',
 'Jainam Polymers',
 'Jalaram Polyprint',
 'Jalaram Traders',
 'Jay Enterprises',
 'Jyoti Packaging',
 'Kalki Fashion Private Limited',
 'Keny Plastic Industries',
 'Kevin Polypack',
 'Krishna Marketing ( Bio)',
 'Kshitij Polyline Ltd',
 'Kumar & Sons',
 'Kushal Enterprise',
 'Kvh Packaging Co.',
 'Mahavirs',
 'Mangaldeep Enterprises',
 'Manglam Packaging',
 'Manglik Press Pvt Ltd',
 'Mayur Packaging (B)',
 'Meckon Flexipack',
 'Meera Bag House',
 'Mexim Adhesive Tapes Pvt Ltd',
 'MILI Steel Pvt Ltd',
 'Mubi Craft India',
 'Muskan Trading',
 'Nirmal Products',
 'Packing Material Company',
 'Pawan Sales Agency',
 'Perfect Packaging',
 'Poonam Plastics',
 'Prime Polyprint',
 'Pro Pack',
 'Raghupati Creation',
 'Rajeshwari Traders',
 'Raj Poly Plast',
 'R.B. Hasmat Rai & Co',
 'Reliance Packaging Industries',
 'Saibaba Infocom Pvt Ltd',
 'Sambhav Impex',
 'Saral Enterprises',
 'Shakti Plastics',
 'Shree Laxmi Packaging',
 'S K Traders',
 'Sri Manoj Plastics',
 'Sri Saraswathi Polybags',
 'Star Packaging',
 'Suswani Poly Print',
 'SV Green India Recyclers Private Limited',
 'Swastik Packaging',
 'Swastik Propack Private Limited',
 'Usha Enterprises (D)',
 'Uttam Packaging',
 'Vara Brothers',
 'Vikas General Stores',
 'Vimal Advance Fabrics (Regd)',
 'Vimal Gold Industries (Regd)',
 'Vimaloxy Product',
 'Vimal Plastic and Packaging',
 'Vimalscop Product',
 'Vishal Print -N- Plast Pvt. Ltd.',
 'Vora Packaging']


VENDOR_NAMES = ['Accurate Laminates',
 'Aceto Chem Agencies',
 'Aceto Tex-Chem Private Limited',
 'ADD Ventures',
 'Afflatus Gravures Pvt Ltd',
 'Ahir Vikeshbhai',
 'Ahmedabad Logistic',
 'Ahura Aqua Pvt Ltd',
 'Ahura Associates',
 'Ajanta Transport Co.',
 'Ajit Industries Pvt Ltd',
 'Ajit Petroleum',
 'A K Air Conditioning',
 'Akash Enterprise',
 'Alpha Industrial Products',
 'Amar-Dec Plastic Industries',
 'Amar Plastic',
 'Amee Bhavesh Shinde',
 'A.M.India Logistics',
 'Amkay Polymers',
 'Amul Packaging',
 'Anil Kumar Singh',
 'Anita Devi',
 'A-One Roto Gravure',
 'Apex Scales',
 'Arihant Power Equipments Pvt Ltd.',
 'Ashapura Enterprise',
 'A.S.Trans Care',
 'Auto Tyres',
 'A.V.H Polychem Pvt Ltd.(Cr.)',
 'Baba Vishwakarma Engg. Works',
 'Bajaj Allianz General Insurance',
 'Balaji Instruments & Electric Agencies',
 'Balaji Steels',
 'Basant Tarai',
 'Bhagwati Roof Industries',
 'Bhartiben Dhirubhai Patel',
 'Bhavani Pipe Fitting Center',
 'Blend Colour Pvt. Ltd.',
 'Bombay Tools Supplying Agency',
 'Brantford Limited',
 'Business Alert Infotech Pvt. Ltd.',
 'Chetak Machinery Stores',
 'Chetak Tube Traders',
 'Chheda Society-CR',
 'Chief Officer Notified Area Gidc-Vapi',
 'Chief Officer Notified Area-Sarigam',
 'Chirag Gudhka (AXIS CC ....1455)',
 'Chirag Gudhka (Axis CC 411 4606 0208 0818)',
 'Chirag Gudhka (HDFC CC 3607 650040 6663)',
 'Chirag Gudhka on Behalf Expenses',
 'Chirag Gudhka (Rent A/c.)',
 'Chiripal Polyfilms Ltd.',
 'Choudhary Packaging',
 'Chourasiya Packaging',
 'C K Zipper Pvt. Ltd',
 'Clear Polyplast India Pvt Ltd-(C.R)',
 'Convertech Equipment Private Limited',
 'Coraplast Industries',
 'Croma Polymer',
 'C Trivedi & Co',
 'Dabhel Gram Panchayat, Daman',
 'Dabulker Art',
 'DDED-Electricity Department',
 'DDED-Electricity Department-UNIT.2',
 'DDED-Electricity Department-UNIT.3',
 'Delta  Enterprise',
 'Delux  Enterprises Global Pvt Ltd',
 'Desire Food and Beverages',
 'Dhanraj Suresh Pandit',
 'Dhwani Polyprints Pvt Ltd.',
 'Diamond Engineering Works',
 'Dilip Engineers',
 'Dilip Mechanical Works',
 'Dipak Jadav Tempo Service',
 'Divya Printers',
 'Diya Enterprises',
 'D.M.Corporation',
 'DP Enterprises',
 'D.P.R Express Parcel Service',
 'Eltech Engineers Private Limited',
 'Eminent Insulation',
 'Enrich Encap Private Limited',
 'Erhardt Plus Leimer India Private Limited',
 'Everon Logistics Pvt Ltd',
 'Excelus Machineries Pvt Ltd',
 'Flexon Engineers Private Limited',
 'Fly Ostrich India Private Limited',
 'Fortunext Retail Pvt Ltd',
 'Frans Engineering Corporation',
 'Galaxy Packtech Pvt Ltd.',
 'Gandhi Shashikant Jaysukhlal',
 'Gayatri Rub Tech',
 'G. Choudhary Enterprises',
 'Globall Plast',
 'Goldcoin Angel Cpp Film Pvt Ltd.',
 'Green Plus Carrier',
 'Guardex Fire Equipment Co.Vapi',
 'Gudhka Packaging Services',
 'Gujarat Polymers Private Limited',
 'Gulson Traders',
 'Gurucharan Industries',
 'Gyandas  Choudhary',
 'Haresh Ratilal Gudhka (Rent A/c.)',
 'Haria Impex (Cr)',
 'Hari Om Plastic Industries',
 'Hari Om Security Service',
 'HDFC ERGO General Insurance Company Limited',
 'Heat Tech Technology',
 'Henkal Adhesive Technologies Pvt Ltd',
 'Hk Carrier',
 'H.M.D.Roadways',
 'Hotel Grand Heritage',
 'Hotel Mountain View',
 'Hotel Royal Garden',
 'Hotel Siddharth',
 'Hubergroup India Pvt Ltd',
 'Hvd Distributors Pvt. Ltd.',
 'ICICI Lambard General Insurance Co. Ltd.',
 'Inception Technologies',
 'Indian Fire Safety',
 'Jagdish Auto Garage',
 'Jahnavi Enterprises',
 'Jainam Polymers',
 'Jash Engineering Works',
 'Jasoda Devi',
 'Jay Enterprises(C.R)',
 'Jayshree Agency',
 'Jitesh Enterprises Cr.',
 'J.K Sweets Private Limited',
 'Kanubhai R Patel',
 'Kataria Automobiles Pvt Ltd',
 'Kavya Steel',
 'Keny Plastic Industries- Cr',
 'Kishor Kumar Kedia HUF',
 'Krishna Caterers',
 'Krishna Services',
 'Krishna Wire Products',
 'Kshitij Polyline Ltd',
 'Kulwinder Singh',
 'Kushal Cargo',
 'Lakshmi Corporation',
 'Lalji Mulji Transport Co.',
 'Laxmi Enterprises',
 'Leeladhari Steel Industries',
 'Leon Labels Pvt Ltd',
 'Liftech Elevator Corporation',
 'Lubi Electronics',
 'Mahavir Laminates',
 'Maitri Traders',
 'Malhotra Transport Co',
 'Mamata Machinery Limited',
 'Mamta Steel',
 'Manas Polyprints',
 'Mangalam Engineering',
 'Manoj Cargo Carriers',
 'Manoj Kumar Kothari-Comm',
 'Marble Park',
 'Maruti Enterprises',
 'Maruti Petrochem',
 'Maruti Transport',
 'Master Extrusions',
 'Matha Engineering Works',
 'Mavani Santoki & Cọ.',
 'Md Seraj Ahamad',
 'M.K.Hardware',
 'Mukesh Gandhi',
 'Muktanand Transport',
 'Mundra Corporation',
 'Nakchhatra Vimleshkumar Mehta',
 'Nakoda Plast Industries Pvt Ltd',
 'Narmada Steel',
 'Nasa Computer Education',
 'Navien Ss Traders',
 'Navkar Tubes and Cores',
 'Naysar Vinod Shah-Comm',
 'Nazir R Khan',
 'Nehal Roadlines',
 'Neha Motors',
 'New Mahaveer Transport Co.of.Bharat',
 'New Suryavanshi Roadways',
 'Niket Communication & Security Systems',
 'Nilkanth Electro Services',
 'Ocean Polymers',
 'Okara Roadways(REGD)',
 'Omega Plasto Limited',
 'OM Enterprise',
 'Om Lab Chem',
 'Omprakash Ladsaria HUF',
 'Om Sai Hydraulics',
 'Origin Textiles Pvt Ltd',
 'Packaging Services- Cr',
 'Pack Print Industries India Private Limited Cr.',
 'Padmavati Auto Agencies',
 'Panamax Limited',
 'Paras Packaging',
 'Paras Polypacks (Rent A/c.)',
 'Parth Agency',
 'Parth Ceramics',
 'Parth Engineering Works',
 'Pavan Interior Concept',
 'Pepcee Pack Global Limited - Daman',
 'Pepcee Pack Industries',
 'Phoenix (India) Rubber Products',
 'PMP Transport',
 'Poly World',
 'Power Lubes (India)',
 'Power Switch Gears',
 'Pragnesh Electrolinks',
 'Prasad Gwk Cooltech Pvt. Ltd.',
 'Prasad Polychem Pvt Ltd',
 'Precitech Weighing Systems',
 'Premier Electronics',
 'Premier Industrial Electronics Private Limited',
 'Prime Polychem Pvt Ltd',
 'Prime Systems',
 'Printile Industries Pvt Ltd (C.R)',
 'Prisam Engitech Pvt Ltd',
 'Priyanka Enterprises',
 'Priya Traders Co.',
 'Protoligths Private Limited',
 'Pushpam Containers Pvt Ltd',
 'Pyramid Industries',
 'Quantum Systems',
 'Quest Consultancy Pvt Ltd',
 'Raghukul Enterprises',
 'Rainbow Plastic Industries',
 'Rainbow Plastics India Limited',
 'Rajesh Damani-Comm',
 'Raj Lalwani HUF',
 'Ramniklal S. Gosalia & Co.',
 'Ranuja Plastic Industry-Comm',
 'Ratan Infra',
 'Rathod Freight Carriers',
 'Rebuild Enterprise',
 'Regal Fire Services',
 'Reliance Industries Limited',
 'Reliance Packaging Industries-CR',
 'R.K. Electrical',
 'Rnd Technosoft',
 'Rollex Machinery Pvt Ltd',
 'Ronak Electronics',
 'Rossini India Printing Rollers Pvt Ltd',
 'Rubix Data Sciences Private Limited',
 'S A Automation Pvt Ltd',
 'Sai Ganesh Block',
 'Sai Krupa Sewing Machine',
 'Sai Plastics',
 'Sairam Engineers',
 'Sai Samarth Industries',
 'Sambhav Impex Cr',
 'Samrat Cars Pvt.Ltd.',
 'Sansam Polymers Pvt Ltd',
 'Sarpo Gravures Pvt Ltd.',
 'Sb Flexographic Products',
 'Setco Inks Private Limited',
 'Shahil Electrical Services',
 'Shah Lalji Nangpar Raymal Samarpan Nidhi',
 'Shah Packwell Industries',
 'Shakti Print N Plast',
 'Shanti Patra Plastics Pvt Ltd',
 'Shanti Spincot Private Limited',
 'Shiv Medical & General Stores',
 'Shraddha Roadways',
 'Shree Balaji Blades Corportation',
 'Shree Balaji Corporation',
 'Shree Ganesh Trading',
 'Shree G Industries',
 'Shree Halari Visha Oswal Sarvajanik Panjrapole',
 'Shree Hari Transport',
 'Shreeji Chemtech',
 'Shreeji Road Carriers',
 'Shreeji Sweets',
 'Shree Krishna Rubber',
 'Shree Laxmi Packaging',
 'Shree Laxmi Pump & Drives',
 'Shree Machinery',
 'Shree Mahalaxmi Plywood',
 'Shree Ram Engineers',
 'Shree Sai Consultancy',
 'Shree Shakti Polyfilms Pvt. Ltd (C)',
 'Shree Somnath Petroleum',
 'Shree Techno',
 'Shree Trading Co.-Comm',
 'Shri Avirat Frp Mouldesr',
 'Shri Krishna Paints Agency',
 'Shriram General Insurance Co Ltd',
 'Shubham Extrusion Machines Pvt Ltd',
 'S.K.Engineers',
 'S.N.Services',
 'SPCX Pvt Ltd',
 'Splendid Aqua Technology',
 'Srishty Freight Carriers',
 'Star Flexi Films',
 'State Bank of India',
 'ST Roadways',
 'Sudarshan Coatings',
 'Sun Packaging',
 'Super Bond Adhesives Pvt Ltd',
 'Svm Packaging',
 'Svp Packaging Industry Pvt Ltd',
 'Swastik Enterprise',
 'Swati Trans Logistics Private Limited',
 'Tally Web Solutions',
 'Tarajyot Polymers Ltd',
 'Target Polymers Pvt.Ltd.',
 'Tata AIG General Insurance Co.Ltd',
 'Tata Aig General Insurance Company Limited',
 'Taurus Enterprises',
 'Thalia Polymers',
 'The Cellphone Studio',
 'The New India Assurance Co Ltd',
 'Total Packaging Services',
 'Total Poly World',
 'Tri Trac Technologies Pvt Ltd',
 'Tulsi Enterprises (Courier)',
 'Turning Point',
 'Tushar Hardware & General Stores',
 'Uflex Limited',
 'Unnikrishnan A Nair',
 'Urja Products Pvt Ltd',
 'Valco Melton Engineering India Private Limited',
 'Vapi Municipal Corporation',
 'Vardhaman Steel Centre',
 'Varsha Haresh Gudhka (Rent A/c.)',
 'Ve Commercial Vehicles Limited',
 'Ved Prime Construction',
 'Vijay Engineers',
 'Vij Electricals And Services',
 'Vij Electricals & Engineers',
 'Vina Road Lines',
 'Vinayak Engineering Works',
 'Vinayak Enterprises',
 'Viral Enterprise',
 'Virali R Jain',
 'Vishal Parivahan',
 'Vishal Print World',
 'Vishwakarma Aluminium',
 'Vjex Industries',
 'Vodafoneidea Ltd',
 'Vraj Traders(Cr.)',
 'Vrl Logistics Ltd',
 'V-Trans (Gujarat)',
 'XL Plastic Machinery Pvt. Ltd.',
 'XL Plastics',
 'Yashgaj Enterprise',
 'Yash Traders',
 'Yug Enterprises',
 'Zeel Impex',
 'Ziptech']


def _next_code(model, prefix, start_index):
    index = start_index
    while True:
        code = f"{prefix}-{index:04d}"
        if not model.objects.filter(code=code).exists():
            return code
        index += 1


def seed_partner_names(apps, schema_editor):
    Customer = apps.get_model("sales", "Customer")
    Vendor = apps.get_model("inventory", "Vendor")

    existing_customers = {name.casefold() for name in Customer.objects.values_list("name", flat=True)}
    customer_index = 1
    for name in CUSTOMER_NAMES:
        if name.casefold() in existing_customers:
            continue
        code = _next_code(Customer, "TALLY-CUST", customer_index)
        customer_index += 1
        Customer.objects.create(name=name, code=code, status="ACTIVE")
        existing_customers.add(name.casefold())

    existing_vendors = {name.casefold() for name in Vendor.objects.values_list("name", flat=True)}
    vendor_index = 1
    for name in VENDOR_NAMES:
        if name.casefold() in existing_vendors:
            continue
        code = _next_code(Vendor, "TALLY-VEND", vendor_index)
        vendor_index += 1
        Vendor.objects.create(name=name, code=code, type="RM", status="ACTIVE")
        existing_vendors.add(name.casefold())


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0031_alter_bulktransaction_type"),
        ("sales", "0019_alter_salesorder_status"),
    ]

    operations = [
        migrations.RunPython(seed_partner_names, migrations.RunPython.noop),
    ]
