# Generated by Django 6.0.4 on 2026-04-21 08:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0023_machine_code_per_work_center'),
        ('inventory', '0034_vendor_additional_addresses_vendor_bank_details_and_more'),
        ('materials', '0017_alter_inventorymaterial_per_sheet_base_qty'),
        ('recipes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryAuditBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_no', models.CharField(blank=True, max_length=60, unique=True)),
                ('type', models.CharField(choices=[('OPENING_STOCK', 'Opening Stock'), ('PHYSICAL_COUNT', 'Physical Count'), ('FY_CLOSE', 'Financial Year Close'), ('FY_CORRECTION', 'Financial Year Correction')], max_length=30)),
                ('financial_year', models.CharField(db_index=True, max_length=20)),
                ('cutoff_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted'), ('LOCKED', 'Locked'), ('VOID', 'Void')], db_index=True, default='DRAFT', max_length=20)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('source_file_name', models.CharField(blank=True, max_length=255)),
                ('summary_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_inventory_audit_batches', to=settings.AUTH_USER_MODEL)),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_inventory_audit_batches', to=settings.AUTH_USER_MODEL)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_audit_batches', to='factory.plant')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_inventory_audit_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'inventory_audit_batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryAuditLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stock_class', models.CharField(choices=[('BULK', 'Bulk'), ('ROLL', 'Roll'), ('PACKAGING', 'Packaging')], max_length=20)),
                ('uom', models.CharField(blank=True, default='KG', max_length=20)),
                ('system_qty', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('counted_qty', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('variance_qty', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('opening_qty', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('rate', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('value', models.DecimalField(decimal_places=4, default=0, max_digits=16)),
                ('label_id', models.CharField(blank=True, max_length=80)),
                ('batch_no', models.CharField(blank=True, max_length=100)),
                ('width_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('thickness_micron', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('length_m', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_fg', models.BooleanField(default=False)),
                ('stage_index', models.IntegerField(default=0)),
                ('status', models.CharField(blank=True, default='AVAILABLE', max_length=20)),
                ('packaging_kind', models.CharField(blank=True, max_length=20)),
                ('base_uom', models.CharField(blank=True, max_length=20)),
                ('posted_reference_json', models.JSONField(blank=True, default=dict)),
                ('row_errors', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.inventoryauditbatch')),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_audit_lines', to='recipes.recipegrade')),
                ('granule_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_audit_lines', to='materials.granulequalitycode')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_audit_lines', to='inventory.inventorylocation')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_audit_lines', to='materials.inventorymaterial')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_audit_lines', to='factory.plant')),
            ],
            options={
                'db_table': 'inventory_audit_lines',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryFinancialPeriod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('financial_year', models.CharField(max_length=20, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSING_IN_PROGRESS', 'Closing In Progress'), ('CLOSED', 'Closed')], db_index=True, default='OPEN', max_length=30)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_inventory_periods', to=settings.AUTH_USER_MODEL)),
                ('closing_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_periods', to='inventory.inventoryauditbatch')),
                ('opening_batch_next_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_from_periods', to='inventory.inventoryauditbatch')),
            ],
            options={
                'db_table': 'inventory_financial_periods',
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddIndex(
            model_name='inventoryauditbatch',
            index=models.Index(fields=['type', 'status'], name='inventory_a_type_eb6001_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryauditbatch',
            index=models.Index(fields=['financial_year', 'plant'], name='inventory_a_financi_d5ac60_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryauditbatch',
            index=models.Index(fields=['cutoff_at'], name='inventory_a_cutoff__743c39_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryauditline',
            index=models.Index(fields=['stock_class', 'material'], name='inventory_a_stock_c_d16592_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryauditline',
            index=models.Index(fields=['plant', 'location'], name='inventory_a_plant_i_e62162_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryauditline',
            index=models.Index(fields=['label_id'], name='inventory_a_label_i_db8645_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventoryfinancialperiod',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'OPEN')), fields=('status',), name='uniq_open_inventory_financial_period'),
        ),
    ]
