# Generated by Codex on 2026-04-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0035_inventoryauditbatch_inventoryauditline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryreservation',
            name='target_grade_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='inventoryreservation',
            name='target_lane_key',
            field=models.CharField(blank=True, db_index=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='inventoryreservation',
            name='target_lane_label',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='inventoryreservation',
            name='target_lane_meta',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='inventoryreservation',
            name='target_layer_index',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventoryreservation',
            name='target_source_step_index',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventoryreservation',
            name='target_thickness_micron',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='inventoryreservation',
            name='target_variant_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='inventoryreservation',
            name='target_width_mm',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
    ]
