# Generated by Codex on 2026-04-24

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0036_inventoryreservation_lane_metadata"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryCorrectionAudit",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("source_type", models.CharField(choices=[("BULK", "Bulk GRN"), ("PACKAGING", "Packaging GRN"), ("ROLL", "Roll GRN")], max_length=20)),
                ("source_id", models.UUIDField(db_index=True)),
                ("correction_type", models.CharField(default="GRN_CORRECTION", max_length=40)),
                ("reason", models.TextField()),
                ("before_json", models.JSONField(blank=True, default=dict)),
                ("after_json", models.JSONField(blank=True, default=dict)),
                ("delta_json", models.JSONField(blank=True, default=dict)),
                ("effective_role", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("actor", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="inventory_corrections", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "inventory_correction_audit",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["source_type", "source_id"], name="inventory_c_source__6b989e_idx"),
                    models.Index(fields=["created_at"], name="inventory_c_created_078008_idx"),
                ],
            },
        ),
    ]
