# Generated by Django 6.0.4 on 2026-04-24 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0037_inventory_correction_audit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulktransaction',
            name='type',
            field=models.CharField(choices=[('INWARD', 'Inward (GRN)'), ('PRODUCE', 'In-House Production'), ('CONSUME', 'Production Consumption'), ('TRANSFER', 'Location Transfer'), ('ADJUST', 'Manual Adjustment'), ('OPENING_BALANCE', 'Opening Balance'), ('COUNT_SHORT', 'Physical Count Short'), ('COUNT_EXCESS', 'Physical Count Excess'), ('FY_ROLLFORWARD', 'FY Roll Forward'), ('FY_CORRECTION', 'FY Correction')], max_length=20),
        ),
        migrations.AlterField(
            model_name='inventoryauditbatch',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted for Approval'), ('APPROVED', 'Approved'), ('POSTED', 'Posted'), ('LOCKED', 'Locked'), ('CANCELLED', 'Cancelled'), ('VOID', 'Void')], db_index=True, default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='inventoryroll',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('RESERVED', 'Reserved'), ('IN_PROCESS', 'In Process'), ('SENT_JOBWORK', 'Sent to Job Work'), ('CONSUMED', 'Consumed'), ('MISSING', 'Missing after Stock Count'), ('SCRAPPED', 'Scrapped')], default='AVAILABLE', max_length=20),
        ),
        migrations.AlterField(
            model_name='packagingtransaction',
            name='type',
            field=models.CharField(choices=[('INWARD', 'Inward (GRN)'), ('CONSUME', 'Consumption'), ('TRANSFER', 'Location Transfer'), ('ADJUST', 'Manual Adjustment'), ('PRODUCE', 'In-House Production'), ('OPENING_BALANCE', 'Opening Balance'), ('COUNT_SHORT', 'Physical Count Short'), ('COUNT_EXCESS', 'Physical Count Excess'), ('FY_ROLLFORWARD', 'FY Roll Forward'), ('FY_CORRECTION', 'FY Correction')], max_length=20),
        ),
        migrations.AlterField(
            model_name='rollmovement',
            name='reason',
            field=models.CharField(choices=[('GRN', 'Goods Receipt'), ('PRODUCTION', 'Production Issue'), ('WIP_TRANSFER', 'WIP Transfer'), ('FG_TRANSFER', 'FG Storage'), ('DISPATCH', 'Dispatch'), ('JOBWORK_OUT', 'Job Work Send'), ('JOBWORK_IN', 'Job Work Return'), ('SCRAP', 'Scrap Yard'), ('ADJUSTMENT', 'Manual Adjustment'), ('INTER_PLANT', 'Inter-Plant Transfer'), ('OPENING_BALANCE', 'Opening Balance'), ('COUNT_SHORT', 'Physical Count Short'), ('COUNT_EXCESS', 'Physical Count Excess'), ('FY_ROLLFORWARD', 'FY Roll Forward'), ('FY_CORRECTION', 'FY Correction')], max_length=20),
        ),
    ]
