# Generated by Django 6.0.4 on 2026-04-25 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0038_alter_bulktransaction_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulktransaction',
            name='type',
            field=models.CharField(choices=[('INWARD', 'Inward (GRN)'), ('PRODUCE', 'In-House Production'), ('CONSUME', 'Production Consumption'), ('TRANSFER', 'Location Transfer'), ('ADJUST', 'Manual Adjustment'), ('OPENING_BALANCE', 'Opening Balance'), ('OPENING_BALANCE_ADJUST', 'Opening Balance Adjustment'), ('COUNT_SHORT', 'Physical Count Short'), ('COUNT_EXCESS', 'Physical Count Excess'), ('FY_ROLLFORWARD', 'FY Roll Forward'), ('FY_CORRECTION', 'FY Correction')], max_length=30),
        ),
        migrations.AlterField(
            model_name='packagingtransaction',
            name='type',
            field=models.CharField(choices=[('INWARD', 'Inward (GRN)'), ('CONSUME', 'Consumption'), ('TRANSFER', 'Location Transfer'), ('ADJUST', 'Manual Adjustment'), ('PRODUCE', 'In-House Production'), ('OPENING_BALANCE', 'Opening Balance'), ('OPENING_BALANCE_ADJUST', 'Opening Balance Adjustment'), ('COUNT_SHORT', 'Physical Count Short'), ('COUNT_EXCESS', 'Physical Count Excess'), ('FY_ROLLFORWARD', 'FY Roll Forward'), ('FY_CORRECTION', 'FY Correction')], max_length=30),
        ),
        migrations.AlterField(
            model_name='rollmovement',
            name='reason',
            field=models.CharField(choices=[('GRN', 'Goods Receipt'), ('PRODUCTION', 'Production Issue'), ('WIP_TRANSFER', 'WIP Transfer'), ('FG_TRANSFER', 'FG Storage'), ('DISPATCH', 'Dispatch'), ('JOBWORK_OUT', 'Job Work Send'), ('JOBWORK_IN', 'Job Work Return'), ('SCRAP', 'Scrap Yard'), ('ADJUSTMENT', 'Manual Adjustment'), ('INTER_PLANT', 'Inter-Plant Transfer'), ('OPENING_BALANCE', 'Opening Balance'), ('OPENING_BALANCE_ADJUST', 'Opening Balance Adjustment'), ('COUNT_SHORT', 'Physical Count Short'), ('COUNT_EXCESS', 'Physical Count Excess'), ('FY_ROLLFORWARD', 'FY Roll Forward'), ('FY_CORRECTION', 'FY Correction')], max_length=30),
        ),
    ]
