# Generated by Django 6.0.4 on 2026-05-09 08:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0040_inventoryroll_roll_weight_breakdown'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventorySavedView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace', models.CharField(choices=[('rolls', 'Rolls'), ('bulk', 'Bulk'), ('packaging', 'Packaging'), ('addons', 'Add-ons'), ('home', 'Inventory Home')], db_index=True, max_length=40)),
                ('name', models.CharField(max_length=120)),
                ('icon', models.CharField(blank=True, default='', max_length=16)),
                ('pinned', models.BooleanField(default=False)),
                ('state', models.JSONField(blank=True, default=dict)),
                ('shared_team', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_saved_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'inventory_saved_views',
                'ordering': ['-pinned', 'name'],
                'indexes': [models.Index(fields=['workspace', 'user'], name='inventory_s_workspa_f100b4_idx'), models.Index(fields=['workspace', 'shared_team'], name='inventory_s_workspa_a3bd2e_idx')],
            },
        ),
    ]
