# Generated by Django 6.0.4 on 2026-05-20 18:54

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0024_process_active_process_has_artwork_process_notes_and_more'),
        ('inventory', '0041_inventory_saved_view'),
        ('materials', '0037_add_is_sellable_and_trading_good'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=40, unique=True)),
                ('reason', models.CharField(choices=[('DAMAGE', 'Damaged / spoiled'), ('WRITE_OFF', 'Write-off'), ('FOUND', 'Found / unaccounted'), ('COUNT_CORRECTION', 'Count correction'), ('RECLASSIFY', 'Reclassification'), ('OTHER', 'Other')], default='OTHER', max_length=24)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted'), ('VOID', 'Voided')], db_index=True, default='DRAFT', max_length=12)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_stock_adjustments', to=settings.AUTH_USER_MODEL)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_adjustments', to='factory.plant')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_stock_adjustments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'inventory_stock_adjustment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockAdjustmentLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('line_no', models.PositiveIntegerField(default=1)),
                ('stock_class', models.CharField(choices=[('BULK', 'Bulk'), ('ROLL', 'Roll'), ('PACKAGING', 'Packaging'), ('TRADING_GOOD', 'Trading Good')], max_length=16)),
                ('before_qty', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14)),
                ('delta_qty', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14)),
                ('after_qty', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14)),
                ('uom', models.CharField(default='KG', max_length=10)),
                ('value_inr', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('adjustment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.stockadjustment')),
                ('inventory_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='materials.inventorymaterial')),
                ('inventory_roll', models.ForeignKey(blank=True, help_text='Specific roll being adjusted (ROLL class only)', null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.inventoryroll')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.inventorylocation')),
                ('trading_good', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='materials.tradinggood')),
            ],
            options={
                'db_table': 'inventory_stock_adjustment_line',
                'ordering': ['line_no', 'id'],
            },
        ),
    ]
