# Generated by Django 6.0.4 on 2026-05-28 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0042_add_stock_adjustment'),
        ('materials', '0042_inventorymaterial_lead_time_override_days_and_more'),
        ('production', '0058_productionjob_meta_json'),
        ('sales', '0032_salesorder_completed_at_alter_salesorder_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulktransaction',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulk_transactions', to='inventory.vendor'),
        ),
        migrations.AddField(
            model_name='bulktransaction',
            name='vendor_invoice_no',
            field=models.CharField(blank=True, db_index=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='inventoryroll',
            name='vendor',
            field=models.ForeignKey(blank=True, help_text='GRN vendor reference for traceability', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_rolls', to='inventory.vendor'),
        ),
        migrations.AddField(
            model_name='inventoryroll',
            name='vendor_invoice_no',
            field=models.CharField(blank=True, db_index=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='packagingtransaction',
            name='vendor_invoice_no',
            field=models.CharField(blank=True, db_index=True, default='', max_length=80),
        ),
        migrations.AddConstraint(
            model_name='bulktransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('vendor_invoice_no__gt', ''), ('vendor__isnull', False)), fields=('vendor', 'vendor_invoice_no'), name='uniq_bulk_tx_vendor_invoice'),
        ),
        migrations.AddConstraint(
            model_name='packagingtransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('vendor_invoice_no__gt', ''), ('vendor__isnull', False)), fields=('vendor', 'vendor_invoice_no'), name='uniq_pkg_tx_vendor_invoice'),
        ),
    ]
