# Generated by Django 6.0.4 on 2026-05-28 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0043_bulktransaction_vendor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulktransaction',
            name='manual_po_ref',
            field=models.CharField(blank=True, db_index=True, default='', help_text="Vendor's PO ref when receiving against a PO not in our system (i.e. no system_po linkage).", max_length=80),
        ),
        migrations.AddField(
            model_name='inventoryroll',
            name='manual_po_ref',
            field=models.CharField(blank=True, db_index=True, default='', help_text="Vendor's PO ref when receiving against a PO not in our system (i.e. no system_po linkage).", max_length=80),
        ),
        migrations.AddField(
            model_name='packagingtransaction',
            name='manual_po_ref',
            field=models.CharField(blank=True, db_index=True, default='', help_text="Vendor's PO ref when receiving against a PO not in our system (i.e. no system_po linkage).", max_length=80),
        ),
    ]
