# Generated by Django 6.0.4 on 2026-05-31 09:48

from django.db import migrations, models


def backfill_open_web(apps, schema_editor):
    InventoryRoll = apps.get_model('inventory', 'InventoryRoll')
    InventoryRoll.objects.update(stock_form="OPEN_WEB", width_basis="OPEN_WEB_WIDTH")


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0045_relax_vendor_invoice_multiline_grn'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryroll',
            name='stock_form',
            field=models.CharField(choices=[('OPEN_WEB', 'Open web / sheet'), ('LAYFLAT_TUBE', 'Lay-flat tube'), ('FOLDED_WEB', 'Folded web')], db_index=True, default='OPEN_WEB', help_text='Physical form of this roll stock.', max_length=24),
        ),
        migrations.AddField(
            model_name='inventoryroll',
            name='width_basis',
            field=models.CharField(choices=[('OPEN_WEB_WIDTH', 'Open-web width'), ('LAYFLAT_WIDTH', 'Lay-flat width'), ('FOLDED_WIDTH', 'Folded width')], default='OPEN_WEB_WIDTH', help_text='Meaning of width_mm for this roll.', max_length=32),
        ),
        migrations.AlterField(
            model_name='inventoryroll',
            name='width_mm',
            field=models.DecimalField(decimal_places=2, help_text='Physical stock width: open-web width for sheet/open web, lay-flat width for tube stock.', max_digits=10),
        ),
        migrations.RunPython(backfill_open_web, migrations.RunPython.noop),
    ]
