# Generated by Codex on 2026-06-13

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("factory", "0026_process_stock_form_capabilities"),
        ("inventory", "0048_inkmaterial_swatch_hex"),
        ("materials", "0048_canonical_pouch_styles"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="inkmaterial",
            name="is_mix",
            field=models.BooleanField(default=False, help_text="True when this ink master represents a returned/mixed floor color."),
        ),
        migrations.AddField(
            model_name="inkmaterial",
            name="mix_family",
            field=models.CharField(blank=True, default="", help_text="Operational grouping such as BLACK MIX or GOLD MIX.", max_length=80),
        ),
        migrations.AddField(
            model_name="inkmaterial",
            name="mix_notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.CreateModel(
            name="InkFloorSession",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("shift_code", models.CharField(blank=True, default="", max_length=20)),
                ("shift_date", models.DateField(blank=True, null=True)),
                ("opened_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("counted_at", models.DateTimeField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("status", models.CharField(choices=[("OPEN", "Open"), ("POSTED", "Posted"), ("LOCKED", "Locked"), ("VOID", "Void")], db_index=True, default="OPEN", max_length=20)),
                ("reference", models.CharField(blank=True, default="", max_length=120)),
                ("notes", models.TextField(blank=True, default="")),
                ("posted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="created_ink_floor_sessions", to=settings.AUTH_USER_MODEL)),
                ("location", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="ink_floor_sessions", to="inventory.inventorylocation")),
                ("machine", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="ink_floor_sessions", to="factory.machine")),
                ("plant", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="ink_floor_sessions", to="factory.plant")),
                ("posted_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="posted_ink_floor_sessions", to=settings.AUTH_USER_MODEL)),
                ("work_center", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="ink_floor_sessions", to="factory.workcenter")),
            ],
            options={
                "db_table": "inventory_ink_floor_sessions",
                "ordering": ["-opened_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InkFloorMovement",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("type", models.CharField(choices=[("ISSUE", "Issue To Floor"), ("RETURN", "Return From Floor"), ("MIX_RETURN", "Mixed Ink Return"), ("COUNT_ADJUST", "Stock Count Adjustment")], db_index=True, max_length=20)),
                ("qty_kg", models.DecimalField(decimal_places=4, max_digits=15)),
                ("event_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("shift_code", models.CharField(blank=True, default="", max_length=20)),
                ("shift_date", models.DateField(blank=True, null=True)),
                ("reference", models.CharField(blank=True, default="", max_length=160)),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("bulk_transaction", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="ink_floor_movements", to="inventory.bulktransaction")),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="created_ink_floor_movements", to=settings.AUTH_USER_MODEL)),
                ("destination_location", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="ink_floor_destination_movements", to="inventory.inventorylocation")),
                ("material", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="ink_floor_movements", to="materials.inventorymaterial")),
                ("plant", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="ink_floor_movements", to="factory.plant")),
                ("session", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="movements", to="inventory.inkfloorsession")),
                ("source_location", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="ink_floor_source_movements", to="inventory.inventorylocation")),
                ("target_material", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="ink_floor_target_movements", to="materials.inventorymaterial")),
            ],
            options={
                "db_table": "inventory_ink_floor_movements",
                "ordering": ["-event_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InkFloorCountLine",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("system_qty_kg", models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ("counted_qty_kg", models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ("variance_qty_kg", models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("adjustment_transaction", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="ink_floor_count_lines", to="inventory.bulktransaction")),
                ("material", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="ink_floor_count_lines", to="materials.inventorymaterial")),
                ("session", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="count_lines", to="inventory.inkfloorsession")),
            ],
            options={
                "db_table": "inventory_ink_floor_count_lines",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="inkfloorsession",
            index=models.Index(fields=["plant", "location", "status"], name="inventory_i_plant_i_5b638c_idx"),
        ),
        migrations.AddIndex(
            model_name="inkfloorsession",
            index=models.Index(fields=["shift_date", "shift_code"], name="inventory_i_shift_d_80a6b4_idx"),
        ),
        migrations.AddIndex(
            model_name="inkfloorsession",
            index=models.Index(fields=["opened_at", "closed_at"], name="inventory_i_opened__d9923e_idx"),
        ),
        migrations.AddIndex(
            model_name="inkfloormovement",
            index=models.Index(fields=["plant", "event_at"], name="inventory_i_plant_i_c18a22_idx"),
        ),
        migrations.AddIndex(
            model_name="inkfloormovement",
            index=models.Index(fields=["material", "event_at"], name="inventory_i_materia_3a2e5f_idx"),
        ),
        migrations.AddIndex(
            model_name="inkfloormovement",
            index=models.Index(fields=["type", "event_at"], name="inventory_i_type_2bb07e_idx"),
        ),
        migrations.AddIndex(
            model_name="inkfloormovement",
            index=models.Index(fields=["shift_date", "shift_code"], name="inventory_i_shift_d_6517ea_idx"),
        ),
        migrations.AddIndex(
            model_name="inkfloorcountline",
            index=models.Index(fields=["material"], name="inventory_i_materia_37ecd4_idx"),
        ),
        migrations.AddConstraint(
            model_name="inkfloorcountline",
            constraint=models.UniqueConstraint(fields=("session", "material"), name="unique_ink_count_material_per_session"),
        ),
    ]
