# Generated by Django 6.0.8 on 2026-09-27 11:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0050_interplantchallanitem_granule_code'),
        ('materials', '0051_productvariant_spec_snapshot'),
        ('production', '0072_merge_release_hardening'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverychallan',
            name='request_fingerprint',
            field=models.CharField(blank=True, default='', editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name='deliverychallan',
            name='request_key',
            field=models.CharField(blank=True, editable=False, max_length=128, null=True, unique=True),
        ),
        migrations.AddConstraint(
            model_name='inventoryreservation',
            constraint=models.UniqueConstraint(condition=models.Q(('roll__isnull', False), ('status', 'ACTIVE')), fields=('roll',), name='one_active_reservation_per_roll'),
        ),
    ]
