# Generated by Django 6.0.8 on 2026-10-09 21:17

import apps.inventory.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0028_enable_print_process_capabilities'),
        ('gate', '0004_documents_outward_gate_passes'),
        ('inventory', '0053_explicit_maintenance_audit'),
        ('materials', '0051_productvariant_spec_snapshot'),
        ('production', '0074_jobwork_waste_scrap_reason'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobWorkChallan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=32, unique=True)),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('purpose', models.CharField(max_length=160)),
                ('expected_return_date', models.DateField(blank=True, null=True)),
                ('place_of_supply', models.CharField(blank=True, default='', max_length=80)),
                ('vehicle_no', models.CharField(blank=True, default='', max_length=32)),
                ('notes', models.TextField(blank=True, default='')),
                ('consignor', models.JSONField(blank=True, default=dict)),
                ('consignee', models.JSONField(blank=True, default=dict)),
                ('total_qty_kg', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('gate_out_at', models.DateTimeField(blank=True, null=True)),
                ('request_key', models.CharField(blank=True, editable=False, max_length=64, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'inventory_job_work_challans',
                'ordering': ['issued_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='JobWorkReturn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=32, unique=True)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('vendor_document_no', models.CharField(blank=True, default='', max_length=80)),
                ('vendor_document_date', models.DateField(blank=True, null=True)),
                ('settled_sent_kg', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('output_kg', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('output_pcs', models.BigIntegerField(default=0)),
                ('balance_kg', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('wastage_kg', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('variance_kg', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('variance_pct', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('variance_reason', models.TextField(blank=True, default='')),
                ('billed_qty', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('billed_uom', models.CharField(blank=True, default='', max_length=8)),
                ('billed_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('billed_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True, default='')),
                ('request_key', models.CharField(blank=True, editable=False, max_length=64, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'inventory_job_work_returns',
                'ordering': ['received_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='JobWorkReturnLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('line_no', models.PositiveIntegerField()),
                ('kind', models.CharField(choices=[('FG_PCS', 'Finished pieces'), ('OUTPUT_ROLL', 'Output roll'), ('OUTPUT_BULK', 'Output bulk'), ('BALANCE_ROLL', 'Balance roll returned'), ('BALANCE_BULK', 'Balance bulk returned'), ('WASTAGE', 'Wastage')], max_length=12)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('uom', models.CharField(max_length=8)),
                ('qty_kg', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('boxes', models.PositiveIntegerField(blank=True, null=True)),
                ('bags', models.PositiveIntegerField(blank=True, null=True)),
                ('returned_to_factory', models.BooleanField(blank=True, null=True)),
                ('roll_label', models.CharField(blank=True, default='', max_length=60)),
                ('meta_json', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'inventory_job_work_return_lines',
                'ordering': ['line_no', 'id'],
            },
        ),
        migrations.CreateModel(
            name='JobWorkSentLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('line_no', models.PositiveIntegerField()),
                ('kind', models.CharField(choices=[('ROLL', 'Roll'), ('BULK', 'Bulk material')], max_length=4)),
                ('is_legacy', models.BooleanField(default=False)),
                ('roll_label', models.CharField(blank=True, default='', max_length=60)),
                ('material_name', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('hsn_code', models.CharField(blank=True, default='', max_length=12)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('uom', models.CharField(default='KG', max_length=8)),
                ('qty_kg', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('width_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('thickness_micron', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rate_per_unit', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('meta_json', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'inventory_job_work_sent_lines',
                'ordering': ['sent_at', 'line_no', 'id'],
            },
        ),
        migrations.CreateModel(
            name='JobWorkSettlement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('RETURN', 'Job-work return'), ('SHORT_CLOSE', 'Short-close write-off'), ('RECONCILE', 'Legacy reconciliation')], max_length=12)),
                ('consumed_qty', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('returned_qty', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('consumed_kg', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('returned_kg', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('written_off', models.BooleanField(default=False)),
                ('note', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'inventory_job_work_settlements',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddField(
            model_name='jobworkorder',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobworkorder',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closed_job_work_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobworkorder',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_job_work_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobworkorder',
            name='expected_output_kind',
            field=models.CharField(choices=[('FG_PCS', 'Finished pieces'), ('ROLLS', 'Rolls'), ('BULK', 'Bulk material')], db_default='ROLLS', default='ROLLS', max_length=8),
        ),
        migrations.AddField(
            model_name='jobworkorder',
            name='expected_qty',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='jobworkorder',
            name='expected_return_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobworkorder',
            name='expected_uom',
            field=models.CharField(blank=True, choices=[('PCS', 'Pieces'), ('KG', 'Kilograms'), ('METER', 'Metres'), ('ROLL', 'Rolls')], db_default='', default='', max_length=8),
        ),
        migrations.AddField(
            model_name='jobworkorder',
            name='number',
            field=models.CharField(blank=True, db_default='', db_index=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='jobworkorder',
            name='process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='job_work_orders', to='factory.process'),
        ),
        migrations.AddField(
            model_name='jobworkorder',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Agreed labour rate per rate_uom (excluding GST).', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='jobworkorder',
            name='rate_uom',
            field=models.CharField(blank=True, choices=[('PCS', 'Per piece'), ('KG', 'Per kg'), ('METER', 'Per metre'), ('ROLL', 'Per roll')], db_default='', default='', max_length=8),
        ),
        migrations.AddField(
            model_name='jobworkorder',
            name='short_close_reason',
            field=models.TextField(blank=True, db_default='', default=''),
        ),
        migrations.AddField(
            model_name='jobworkorder',
            name='wastage_tolerance_pct',
            field=models.DecimalField(db_default=Decimal('3.00'), decimal_places=2, default=Decimal('3.00'), help_text='Unexplained material-balance difference allowed before a reason is required.', max_digits=5),
        ),
        migrations.AddField(
            model_name='vendor',
            name='jobwork_rates',
            field=models.JSONField(blank=True, db_default=models.Value([], output_field=models.JSONField()), default=list, help_text='Agreed job-work labour rates: [{process_code, rate, uom}] (rate excludes GST).', validators=[apps.inventory.models.validate_jobwork_rates]),
        ),
        migrations.AlterField(
            model_name='jobworkorder',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent'), ('PARTLY_RETURNED', 'Partly returned'), ('RETURNED', 'Returned'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled'), ('PARTIAL', 'Partly returned (legacy)')], default='DRAFT', max_length=20),
        ),
        migrations.AddIndex(
            model_name='jobworkorder',
            index=models.Index(fields=['plant', 'status', 'created_at'], name='jobwork_plant_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='jobworkorder',
            constraint=models.UniqueConstraint(condition=models.Q(('number', ''), _negated=True), fields=('number',), name='jobwork_order_number_unique'),
        ),
        migrations.AddField(
            model_name='jobworkchallan',
            name='gate_out_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gated_job_work_challans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobworkchallan',
            name='issued_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issued_job_work_challans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobworkchallan',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challans', to='inventory.jobworkorder'),
        ),
        migrations.AddField(
            model_name='jobworkchallan',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_work_challans', to='factory.plant'),
        ),
        migrations.AddField(
            model_name='jobworkchallan',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_work_challans', to='inventory.vendor'),
        ),
        migrations.AddField(
            model_name='jobworkreturn',
            name='bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jobwork_returns', to='gate.inwardbillintake'),
        ),
        migrations.AddField(
            model_name='jobworkreturn',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='inventory.jobworkorder'),
        ),
        migrations.AddField(
            model_name='jobworkreturn',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_work_returns', to='factory.plant'),
        ),
        migrations.AddField(
            model_name='jobworkreturn',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='received_job_work_returns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobworkreturnline',
            name='bulk_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_work_return_lines', to='inventory.bulktransaction'),
        ),
        migrations.AddField(
            model_name='jobworkreturnline',
            name='fg_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_work_return_lines', to='production.finishedgoodsbatch'),
        ),
        migrations.AddField(
            model_name='jobworkreturnline',
            name='job_work_return',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.jobworkreturn'),
        ),
        migrations.AddField(
            model_name='jobworkreturnline',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_work_return_lines', to='inventory.inventorylocation'),
        ),
        migrations.AddField(
            model_name='jobworkreturnline',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_work_return_lines', to='materials.inventorymaterial'),
        ),
        migrations.AddField(
            model_name='jobworkreturnline',
            name='roll',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_work_return_lines', to='inventory.inventoryroll'),
        ),
        migrations.AddField(
            model_name='jobworkreturnline',
            name='scrap_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_work_return_lines', to='production.scraplog'),
        ),
        migrations.AddField(
            model_name='jobworksentline',
            name='challan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.jobworkchallan'),
        ),
        migrations.AddField(
            model_name='jobworksentline',
            name='from_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_work_sent_lines', to='inventory.inventorylocation'),
        ),
        migrations.AddField(
            model_name='jobworksentline',
            name='granule_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_work_sent_lines', to='materials.granulequalitycode'),
        ),
        migrations.AddField(
            model_name='jobworksentline',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_work_sent_lines', to='materials.inventorymaterial'),
        ),
        migrations.AddField(
            model_name='jobworksentline',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_lines', to='inventory.jobworkorder'),
        ),
        migrations.AddField(
            model_name='jobworksentline',
            name='roll',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_work_sent_lines', to='inventory.inventoryroll'),
        ),
        migrations.AddField(
            model_name='jobworkreturnline',
            name='sent_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_lines', to='inventory.jobworksentline'),
        ),
        migrations.AddField(
            model_name='jobworksettlement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_work_settlements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobworksettlement',
            name='job_work_return',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='inventory.jobworkreturn'),
        ),
        migrations.AddField(
            model_name='jobworksettlement',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='inventory.jobworkorder'),
        ),
        migrations.AddField(
            model_name='jobworksettlement',
            name='sent_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='inventory.jobworksentline'),
        ),
        migrations.AddIndex(
            model_name='jobworkchallan',
            index=models.Index(fields=['plant', 'issued_at'], name='jobwork_challan_plant_idx'),
        ),
        migrations.AddIndex(
            model_name='jobworkreturn',
            index=models.Index(fields=['plant', 'received_at'], name='jobwork_return_plant_idx'),
        ),
        migrations.AddIndex(
            model_name='jobworksentline',
            index=models.Index(fields=['order', 'kind'], name='jobwork_sent_order_idx'),
        ),
        migrations.AddIndex(
            model_name='jobworksettlement',
            index=models.Index(fields=['order', 'sent_line'], name='jobwork_settle_line_idx'),
        ),
    ]
