# Generated by Django 6.0.8 on 2026-10-10 08:07

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0028_enable_print_process_capabilities'),
        ('gate', '0005_backfill_document_headers'),
        ('inventory', '0055_backfill_job_work_numbers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='jobworkorder',
            name='step_release_reason',
            field=models.TextField(blank=True, db_default='', default=''),
        ),
        migrations.AddField(
            model_name='jobworkorder',
            name='step_released_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobworkorder',
            name='step_released_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='released_job_work_steps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='JobWorkBillLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('billed_qty', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('billed_uom', models.CharField(blank=True, default='', max_length=8)),
                ('billed_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('billed_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('received_qty', models.DecimalField(blank=True, decimal_places=3, help_text="This return's received quantity in billed_uom.", max_digits=14, null=True)),
                ('allocated_amount', models.DecimalField(blank=True, decimal_places=2, help_text="This return's share of billed_amount by received quantity.", max_digits=16, null=True)),
                ('return_count', models.PositiveIntegerField(default=1)),
                ('bill_complete', models.BooleanField(default=False)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('request_key', models.CharField(editable=False, max_length=64)),
                ('linked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobwork_bill_links', to='gate.inwardbillintake')),
                ('job_work_return', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='late_bill_link', to='inventory.jobworkreturn')),
                ('linked_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_work_bill_links', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bill_links', to='inventory.jobworkorder')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_work_bill_links', to='factory.plant')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_work_bill_links', to='inventory.vendor')),
            ],
            options={
                'db_table': 'inventory_job_work_bill_links',
                'ordering': ['linked_at', 'id'],
                'indexes': [models.Index(fields=['bill', 'linked_at'], name='jobwork_billlink_bill_idx')],
            },
        ),
    ]
