
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 'rest_framework',
    # 'corsheaders',
    # 'apps.materials',
    # 'apps.recipes',
    # 'apps.factory',
    # 'apps.routing',
    # 'apps.templates',
    # 'apps.sales',
    # 'apps.inventory.apps.InventoryConfig',
    # 'apps.production',
    # 'apps.physics',
    # 'apps.bom',
    # 'apps.users',
    # 'apps.tooling',
    # 'apps.artwork',
    # 'apps.dashboard',
    # 'apps.analytics',
    # 'rest_framework_simplejwt',
]
