# Generated by Django 5.2.10 on 2026-03-06 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportDistributionProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_code', models.CharField(choices=[('production_daily', 'Production Daily'), ('stock_standing_daily', 'Stock Standing Daily')], max_length=64, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('target_roles', models.JSONField(blank=True, default=list)),
                ('extra_recipients', models.JSONField(blank=True, default=list)),
                ('schedule_hour', models.PositiveSmallIntegerField(default=8)),
                ('schedule_minute', models.PositiveSmallIntegerField(default=0)),
                ('email_subject_template', models.CharField(blank=True, default='', max_length=255)),
                ('email_body_template', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_report_distribution_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analytics_report_distribution_profiles',
                'ordering': ['report_code'],
            },
        ),
        migrations.CreateModel(
            name='ReportDispatchRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_code', models.CharField(max_length=64)),
                ('report_date', models.DateField()),
                ('window_start', models.DateTimeField(blank=True, null=True)),
                ('window_end', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped')], default='PENDING', max_length=16)),
                ('recipients', models.JSONField(blank=True, default=list)),
                ('recipient_count', models.PositiveIntegerField(default=0)),
                ('warning_text', models.TextField(blank=True, default='')),
                ('error_text', models.TextField(blank=True, default='')),
                ('provider', models.CharField(blank=True, default='', max_length=32)),
                ('provider_message_id', models.CharField(blank=True, default='', max_length=255)),
                ('pdf_file_name', models.CharField(blank=True, default='', max_length=255)),
                ('pdf_checksum_sha1', models.CharField(blank=True, default='', max_length=40)),
                ('pdf_size_bytes', models.PositiveIntegerField(default=0)),
                ('triggered_manually', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_report_dispatch_runs', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='analytics.reportdistributionprofile')),
            ],
            options={
                'db_table': 'analytics_report_dispatch_runs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['report_code', 'report_date'], name='analytics_r_report__38bd12_idx'), models.Index(fields=['status', 'created_at'], name='analytics_r_status_2f6276_idx')],
            },
        ),
    ]
