# Generated by Django 5.2.10 on 2026-03-14 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportdispatchrun',
            name='detail_checksum_sha1',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='reportdispatchrun',
            name='detail_file_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='reportdispatchrun',
            name='detail_size_bytes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reportdispatchrun',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped'), ('SKIPPED_EMAIL', 'Skipped Email')], default='PENDING', max_length=16),
        ),
    ]
