# Generated by Django 5.2.10 on 2026-03-14 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_reportdispatchrun_detail_checksum_sha1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportdistributionprofile',
            name='report_code',
            field=models.CharField(choices=[('owner_executive_daily', 'Owner Executive Daily'), ('production_daily', 'Production Daily'), ('dispatch_daily', 'Dispatch Daily'), ('packing_dispatch_summary_daily', 'Packing Dispatch Summary Daily'), ('stock_standing_daily', 'Stock Standing Daily')], max_length=64, unique=True),
        ),
    ]
