# Generated by Django 6.0.1 on 2026-01-19 13:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeGrade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'recipe_grades',
            },
        ),
        migrations.CreateModel(
            name='ExtrusionRecipe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('thickness_min_micron', models.IntegerField(default=20)),
                ('thickness_max_micron', models.IntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('film_variant', models.ForeignKey(limit_choices_to={'category': 'FILM_VARIANT', 'is_extrudable': True}, on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='materials.inventorymaterial')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recipes.recipegrade')),
            ],
            options={
                'db_table': 'extrusion_recipes',
                'unique_together': {('film_variant', 'grade', 'thickness_min_micron', 'thickness_max_micron', 'is_active')},
            },
        ),
        migrations.CreateModel(
            name='ExtrusionRecipeComponent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('percentage', models.FloatField(help_text='0-100%')),
                ('granule', models.ForeignKey(limit_choices_to={'category': 'GRANULE'}, on_delete=django.db.models.deletion.PROTECT, to='materials.inventorymaterial')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='recipes.extrusionrecipe')),
            ],
            options={
                'db_table': 'extrusion_recipe_components',
                'unique_together': {('recipe', 'granule')},
            },
        ),
    ]
