# Generated by Django 6.0.8 on 2026-10-07 10:37

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('factory', '0028_enable_print_process_capabilities'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GatePublicRateBucket',
            fields=[
                ('key', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('count', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='GatePublicLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gate_public_link', to='factory.plant')),
            ],
        ),
        migrations.CreateModel(
            name='GateRequestReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.CharField(max_length=128)),
                ('token', models.UUIDField()),
                ('fingerprint', models.CharField(max_length=64)),
                ('response', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('scope', 'token'), name='gate_request_unique')],
            },
        ),
        migrations.CreateModel(
            name='GoodsMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direction', models.CharField(choices=[('INWARD', 'Inward'), ('OUTWARD', 'Outward')], max_length=8)),
                ('invoice_number', models.CharField(max_length=80)),
                ('invoice_normalized', models.CharField(max_length=80)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('invoice_year', models.PositiveIntegerField()),
                ('vehicle_number', models.CharField(max_length=40)),
                ('party_kind', models.CharField(choices=[('VENDOR', 'Vendor'), ('CUSTOMER', 'Customer')], max_length=8)),
                ('party_id', models.UUIDField()),
                ('party_name', models.CharField(max_length=255)),
                ('document_kind', models.CharField(blank=True, max_length=20)),
                ('document_id', models.UUIDField(blank=True, null=True)),
                ('document_snapshot', models.JSONField(blank=True, default=dict)),
                ('reconciliation_status', models.CharField(choices=[('UNMATCHED', 'Unmatched'), ('MATCHED', 'Matched'), ('DISCREPANCY', 'Discrepancy')], default='UNMATCHED', max_length=16)),
                ('discrepancies', models.JSONField(blank=True, default=list)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('logged_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gate_movements', to=settings.AUTH_USER_MODEL)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gate_movements', to='factory.plant')),
            ],
            options={
                'ordering': ['-logged_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='GoodsLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_kind', models.CharField(choices=[('MATERIAL', 'Material'), ('PRODUCT', 'Product'), ('TRADING', 'Trading good'), ('CONSUMABLE', 'Consumable')], max_length=12)),
                ('product_id', models.UUIDField()),
                ('product_name', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=16)),
                ('uom', models.CharField(max_length=10)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('movement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='gate.goodsmovement')),
            ],
        ),
        migrations.CreateModel(
            name='VisitorVisit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('mobile', models.CharField(max_length=16)),
                ('purpose', models.CharField(max_length=80)),
                ('company', models.CharField(blank=True, max_length=160)),
                ('government_id_type', models.CharField(blank=True, max_length=8)),
                ('government_id_encrypted', models.TextField(blank=True)),
                ('government_id_suffix', models.CharField(blank=True, max_length=4)),
                ('selfie_data', models.BinaryField(blank=True, null=True)),
                ('source', models.CharField(choices=[('PUBLIC', 'Public QR'), ('WATCHMAN', 'Watchman')], default='PUBLIC', max_length=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('INSIDE', 'Inside'), ('EXITED', 'Exited'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10)),
                ('submitted_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('consent_at', models.DateTimeField()),
                ('entry_at', models.DateTimeField(blank=True, null=True)),
                ('exit_at', models.DateTimeField(blank=True, null=True)),
                ('entry_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gate_visitor_entries', to=settings.AUTH_USER_MODEL)),
                ('exit_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gate_visitor_exits', to=settings.AUTH_USER_MODEL)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gate_visitors', to='factory.plant')),
            ],
            options={
                'ordering': ['-submitted_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='GateAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gate_assignments', to='factory.plant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gate_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'plant'), name='gate_user_plant_unique')],
            },
        ),
        migrations.CreateModel(
            name='GateAuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.UUIDField(db_index=True)),
                ('object_type', models.CharField(max_length=12)),
                ('action', models.CharField(max_length=24)),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('before', models.JSONField(blank=True, default=dict)),
                ('after', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gate_audit_events', to=settings.AUTH_USER_MODEL)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gate_audit_events', to='factory.plant')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['plant', 'created_at'], name='gate_gateau_plant_i_4380e5_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='goodsmovement',
            index=models.Index(fields=['plant', 'logged_at'], name='gate_goodsm_plant_i_af670d_idx'),
        ),
        migrations.AddIndex(
            model_name='goodsmovement',
            index=models.Index(fields=['reconciliation_status', 'logged_at'], name='gate_goodsm_reconci_165652_idx'),
        ),
        migrations.AddConstraint(
            model_name='goodsmovement',
            constraint=models.UniqueConstraint(fields=('plant', 'direction', 'party_kind', 'party_id', 'invoice_normalized', 'invoice_year'), name='gate_invoice_unique'),
        ),
        migrations.AddConstraint(
            model_name='goodsmovement',
            constraint=models.UniqueConstraint(condition=models.Q(('document_id__isnull', False)), fields=('plant', 'direction', 'document_kind', 'document_id'), name='gate_document_unique'),
        ),
        migrations.AddConstraint(
            model_name='goodsline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='gate_line_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='goodsline',
            constraint=models.CheckConstraint(condition=models.Q(('amount__isnull', True), ('amount__gte', 0), _connector='OR'), name='gate_line_amount_nonnegative'),
        ),
        migrations.AddIndex(
            model_name='visitorvisit',
            index=models.Index(fields=['plant', 'status', 'submitted_at'], name='gate_visito_plant_i_c9df5b_idx'),
        ),
        migrations.AddConstraint(
            model_name='visitorvisit',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['PENDING', 'INSIDE'])), fields=('plant', 'mobile'), name='gate_active_visitor_unique'),
        ),
        migrations.AddConstraint(
            model_name='visitorvisit',
            constraint=models.CheckConstraint(condition=models.Q(('exit_at__isnull', True), models.Q(('entry_at__isnull', False), ('exit_at__gte', models.F('entry_at'))), _connector='OR'), name='gate_exit_after_entry'),
        ),
    ]
