# Generated by Django 6.0.8 on 2026-10-08 14:35

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


def guard_bill_evidence(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    for model, trigger in [("InwardBillPage", "bill_page_immutable"), ("InwardBillReceiptReference", "bill_reference_immutable")]:
        table = apps.get_model("gate", model)._meta.db_table
        schema_editor.execute(f'CREATE TRIGGER {trigger} BEFORE UPDATE OR DELETE ON "{table}" FOR EACH ROW EXECUTE FUNCTION gate_audit_append_only();')
    table = apps.get_model("gate", "InwardBillIntake")._meta.db_table
    schema_editor.execute(f'''CREATE OR REPLACE FUNCTION gate_bill_arrival_immutable() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN
        IF TG_OP = 'DELETE' THEN RAISE EXCEPTION 'Bill arrivals cannot be deleted'; END IF;
        IF (NEW.plant_id, NEW.created_by_id, NEW.arrival_at, NEW.content_hash) IS DISTINCT FROM (OLD.plant_id, OLD.created_by_id, OLD.arrival_at, OLD.content_hash) THEN
            RAISE EXCEPTION 'Bill arrival evidence is immutable'; END IF;
        RETURN NEW;
        END $$;
        CREATE TRIGGER bill_arrival_immutable BEFORE UPDATE OR DELETE ON "{table}" FOR EACH ROW EXECUTE FUNCTION gate_bill_arrival_immutable();''')


def unguard_bill_evidence(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    for model, trigger in [("InwardBillPage", "bill_page_immutable"), ("InwardBillReceiptReference", "bill_reference_immutable"), ("InwardBillIntake", "bill_arrival_immutable")]:
        table = apps.get_model("gate", model)._meta.db_table
        schema_editor.execute(f'DROP TRIGGER IF EXISTS {trigger} ON "{table}";')
    schema_editor.execute('DROP FUNCTION IF EXISTS gate_bill_arrival_immutable();')


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0028_enable_print_process_capabilities'),
        ('gate', '0002_public_links_and_audit_guard'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InwardBillIntake',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('arrival_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('PENDING_GRN', 'Pending GRN'), ('PARTIAL_GRN', 'Partially received'), ('RECEIPTED', 'Receipted'), ('VOID', 'Explained resolution')], default='PENDING_GRN', max_length=16)),
                ('content_hash', models.CharField(db_index=True, max_length=64)),
                ('review_data', models.JSONField(blank=True, default=dict)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_reason', models.CharField(blank=True, max_length=500)),
                ('resolution_code', models.CharField(blank=True, max_length=20)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inward_bill_intakes', to=settings.AUTH_USER_MODEL)),
                ('duplicate_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gate.inwardbillintake')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inward_bill_intakes', to='factory.plant')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resolved_inward_bills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['arrival_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='InwardBillPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('page_number', models.PositiveSmallIntegerField()),
                ('data', models.BinaryField()),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('byte_size', models.PositiveIntegerField()),
                ('sha256', models.CharField(max_length=64)),
                ('intake', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pages', to='gate.inwardbillintake')),
            ],
            options={
                'ordering': ['page_number'],
            },
        ),
        migrations.CreateModel(
            name='InwardBillReceiptReference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('BULK', 'BULK'), ('ROLL', 'ROLL'), ('PACKAGING', 'PACKAGING'), ('PO_RECEIPT', 'PO_RECEIPT'), ('TRADING', 'TRADING')], max_length=12)),
                ('object_id', models.UUIDField()),
                ('snapshot', models.JSONField(default=dict)),
                ('linked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('intake', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_references', to='gate.inwardbillintake')),
                ('linked_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['linked_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='inwardbillintake',
            index=models.Index(fields=['plant', 'status', 'arrival_at'], name='gate_inward_plant_i_63cc23_idx'),
        ),
        migrations.AddConstraint(
            model_name='inwardbillintake',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['PENDING_GRN', 'PARTIAL_GRN']), ('resolved_at__isnull', False), _connector='OR'), name='bill_resolution_timestamp'),
        ),
        migrations.AddConstraint(
            model_name='inwardbillpage',
            constraint=models.UniqueConstraint(fields=('intake', 'page_number'), name='bill_page_order_unique'),
        ),
        migrations.AddConstraint(
            model_name='inwardbillreceiptreference',
            constraint=models.UniqueConstraint(fields=('kind', 'object_id'), name='bill_receipt_source_unique'),
        ),
        migrations.RunPython(guard_bill_evidence, unguard_bill_evidence),
    ]
