# Generated by Django 6.0.8 on 2026-10-09 20:46

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


def guard_document_evidence(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    append_only = [("OutwardDocumentPage", "outward_page_immutable"), ("DocumentOriginalFile", "document_original_immutable"), ("GatePassReturn", "gate_pass_return_immutable")]
    for model, trigger in append_only:
        table = apps.get_model("gate", model)._meta.db_table
        schema_editor.execute(f'CREATE TRIGGER {trigger} BEFORE UPDATE OR DELETE ON "{table}" FOR EACH ROW EXECUTE FUNCTION gate_audit_append_only();')
    outward = apps.get_model("gate", "OutwardDocument")._meta.db_table
    schema_editor.execute(f'''CREATE OR REPLACE FUNCTION gate_outward_departure_immutable() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN
        IF TG_OP = 'DELETE' THEN RAISE EXCEPTION 'Outward departures cannot be deleted'; END IF;
        IF (NEW.plant_id, NEW.created_by_id, NEW.departed_at, NEW.content_hash) IS DISTINCT FROM (OLD.plant_id, OLD.created_by_id, OLD.departed_at, OLD.content_hash) THEN
            RAISE EXCEPTION 'Outward departure evidence is immutable'; END IF;
        RETURN NEW;
        END $$;
        CREATE TRIGGER outward_departure_immutable BEFORE UPDATE OR DELETE ON "{outward}" FOR EACH ROW EXECUTE FUNCTION gate_outward_departure_immutable();''')
    link = apps.get_model("gate", "OutwardDocumentLink")._meta.db_table
    schema_editor.execute(f'''CREATE OR REPLACE FUNCTION gate_outward_link_append_only() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN
        IF TG_OP = 'DELETE' THEN RAISE EXCEPTION 'Outward links cannot be deleted'; END IF;
        IF OLD.removed_at IS NOT NULL THEN RAISE EXCEPTION 'A removed outward link is final'; END IF;
        IF (NEW.document_id, NEW.kind, NEW.object_id, NEW.reference, NEW.snapshot, NEW.link_source, NEW.linked_at, NEW.linked_by_id) IS DISTINCT FROM (OLD.document_id, OLD.kind, OLD.object_id, OLD.reference, OLD.snapshot, OLD.link_source, OLD.linked_at, OLD.linked_by_id) THEN
            RAISE EXCEPTION 'Outward link evidence is immutable'; END IF;
        RETURN NEW;
        END $$;
        CREATE TRIGGER outward_link_append_only BEFORE UPDATE OR DELETE ON "{link}" FOR EACH ROW EXECUTE FUNCTION gate_outward_link_append_only();''')


def unguard_document_evidence(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    for model, trigger in [("OutwardDocumentPage", "outward_page_immutable"), ("DocumentOriginalFile", "document_original_immutable"), ("GatePassReturn", "gate_pass_return_immutable"), ("OutwardDocument", "outward_departure_immutable"), ("OutwardDocumentLink", "outward_link_append_only")]:
        table = apps.get_model("gate", model)._meta.db_table
        schema_editor.execute(f'DROP TRIGGER IF EXISTS {trigger} ON "{table}";')
    schema_editor.execute('DROP FUNCTION IF EXISTS gate_outward_departure_immutable();')
    schema_editor.execute('DROP FUNCTION IF EXISTS gate_outward_link_append_only();')


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0028_enable_print_process_capabilities'),
        ('gate', '0003_inward_bill_intake'),
        ('inventory', '0053_explicit_maintenance_audit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentOriginalFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=80)),
                ('byte_size', models.PositiveIntegerField()),
                ('sha256', models.CharField(max_length=64)),
                ('page_count', models.PositiveSmallIntegerField()),
                ('data', models.BinaryField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DocumentPageView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('page_kind', models.CharField(choices=[('INWARD', 'Inward page'), ('OUTWARD', 'Outward page')], max_length=8)),
                ('page_id', models.UUIDField()),
                ('display_rotation', models.PositiveSmallIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=24)),
                ('fiscal_year', models.PositiveIntegerField()),
                ('last_value', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='GatePass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=32, unique=True)),
                ('kind', models.CharField(choices=[('RETURNABLE', 'Returnable gate pass (RGP)'), ('NON_RETURNABLE', 'Non-returnable gate pass (NRGP)')], max_length=16)),
                ('party_name', models.CharField(max_length=255)),
                ('party_address', models.TextField(blank=True, default='')),
                ('party_gstin', models.CharField(blank=True, default='', max_length=20)),
                ('purpose', models.CharField(choices=[('REPAIR', 'Repair'), ('CALIBRATION', 'Calibration'), ('FABRICATION', 'Fabrication / machining'), ('TRIAL', 'Trial / testing'), ('LOAN', 'Loan / demo'), ('SCRAP_SALE', 'Scrap sale'), ('SAMPLE', 'Sample'), ('RETURN_TO_SUPPLIER', 'Return to supplier'), ('OTHER', 'Other')], max_length=24)),
                ('expected_return_date', models.DateField(blank=True, null=True)),
                ('vehicle_number', models.CharField(blank=True, default='', max_length=40)),
                ('carried_by', models.CharField(blank=True, default='', max_length=120)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ISSUED', 'Issued, waiting at gate'), ('OUT', 'Out of factory'), ('PARTLY_RETURNED', 'Partly returned'), ('RETURNED', 'Returned'), ('CLOSED', 'Closed'), ('SHORT_CLOSED', 'Short-closed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=16)),
                ('notes', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('out_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('close_reason', models.CharField(blank=True, default='', max_length=500)),
                ('version', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='GatePassLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('line_no', models.PositiveSmallIntegerField()),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('uom', models.CharField(max_length=10)),
                ('equipment_text', models.CharField(blank=True, default='', max_length=160)),
                ('serial_no', models.CharField(blank=True, default='', max_length=80)),
                ('approx_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('returned_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('remarks', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'ordering': ['line_no'],
            },
        ),
        migrations.CreateModel(
            name='GatePassReturn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('returned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('general_receipt_line_id', models.UUIDField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, default='', max_length=500)),
            ],
            options={
                'ordering': ['returned_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OutwardDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('departed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('content_hash', models.CharField(db_index=True, max_length=64)),
                ('vehicle_number', models.CharField(blank=True, default='', max_length=40)),
                ('scanned_refs', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('PENDING_MATCH', 'Pending match'), ('MATCHED', 'Matched'), ('DISCREPANCY', 'Discrepancy'), ('VOID', 'Voided')], default='PENDING_MATCH', max_length=16)),
                ('notes', models.CharField(blank=True, default='', max_length=500)),
                ('matched_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_reason', models.CharField(blank=True, default='', max_length=500)),
                ('discrepancies', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['-departed_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='OutwardDocumentLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('SALES_DC', 'Sales delivery challan'), ('CUSTOMER_DISPATCH', 'Customer dispatch / invoice'), ('TRADE_ORDER', 'Trade order invoice'), ('INTERPLANT_DC', 'Inter-plant challan'), ('JOBWORK_CHALLAN', 'Job-work challan'), ('GATE_PASS', 'Gate pass (RGP / NRGP)'), ('OTHER', 'Other / unlisted document')], max_length=20)),
                ('object_id', models.UUIDField(blank=True, null=True)),
                ('reference', models.CharField(blank=True, default='', max_length=120)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('link_source', models.CharField(choices=[('QR', 'QR scan'), ('MANUAL', 'Office match')], default='MANUAL', max_length=8)),
                ('linked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('removed_reason', models.CharField(blank=True, default='', max_length=500)),
            ],
            options={
                'ordering': ['linked_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OutwardDocumentPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('page_number', models.PositiveSmallIntegerField()),
                ('data', models.BinaryField()),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('byte_size', models.PositiveIntegerField()),
                ('sha256', models.CharField(max_length=64)),
            ],
            options={
                'ordering': ['page_number'],
            },
        ),
        migrations.AddField(
            model_name='inwardbillintake',
            name='attached_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supporting_documents', to='gate.inwardbillintake'),
        ),
        migrations.AddField(
            model_name='inwardbillintake',
            name='category',
            field=models.CharField(blank=True, choices=[('STOCK', 'Stock items (GRN)'), ('JOBWORK', 'Job work'), ('SPARES', 'Spares and parts'), ('MACHINERY', 'Machinery and equipment'), ('SERVICE', 'Service / repair'), ('UTILITY', 'Utility'), ('PROFESSIONAL_STATUTORY', 'Professional / statutory fee'), ('TRANSPORT', 'Transport / freight'), ('OTHER_EXPENSE', 'Other expense')], db_default='', default='', max_length=24),
        ),
        migrations.AddField(
            model_name='inwardbillintake',
            name='classified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inwardbillintake',
            name='classified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='classified_inward_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inwardbillintake',
            name='doc_type',
            field=models.CharField(blank=True, choices=[('TAX_INVOICE', 'Tax invoice'), ('DELIVERY_CHALLAN', 'Delivery challan'), ('LR_TRANSPORT', 'Transport LR / consignment note'), ('DEBIT_NOTE', 'Debit note'), ('CREDIT_NOTE', 'Credit note'), ('SERVICE_REPORT', 'Service report'), ('UTILITY_BILL', 'Utility bill'), ('OTHER', 'Other document')], db_default='', default='', max_length=20),
        ),
        migrations.AddField(
            model_name='inwardbillintake',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inwardbillintake',
            name='header_version',
            field=models.PositiveIntegerField(db_default=0, default=0),
        ),
        migrations.AddField(
            model_name='inwardbillintake',
            name='invoice_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inwardbillintake',
            name='invoice_fy',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inwardbillintake',
            name='invoice_normalized',
            field=models.CharField(blank=True, db_default='', db_index=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='inwardbillintake',
            name='invoice_number',
            field=models.CharField(blank=True, db_default='', default='', max_length=80),
        ),
        migrations.AddField(
            model_name='inwardbillintake',
            name='party_name',
            field=models.CharField(blank=True, db_default='', default='', max_length=255),
        ),
        migrations.AddField(
            model_name='inwardbillintake',
            name='ship_to_plant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ship_to_inward_documents', to='factory.plant'),
        ),
        migrations.AddField(
            model_name='inwardbillintake',
            name='source',
            field=models.CharField(choices=[('GATE', 'Gate arrival'), ('OFFICE', 'Received at office')], db_default='GATE', default='GATE', max_length=8),
        ),
        migrations.AddField(
            model_name='inwardbillintake',
            name='tax_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='inwardbillintake',
            name='taxable_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='inwardbillintake',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='inwardbillintake',
            name='valid_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inwardbillintake',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inward_documents', to='inventory.vendor'),
        ),
        migrations.AlterField(
            model_name='inwardbillintake',
            name='status',
            field=models.CharField(choices=[('PENDING_GRN', 'Pending GRN'), ('PARTIAL_GRN', 'Partially received'), ('RECEIPTED', 'Receipted'), ('FILED', 'Filed as record'), ('VOID', 'Explained resolution')], default='PENDING_GRN', max_length=16),
        ),
        migrations.AlterField(
            model_name='inwardbillreceiptreference',
            name='kind',
            field=models.CharField(choices=[('BULK', 'BULK'), ('ROLL', 'ROLL'), ('PACKAGING', 'PACKAGING'), ('PO_RECEIPT', 'PO_RECEIPT'), ('TRADING', 'TRADING'), ('GENERAL_RECEIPT', 'GENERAL_RECEIPT'), ('JOBWORK_RETURN', 'JOBWORK_RETURN')], max_length=16),
        ),
        migrations.AddIndex(
            model_name='inwardbillintake',
            index=models.Index(fields=['vendor', 'invoice_normalized', 'invoice_fy'], name='bill_vendor_invoice_idx'),
        ),
        migrations.AddIndex(
            model_name='inwardbillintake',
            index=models.Index(fields=['category', 'status', 'arrival_at'], name='bill_category_status_idx'),
        ),
        migrations.AddIndex(
            model_name='inwardbillintake',
            index=models.Index(fields=['plant', 'source', 'arrival_at'], name='bill_plant_source_idx'),
        ),
        migrations.AddField(
            model_name='documentoriginalfile',
            name='intake',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='original_files', to='gate.inwardbillintake'),
        ),
        migrations.AddField(
            model_name='documentpageview',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_page_views', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='documentsequence',
            constraint=models.UniqueConstraint(fields=('key', 'fiscal_year'), name='document_sequence_unique'),
        ),
        migrations.AddField(
            model_name='gatepass',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closed_gate_passes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gatepass',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_gate_passes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gatepass',
            name='issued_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issued_gate_passes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gatepass',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gate_passes', to='factory.plant'),
        ),
        migrations.AddField(
            model_name='gatepass',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gate_passes', to='inventory.vendor'),
        ),
        migrations.AddField(
            model_name='gatepassline',
            name='gate_pass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='gate.gatepass'),
        ),
        migrations.AddField(
            model_name='gatepassline',
            name='machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gate_pass_lines', to='factory.machine'),
        ),
        migrations.AddField(
            model_name='gatepassreturn',
            name='inward_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gate_pass_returns', to='gate.inwardbillintake'),
        ),
        migrations.AddField(
            model_name='gatepassreturn',
            name='line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='gate.gatepassline'),
        ),
        migrations.AddField(
            model_name='gatepassreturn',
            name='received_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gate_pass_returns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='outwarddocument',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outward_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='outwarddocument',
            name='matched_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matched_outward_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='outwarddocument',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outward_documents', to='factory.plant'),
        ),
        migrations.AddField(
            model_name='outwarddocumentlink',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='links', to='gate.outwarddocument'),
        ),
        migrations.AddField(
            model_name='outwarddocumentlink',
            name='linked_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outward_links', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='outwarddocumentlink',
            name='removed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='removed_outward_links', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='outwarddocumentpage',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pages', to='gate.outwarddocument'),
        ),
        migrations.AddConstraint(
            model_name='documentpageview',
            constraint=models.UniqueConstraint(fields=('page_kind', 'page_id'), name='document_page_view_unique'),
        ),
        migrations.AddConstraint(
            model_name='documentpageview',
            constraint=models.CheckConstraint(condition=models.Q(('display_rotation__in', [0, 90, 180, 270])), name='document_page_rotation_valid'),
        ),
        migrations.AddIndex(
            model_name='gatepass',
            index=models.Index(fields=['plant', 'status', 'created_at'], name='gate_pass_plant_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='gatepass',
            constraint=models.CheckConstraint(condition=models.Q(('kind', 'NON_RETURNABLE'), ('expected_return_date__isnull', False), ('status__in', ['DRAFT', 'CANCELLED']), _connector='OR'), name='gate_pass_rgp_return_date'),
        ),
        migrations.AddConstraint(
            model_name='gatepassline',
            constraint=models.UniqueConstraint(fields=('gate_pass', 'line_no'), name='gate_pass_line_unique'),
        ),
        migrations.AddConstraint(
            model_name='gatepassline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='gate_pass_line_qty_positive'),
        ),
        migrations.AddConstraint(
            model_name='gatepassline',
            constraint=models.CheckConstraint(condition=models.Q(('returned_quantity__gte', 0), ('returned_quantity__lte', models.F('quantity'))), name='gate_pass_line_returned_bounds'),
        ),
        migrations.AddConstraint(
            model_name='gatepassreturn',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='gate_pass_return_qty_positive'),
        ),
        migrations.AddIndex(
            model_name='outwarddocument',
            index=models.Index(fields=['plant', 'status', 'departed_at'], name='outward_plant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='outwarddocumentlink',
            index=models.Index(fields=['kind', 'object_id'], name='outward_link_object_idx'),
        ),
        migrations.AddConstraint(
            model_name='outwarddocumentlink',
            constraint=models.UniqueConstraint(condition=models.Q(('object_id__isnull', False), ('removed_at__isnull', True)), fields=('document', 'kind', 'object_id'), name='outward_link_active_unique'),
        ),
        migrations.AddConstraint(
            model_name='outwarddocumentpage',
            constraint=models.UniqueConstraint(fields=('document', 'page_number'), name='outward_page_order_unique'),
        ),
        migrations.RunPython(guard_document_evidence, unguard_document_evidence),
    ]
